### PR TITLE
LPS-119591 Add itemsTotal in Custom Fields

### PR DESCRIPTION
**Pull request by murilostodolni**

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:forward

LGTM!

**Comment by murilostodolni** [comment]
ci:test:relevant

**Comment by RafaelCRC** [comment]
@epark18 are these failures related?

**Comment by epark18** [comment]
Failures are unrelated here.

**Comment by epark18** [comment]
Pushed to Brian. https://github.com/brianchandotcom/liferay-portal/pull/120552

**Comment by epark18** [comment]
ci:close

**Pull request closed without merging**
