### PR TITLE
LPS-157692 No limitation for External Reference Code in Account

### PR DESCRIPTION
**Pull request by RafaelCRC**
update for [LPS-157692](https://issues.liferay.com/browse/LPS-157692)

### CODE REVIEW

**Review by gislayne-vitorino — APPROVED** [review]
LGTM, @drewbrokke any thoughts about this one?

**Comment by gislayne-vitorino** [comment]
@patriciajeanperez are these failures related?

**Review by drewbrokke — CHANGES_REQUESTED** [review]
@RafaelCRC let's apply this validation via model hints again instead of `validator` taglibs. I believe the proper hints are already defined.

**Comment by Sharryxue** [comment]
Failures in [ci:test:relevant - RafaelCRC > liferay-usm - PR#710 - 2022-08-26[10:26:57]](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1958434588) are unrelated to the commits here.

**Comment by RafaelCRC** [comment]
my branch got messed up, going to create other with the new changes

**Pull request closed without merging**
