### PR TITLE
LPS-166687,LPS-166688 Allow invitation email templates and token expiration date to be configurable

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test:bundle

**Comment by melodywu** [comment]
ci:test:account

**Comment by Sharryxue** [comment]
- Failure in [semantic-versioning](https://testray.liferay.com/home/-/testray/case_results/2021501133) is related. Refer the full [console log](https://testray.liferay.com/reports/production/logs/2022-10/test-1-38/test-portal-acceptance-pullrequest(master)/4577/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0). Hellp @pei-jung, would you please take a look into it? Thanks.
No other issue find in ci:test:relevant and ci:test:account, all the failed POSHI tests would be fixed with commits in https://github.com/brianchandotcom/liferay-portal/pull/125316 merged. It would be better to retrigger the account test suite after https://github.com/brianchandotcom/liferay-portal/pull/125316 merged in case any issue hides. If we can not wait for it, manual testing would also helps. /cc @patriciajeanperez 
```
     [exec] 9 tests completed, 1 failed
     [exec] 
     [exec] > Task :test:semantic-versioning-test:test
     [exec] 
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/account/account-api] STARTED
     [exec] 
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/account/account-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.account.configuration                  MINOR      2.0.0      2.0.0      2.1.0      VERSION INCREASE REQUIRED
     [exec]     	+   interface  com.liferay.account.configuration.AccountEntryEmailConfiguration
     [exec]     		+   access     abstract
     [exec]     		+   method     invitationEmailBody()
     [exec]     			+   access     abstract
     [exec]     			+   annotated  aQute.bnd.annotation.metatype.Meta$AD
```

**Comment by pei-jung** [comment]
Thanks @Sharryxue! I rebased and resent the PR with the semantic version fix, https://github.com/liferay-usm/liferay-portal/pull/821.

**Pull request closed without merging**
