### PR TITLE
LPS-151602

### PR DESCRIPTION
**Pull request by mbowerman**
/cc @SelenaAungst

https://issues.liferay.com/browse/LPS-151602

### CODE REVIEW

**Comment by epark18** [comment]
Failures here are unrelated to pull.

**Review by drewbrokke — CHANGES_REQUESTED** [review]
Hi @SelenaAungst @mbowerman, thank you for this change. Since the personal menu is used in many places, I think it would be best to reduce the scope of he change to just the System/Instance/Site Settings portlets.

I think we should consider reducing the z-index of the usages of `sticky-top` inside of `configuration-admin-web` to `z-index:999;`

Would you be willing to try that change to see if it addresses the issue? Thank you!

**Comment by SelenaAungst** [comment]
> I think we should consider reducing the z-index of the usages of `sticky-top` inside of `configuration-admin-web` to `z-index:999;` That will put it just below the index of dropdowns for this case only. See [clay's definition file](https://github.com/liferay/clay/blob/aa4653f901d22386711b2807c501e9e94a2a1dd5/packages/clay-css/src/scss/variables/_globals-z-index.scss#L1-L2=).

Hi @drewbrokke,
I added `z-index: 999;` to the `class="sticky-top"` div in the `configuration-admin-web` `view.jsp` file, and that seemed to fix the problem as well. I will get these changes pushed right away. Please let me know if there is anything else I can do!

**Comment by SelenaAungst** [comment]
@drewbrokke,

I have created the new pull request here: https://github.com/liferay-usm/liferay-portal/pull/536. Thank you!

**Pull request closed without merging**
