### PR TITLE
LPS-120257 User category should be under Platform, instead of Commerce

### PR DESCRIPTION
**Pull request by erickmonteiroo**
/cc @drewbrokke @pei-jung

### CODE REVIEW

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
ci:forward

**Comment by epark18** [comment]
ci:test:relevant

**Comment by epark18** [comment]
Failures are unrelated to the PR

**Comment by pei-jung** [comment]
@patriciajeanperez can we forward this one?

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
