### PR TITLE
LPS-143803 Create an endpoint to remove a User from a User Group

### PR DESCRIPTION
**Pull request by erickmonteiroo**
@drewbrokke @pei-jung

### CODE REVIEW

**Review by drewbrokke — APPROVED** [review]
LGTM 👍

**Comment by drewbrokke** [comment]
ci:forward

**Comment by erickmonteiroo** [comment]
ci:forward

**Comment by erickmonteiroo** [comment]
ci:test:relevant

**Comment by erickmonteiroo** [comment]
ci:forward

**Pull request closed without merging**
