### PR TITLE
LPS-146722 SQLServer 2017 - Roles test is failing due to request having too many parameters

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-146722](https://issues.liferay.com/browse/LPS-146722).<br/><br/>/cc @pei-jung @ChrisKian @patriciajeanperez @david-truong @gislayne-vitorino

### CODE REVIEW

**Comment by drewbrokke** [comment]
@patriciajeanperez are these failures related?

**Comment by patriciajeanperez** [comment]
ci:test:roles

**Comment by drewbrokke** [comment]
@patriciajeanperez if this looks good to you, I think we can manually forward.

**Comment by patriciajeanperez** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/129069

**Pull request closed without merging**
