### PR TITLE
[TS] LPS-141727 Change css class name to avoid conflict with aui_deprecated.css

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi Team,

**Notes from @noornajj:**

> https://issues.liferay.com/browse/LPS-141727
> 
> The issue here is that a user's additional information in Members portlet is not visible in Firefox due to css issue with float.
> 
> It was caused by a conflict of the css class name field-group with the file aui_deprecated.css. The issue was fixed by changing the class name to lfr-field-group.
> 
> This issue is no longer reproducible in Master because aui_deprecated.css has been removed. However, we are committing these changes to master to insure consistency between Master and 7.3.x

Please let us know if you have any questions.
Thanks!

### CODE REVIEW

**Review by drewbrokke — COMMENTED** [review]
LGTM 👍

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
@patriciajeanperez if these failures are unrelated, can you please forward this pull? Thanks!

**Comment by patriciajeanperez** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/110123

cc @ericyanLr @drewbrokke

**Comment by patriciajeanperez** [comment]
ci:close

**Pull request closed without merging**
