### PR TITLE
LPS-169033 Trying to associate a user to an account before creating an account make the portlet break

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-169033](https://issues.liferay.com/browse/LPS-169033).

442bbfb17b54 caused this issue. All the account tabs were visible during account creation, which allows for all sorts of issues.

@patriciajeanperez if possible can we add test coverage to assert that the tabs are only visible after the account has been created?

/cc @pei-jung @ChrisKian @david-truong @gislayne-vitorino

### CODE REVIEW

**Comment by drewbrokke** [comment]
FYI @iovaneale

**Comment by drewbrokke** [comment]
@pei-jung any objections to forwarding this one?

**Comment by patriciajeanperez** [comment]
Thank you for the fix, @drewbrokke! Functional test will be added in https://github.com/patriciajeanperez/liferay-portal/pull/703.

**Review by pei-jung — APPROVED** [review]

**Comment by pei-jung** [comment]
ci:forward

**Pull request closed without merging**
