### PR TITLE
LPS-168284 HR_325 SR is announcing the "cancel button" as "cancel link" on add new user page

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Review by drewbrokke — APPROVED** [review]

**Comment by pei-jung** [comment]
@patriciajeanperez are the failures related?

**Comment by patriciajeanperez** [comment]
@pei-jung No related failures. I'll forward the PR

**Comment by patriciajeanperez** [comment]
ci:forward

**Comment by pei-jung** [comment]
@patriciajeanperez if the failures are not related, can you please manually forward this pr to Brian? Thank you!

**Comment by patriciajeanperez** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/129492

**Pull request closed without merging**
