### PR TITLE
LPS-143802 Create GET UserGroup by ExternalReferenceCode for User Group Headless API

### PR DESCRIPTION
**Pull request by erickmonteiroo**
@drewbrokke @pei-jung

### CODE REVIEW

**Comment by erickmonteiroo** [comment]
ci:test:sf

**Comment by erickmonteiroo** [comment]
ci:test:relevant

**Comment by epark18** [comment]
Hello @erickmonteiroo, looks there is a related failure in this pull. Here are the [Error Logs](https://testray.liferay.com/reports/production/logs/2022-01/test-1-36/test-portal-acceptance-pullrequest(master)/220/modules-integration-mysql57-jdk8/0/1/jenkins-console.txt.gz) | [Case Results](1595834567) 

`     [exec] com.liferay.headless.admin.user.resource.v1_0.test.UserGroupResourceTest > testGetUserGroupByExternalReferenceCode FAILED
     [exec]     com.liferay.headless.admin.user.client.problem.Problem$ProblemException: No UserGroup exists with the primary key 0
     [exec]     	at com.liferay.headless.admin.user.client.resource.v1_0.UserGroupResource$UserGroupResourceImpl.getUserGroupByExternalReferenceCode(UserGroupResource.java:348)
     [exec]     	at com.liferay.headless.admin.user.resource.v1_0.test.BaseUserGroupResourceTestCase.testGetUserGroupByExternalReferenceCode(BaseUserGroupResourceTestCase.java:218)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)`

**Comment by erickmonteiroo** [comment]
Closing. I'll send it further with proper fix.

**Pull request closed without merging**
