### PR TITLE
LPS-167667 Remove redundant usages of the method getSearchActionURL from batch-planner-web

### PR DESCRIPTION
**Pull request by gislayne-vitorino**
This is an update for [subtask: LPS-167667](https://issues.liferay.com/browse/LPS-167667), [LPS-161233](https://issues.liferay.com/browse/LPS-161233)

### CODE REVIEW

**Review by drewbrokke — APPROVED** [review]

**Comment by patriciajeanperez** [comment]
ci:test:stable

**Comment by melodywu** [comment]
Because error "java.net.ConnectException: Connection timed out" run ci:test:stable again.

**Comment by melodywu** [comment]
ci:test:stable

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
