### PR TITLE
LPS-147814 Data Truncation error in language key

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by Sharryxue** [comment]
Failure not related, the fix commit is in [BChan's repo](https://github.com/brianchandotcom/liferay-portal/commit/aacd81c6fc535ebbfd62376c6d5be3ff704d1353), not merged yet.

**Comment by drewbrokke** [comment]
ci:reevaluate:1277401_2273

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
@epark18 if there are no related failures, this one is ready to forward.

**Comment by epark18** [comment]
ci:close

**Pull request closed without merging**
