### PR TITLE
LPS-163706 Add all workflow fields to AccountEntry

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-163706](https://issues.liferay.com/browse/LPS-163706).

@pei-jung @ChrisKian @patriciajeanperez @david-truong @gislayne-vitorino

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
ci:test:account

**Comment by melodywu** [comment]
ci:test:bundle

**Comment by melodywu** [comment]
Hello @drewbrokke ,There is a related failure found in ci:test:account result, the Active button disappear. Could you help take a look.Thanks in advance.
*Actual Results*
file:///home/liferay/Downloads/fail.png


*Expected Results*
pass

**Comment by drewbrokke** [comment]
@melodywu thanks for the heads up. I neglected to mention that that is intended behavior - I completely removed the active button. Please see my comment on https://github.com/liferay-usm/liferay-portal/pull/791/commits/0f2cf82fba436fe679ae10e1ec7554f2ec843466.

FYI @patriciajeanperez this requires updates to our functional tests.

**Comment by drewbrokke** [comment]
Just added an update for [LPS-166522](https://issues.liferay.com/browse/LPS-166522) as well.

**Comment by patriciajeanperez** [comment]
@drewbrokke will update them once the pull is ready to be sent. Thanks!

**Review by pei-jung — APPROVED** [review]
LGTM!

**Comment by patriciajeanperez** [comment]
Resent with functional test fixes: https://github.com/liferay-usm/liferay-portal/pull/796

**Pull request closed without merging**
