### PR TITLE
LPS-149559 Error message should show in UI to indicate Data Truncation failure

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-149559](https://issues.liferay.com/browse/LPS-149559).

### CODE REVIEW

**Comment by drewbrokke** [comment]
@epark18 is this a real failure? If not, could we just re-invoke relevant?

**Comment by epark18** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Resent from https://github.com/liferay-usm/liferay-portal/pull/614

**Comment by drewbrokke** [comment]
FYI @hongvo2308 and @tototrinh

**Pull request closed without merging**
