### PR TITLE
LPS-154862 Test for solution already in master

### PR DESCRIPTION
**Pull request by joseluisbango**
Relevant issues:

- https://issues.liferay.com/browse/LPS-154862: Unable to manage a site without the user locale enabled
- https://issues.liferay.com/browse/PTR-3085

Pr fix: https://github.com/liferay-usm/liferay-portal/pull/650

---

Hi @liferay-usm,

This is an addendum to the solution for [LPS-154862](https://issues.liferay.com/browse/LPS-154862) (already in master) with a test requested in https://github.com/brianchandotcom/liferay-portal/pull/120476#issuecomment-1186641587.

The tests try to get the `I18nServlet.I18nData` for a group control panel path and a given locale:

- If the locale is enabled in the instance, a proper `I18nServlet.I18nData` object must be returned.
-  In case the locale is not enabled in the instance, the result must be null. 

Please let me know if you have any questions.

Thanks!

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:forward

**Comment by Sharryxue** [comment]
CI failure, will retry the forward command before manually forwarded it.
/cc @drewbrokke

**Comment by Sharryxue** [comment]
ci:forward

**Comment by Sharryxue** [comment]
The failure not related, will manually forward the commit.

**Comment by Sharryxue** [comment]
ci:close

**Pull request closed without merging**
