### PR TITLE
LPS-135289 Include Account actions in the DTOConverter component

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-135289](https://issues.liferay.com/browse/LPS-135289).<br/><br/>/cc @pei-jung @alee8888 @ChrisKian @patriciajeanperez @lr-leo

@luca-pellizzon @riccardo-alberti will you please look over this change and let me know if I am missing anything? Thank you!

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
Hey @drewbrokke thanks for this. Looks fine to me, but the real issue is when using nested fields (that's what we do).
You can check this one https://issues.liferay.com/browse/LPS-136708
Also just for confirmation, were you also checking actions for users or only for accounts?
Thank you.

**Comment by drewbrokke** [comment]
@luca-pellizzon user actions will be checked under a separate ticket.

Is the nested fields issue restricted to our component, or is it a more wide-spread issue?

**Comment by drewbrokke** [comment]
ci:forward

**Comment by luca-pellizzon** [comment]
@drewbrokke the issue looks like to be a headless generic issue, not only related to accounts

**Comment by drewbrokke** [comment]
Ok, I will keep an eye on that ticket as well then.

**Pull request closed without merging**
