### PR TITLE
LPS-159446 Inconsistency issue in uploading avatar for users and account user

### PR DESCRIPTION
**Pull request by RafaelCRC**
Update for [LPS-159446](https://issues.liferay.com/browse/LPS-159446)

### CODE REVIEW

**Comment by RafaelCRC** [comment]
ci:test:sf

**Comment by RafaelCRC** [comment]
ci:test:relevant

**Review by gislayne-vitorino — COMMENTED** [review]
It looks good to me, I believe you just need to do the semantic versioning issue that [was found.](https://github.com/liferay-usm/liferay-portal/pull/688#issuecomment-1213540110)

**Comment by RafaelCRC** [comment]
ci:test:relevant

**Comment by RafaelCRC** [comment]
Hi @patriciajeanperez, could you check if these failures are related with my changes? Thanks!

**Comment by RafaelCRC** [comment]
ci:test:sf

**Comment by RafaelCRC** [comment]
ci:test:relevant

**Comment by RafaelCRC** [comment]
@pei-jung you're right, i forgot about that, everything should be good to go now.

**Comment by drewbrokke** [comment]
ci:reevaluate:1367401_1832

**Comment by drewbrokke** [comment]
@RafaelCRC looks like some rebase conflicts here

**Comment by RafaelCRC** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
Failures are unrelated @RafaelCRC

**Review by pei-jung — APPROVED** [review]
LGTM! 👍

**Comment by patriciajeanperez** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/121967

**Comment by drewbrokke** [comment]
@RafaelCRC looks like a rebase conflict here.

**Comment by RafaelCRC** [comment]
@drewbrokke @patriciajeanperez sorry for the delay, i did some rework and fixed a mistake i noticed later.

**Comment by RafaelCRC** [comment]
ci:test:sf

**Comment by RafaelCRC** [comment]
ci:test:relevant

**Comment by RafaelCRC** [comment]
ci:stop

**Comment by RafaelCRC** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
Relevant failures are not related

**Review by pei-jung — APPROVED** [review]
Nice work! Changes look good.

**Comment by pei-jung** [comment]
@patriciajeanperez can you forward this to Brian? Thanks!

**Comment by Sharryxue** [comment]
Hello @patriciajeanperez,
Do you need any help for the manual forward if this PR? The [brianchandotcom/liferay-portal#121967](https://github.com/brianchandotcom/liferay-portal/pull/121967) you manually forwarded seems not merged yet.

**Comment by drewbrokke** [comment]
Looks like a rebase is needed on this one before we can manually forward.

**Comment by RafaelCRC** [comment]
ci:relevant

**Comment by RafaelCRC** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
@RafaelCRC was this pr updated only with the rebase or are there additional changes that require review from Drew/Pei? wanted to make sure before I forward. Thanks!

**Comment by RafaelCRC** [comment]
Just the rebase @patriciajeanperez

**Comment by patriciajeanperez** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/122451

**Comment by patriciajeanperez** [comment]
ci:close

**Comment by patriciajeanperez** [comment]
ci:close

**Pull request closed without merging**
