### PR TITLE
master | LPS-143296 Additional commits (test)

### PR DESCRIPTION
**Pull request by davidtellolr**
Hi Team,

This PR comes from [#110959](https://github.com/brianchandotcom/liferay-portal/pull/110959).

The previous PR was merged by Brian, but he required me for a test. 

This new PR only contains the required test.

Please, let me know if you have any doubts.

Thanks.

### CODE REVIEW

**Comment by davidtellolr** [comment]
ci:test:sf

**Comment by epark18** [comment]
ci:test:relevant

**Review by drewbrokke — CHANGES_REQUESTED** [review]
@davidtellolr thank you for writing this test case! There are a number of changes needed before I can send it on, please see my inline comments.

Thank you!

**Comment by davidtellolr** [comment]
Hi Drew,

Thanks for all the comments. I'll analyze all of them and I'll send you the PR fixed. It's the first time I developed a test for Liferay, and I reviewed and got ideas from other tests in the project. I hope to do better next time ;-)

Regards.

**Comment by drewbrokke** [comment]
Sounds good, thank you @davidtellolr!

**Comment by drewbrokke** [comment]
@davidtellolr I'm going to close this PR for now. Feel free to open a new one once you're ready. Thanks!

**Pull request closed without merging**
