### PR TITLE
LPS-164415 Rename the column Website

### PR DESCRIPTION
**Pull request by gislayne-vitorino**
This is an update for: [subtask: LPS-164415](https://issues.liferay.com/browse/LPS-164415), [Task: LPS-155969](https://issues.liferay.com/browse/LPS-155969)

### CODE REVIEW

**Review by RafaelCRC — APPROVED** [review]
LGTM! :+1:

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Review by drewbrokke — APPROVED** [review]

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
Hi @gislayne-vitorino! Can you please take look at the compile error in `website-test`? Thank you!

**Comment by drewbrokke** [comment]
Looks like a real failure here in `directory-web` @gislayne-vitorino

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:reevaluate:1307401_4889

**Comment by drewbrokke** [comment]
@patriciajeanperez are these failures related?

**Comment by patriciajeanperez** [comment]
@drewbrokke sorry for the delay! The failures are not related

**Comment by drewbrokke** [comment]
@patriciajeanperez then I think we're good to forward this one 👍

**Comment by patriciajeanperez** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/124317

**Pull request closed without merging**
