### PR TITLE
LPS-165077 Allow parameter field name with an underscore

### PR DESCRIPTION
**Pull request by joanagrego**
Hi team,

I was trying to import data to a Custom Object via Import/Export Center and we notice that we were having a problem with our relationship field with the User, which has the `"r_userToApplications_userId"` format.

When we tried to import data, we got an error in `_com.liferay.batch.planner.exception.BatchPlannerMappingInternalFieldNameException_.`

We investigated and found a treatment of parameters with an underscore, which we fixed in this PR.

Could you please review this pull request?
Thank you!

### CODE REVIEW

**Comment by joanagrego** [comment]
ci:test:sf

**Comment by joanagrego** [comment]
ci:stop

**Review by drewbrokke — CHANGES_REQUESTED** [review]
@joanagrego thank you for sending this change. I am not familiar with this framework, so I will be learning at this point, but I think in any case it is necessary to add an integration or unit test case to demonstrate the issue and to prevent future regressions.

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
@joanagrego this code is owned by liferay-headless/liferay-portal can you forward this PR there?

**Comment by drewbrokke** [comment]
@joanagrego I'm going to close this pull per @4lejandrito's comment above. Please re-send to @liferay-headless. Thank you!

**Comment by joanagrego** [comment]
@drewbrokke Sure! Thank you :ok:

**Pull request closed without merging**
