### PR TITLE
LPS-172507 Fix the flaky tests testAuthenticateByEmailAddress and testLockout

### PR DESCRIPTION
**Pull request by gislayne-vitorino**
This is an update for: [subtask LPS-172507](https://issues.liferay.com/browse/LPS-172507), [LPS-166748](https://issues.liferay.com/browse/LPS-166748)

/cc: @rafaprax @drewbrokke

### CODE REVIEW

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Review by drewbrokke — CHANGES_REQUESTED** [review]
@gislayne-vitorino looks good. Just one change - please leave a comment with the ticket number here and a brief explanation why this is necessary. Then we can leave a longer analysis in the ticket. That way, when a future dev encounters this code, they will quickly understand why it's important.

Thanks! LMK if you have any questions.

**Comment by gislayne-vitorino** [comment]
ci:test:relevant

**Comment by gislayne-vitorino** [comment]
ci:stop

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
ci:test:relevant

**Review by drewbrokke — APPROVED** [review]
LGTM 👍

**Comment by drewbrokke** [comment]
@rafaprax FYI

**Comment by drewbrokke** [comment]
ci:reevaluate:1377401_8252

**Comment by drewbrokke** [comment]
@patriciajeanperez do you see any unique failures here? Also, are the log failures from the ticket present here?

**Comment by patriciajeanperez** [comment]
No related failures @drewbrokke @gislayne-vitorino

**Comment by patriciajeanperez** [comment]
ci:forward

**Comment by drewbrokke** [comment]
@patriciajeanperez we need to also run the suites that contain `UserLocalServiceTest` and `UserAccountResourceTest`, since they are the ones that are "failing" according to the ticket, and I don't think they will run as part of the `relevant` suite for this. Would you be willing to trigger them?

**Comment by patriciajeanperez** [comment]
Hi @drewbrokke, they ran and were passing: [UserLocalServiceTest](https://testray.liferay.com/reports/production/logs/2023-01/test-1-36/test-portal-acceptance-pullrequest(master)/2858/modules-integration-mysql57-jdk8/4/2/jenkins-console.txt.gz?authuser=0) & [UserAccountResourceTest](https://testray.liferay.com/reports/production/logs/2023-01/test-1-36/test-portal-acceptance-pullrequest(master)/2858/modules-integration-mysql57-jdk8/1/24/jenkins-console.txt.gz?authuser=0). One thing to note though is that it is a flaky failure so we will have to run the tests a few more times to see if it is now stable. Would you be ok if I send this in now and reopen if the same issue appears in the next builds?

**Comment by patriciajeanperez** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/129180

**Pull request closed without merging**
