### PR TITLE
LPS-143986 Create DELETE UserGroup by ExternalReferenceCode for User Group Headless API

### PR DESCRIPTION
**Pull request by erickmonteiroo**
@drewbrokke @pei-jung

### CODE REVIEW

**Comment by erickmonteiroo** [comment]
ci:test:relevant

**Comment by erickmonteiroo** [comment]
ci:test:relevant

**Comment by erickmonteiroo** [comment]
ci:reevaluate:1267401_1487

**Comment by erickmonteiroo** [comment]
ci:reevaluate:1267401_1487

**Review by drewbrokke — APPROVED** [review]
LGTM 👍

**Comment by drewbrokke** [comment]
ci:forward

**Comment by erickmonteiroo** [comment]
ci:forward

**Comment by erickmonteiroo** [comment]
ci:forward

**Pull request closed without merging**
