### PR TITLE
LPS-138597 Filter Account Addresses by Type

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:reevaluate:1287401_340

**Review by drewbrokke — APPROVED** [review]
LGTM 👍

**Comment by drewbrokke** [comment]
ci:reevaluate:1287401_340

**Comment by pei-jung** [comment]
Resent as https://github.com/liferay-usm/liferay-portal/pull/269

**Pull request closed without merging**
