### PR TITLE
LPS-138590 Include the account-admin-web module in the release build

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
@patriciajeanperez are these failures related?

**Comment by patriciajeanperez** [comment]
@drewbrokke they are not related, I will manually forward.

**Comment by patriciajeanperez** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/106592

**Comment by patriciajeanperez** [comment]
ci:close

**Pull request closed without merging**
