### PR TITLE
LPS-178511 Feature Flag property changes are not read during tests

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-178511](https://issues.liferay.com/browse/LPS-178511).

@ethib137 @pei-jung @4lejandrito @patriciajeanperez

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:help

**Comment by patriciajeanperez** [comment]
ci:test:object

**Comment by patriciajeanperez** [comment]
Failures are unrelated @drewbrokke @4lejandrito

**Comment by drewbrokke** [comment]
Thanks @patriciajeanperez!

**Comment by drewbrokke** [comment]
ci:forward:force

**Pull request closed without merging**
