### PR TITLE
LPS-149522 Inconsistent name format for import and export language key

### PR DESCRIPTION
**Pull request by pei-jung**
Screen Shot 2022-04-18 at 11 48 31 AM

### CODE REVIEW

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
@pei-jung looks like a rebase error.

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
