### PR TITLE
LPS-132460 Cannot update Account Address phone number

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-132460](https://issues.liferay.com/browse/LPS-132460).<br/><br/>/cc @alee8888 @ChrisKian @dejuknow @patriciajeanperez

FYI @brunoquei2105, this is the issue we observed earlier today. It is a separate issue, unrelated to your changes.

@pei-jung Please see the updated test case. The assertions were masking the issue.

### CODE REVIEW

**Comment by Sharryxue** [comment]
No specific issue found, the fix commit for the failure is merged in BChan's repo, will retrigger the relevant test later.

**Comment by Sharryxue** [comment]
ci:test:relevant

**Review by pei-jung — APPROVED** [review]
LGTM!

**Comment by pei-jung** [comment]
ci:forward

**Pull request closed without merging**
