### PR TITLE
LPS-136288 Profile picture is missing server side validation on the size

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-136288](https://issues.liferay.com/browse/LPS-136288).

Hey @IstvanD, will you please look over this solution and let me know if it fulfills the requirements on the ticket? 

I'll keep it open here so you can evaluate it and let me know the result. Thank you!

cc @ChrisKian @pei-jung

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
Hi @drewbrokke 

Thank you for the solution! I have tested it with intercepting the `_com_liferay_image_uploader_web_portlet_ImageUploaderPortlet_maxFileSize` parameter, but the newly added `UploadUserPortraitPortletFilter` filter sets the `maxFileSize` reliably to the correct value. 👍

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
