### PR TITLE
LPS-146722 SQLServer 2017 - Roles test is failing due to request having too many parameters

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-146722](https://issues.liferay.com/browse/LPS-146722).<br/><br/>/cc @pei-jung @ChrisKian @patriciajeanperez @david-truong @gislayne-vitorino

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:reevaluate:1277401_6492

**Comment by drewbrokke** [comment]
@patriciajeanperez are these failures related?

**Comment by patriciajeanperez** [comment]
No related failures @drewbrokke

**Comment by drewbrokke** [comment]
Superseded by https://github.com/liferay-usm/liferay-portal/pull/936

**Pull request closed without merging**
