### PR TITLE
LPS-131761 Remove supplemental DSL Queries from bridged Commerce Account services

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by Sharryxue** [comment]
The failed POSHI test is due to issue addressed in LPS-134610, not related.
For the Semantic Versioning issue, it seems related to the changes, would you please double check @pei-jung? [Jenkins Console log](https://testray.liferay.com/reports/production/logs/2021-06/test-1-17/test-portal-acceptance-pullrequest(master)/7867/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz).
Thanks
```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/commerce/commerce-account-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.commerce.account.service.persistence   MAJOR      7.0.0      7.0.0      8.0.0      VERSION INCREASE REQUIRED
     [exec]     	-   class      com.liferay.commerce.account.service.persistence.CommerceAccountOrganizationRelUtil
```

**Review by drewbrokke — APPROVED** [review]
LGTM 👍

**Comment by drewbrokke** [comment]
@pei-jung once you force-push the semver fixes, go ahead and invoke ci : forward.

**Comment by pei-jung** [comment]
ci:forward

**Comment by Sharryxue** [comment]
The failed POSHI test is due to issue addressed in [LPS-134610](https://issues.liferay.com/browse/LPS-134610), not related. Will manually forweard the commits.

**Pull request closed without merging**
