### PR TITLE
LPS-151917 As a developer using headless endpoints, I'd like to get a region by regionId

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by pei-jung** [comment]
@drewbrokke since LPS-151916 has not been merged yet, i'm sending this change on top of it. Please just review the changes for LPS-151917. I'll rebase when the other PR is merged. Thanks!

**Comment by epark18** [comment]
CI failures are unrelated to pull.

**Review by drewbrokke — APPROVED** [review]

**Comment by pei-jung** [comment]
ci:forward

**Comment by drewbrokke** [comment]
ci:forward

**Comment by epark18** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
Hello @pei-jung ,
seems the [semantic-versioning-jdk8/0/0](https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/6176//consoleText) for headless.admin.address.resource.v1_0 need changes, would you please checking it? Thanks in advance.

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:reevaluate:1267401_2978

**Comment by Sharryxue** [comment]
The failures are unrelated. Thanks.

**Comment by pei-jung** [comment]
Hi @epark18, can we manually forward this PR?

**Comment by epark18** [comment]
Pushed to BChan. https://github.com/brianchandotcom/liferay-portal/pull/117210

**Comment by pei-jung** [comment]
Thanks @epark18!

**Pull request closed without merging**
