### PR TITLE
LPS-170760 Allow mapping a configuration to a visibility controller in either direction

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-170760](https://issues.liferay.com/browse/LPS-170760).

/cc @pei-jung @ChrisKian @patriciajeanperez @david-truong @gislayne-vitorino

### CODE REVIEW

**Comment by drewbrokke** [comment]
@stian-sigvartsen take a look at https://github.com/liferay-usm/liferay-portal/pull/906/commits/28531571b2ed6b3c561a78af5a5dc9db9a963f50 and let me know what you think. Thanks!

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by melodywu** [comment]
ci:test:help

**Comment by melodywu** [comment]
ci:test:mfa

**Comment by melodywu** [comment]
No related issue found in ci:test:relevant. Note still waiting for ci:test:mfa results.

**Comment by melodywu** [comment]
ci:test:mfa

**Comment by melodywu** [comment]
Hello @pei-jung , There are related failures found in ci:test:relevant result,
[modules-semantic-versioning-jdk8/0/6](https://testray.liferay.com/home/-/testray/case_results/2119604089?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2119604011%26testrayRunId%3D2119604029%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)

```
[exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/static/portal-configuration/portal-configuration-metatype-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.portal.configuration.metatype.annotations MINOR      1.5.0      1.5.0      1.6.0      VERSION INCREASE REQUIRED
     [exec]     	<   annotation com.liferay.portal.configuration.metatype.annotations.ExtendedObjectClassDefinition
     [exec]     		+   method     visibilityControllerKey()
     [exec]     			+   access     abstract
     [exec]     			+   default    
     [exec]     			+   return     java.lang.String
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 6.1.0
     [exec]         at org.junit.Assert.fail(Assert.java:88)
     [exec]         at org.junit.Assert.assertTrue(Assert.java:41)
     [exec]         at org.junit.Assert.assertFalse(Assert.java:64)
```
Could you help with confirm @pei-jung ? Thanks in advance.

**Comment by drewbrokke** [comment]
@melodywu thanks for the heads up, I'll fix it.

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by melodywu** [comment]
No related issue found in ci:test:relevant.

**Comment by melodywu** [comment]
ci:test:system

**Comment by melodywu** [comment]
ci:test:system

**Review by pei-jung — APPROVED** [review]
LGTM! 👍

**Comment by pei-jung** [comment]
@patriciajeanperez can you forward this Brian if the failures are not related?

**Comment by Sharryxue** [comment]
ci:close

**Pull request closed without merging**
