### PR TITLE
LPS-155475 Fix typeId in upgrade process


### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by Sharryxue** [comment]
No related failure found in ci:test:relevant suite, will trigger the upgrade test suite to confirm the new added upgrade process.

**Comment by Sharryxue** [comment]
ci:test:upgrade

**Review by drewbrokke — APPROVED** [review]

**Comment by Sharryxue** [comment]
No related failure found in ci:test:upgrade test suite, the new added upgrade process completed with no error.
```
 [parallel] 2022-06-09 05:00:35.080 INFO  [Portal Dependency Manager Component Executor--1][UpgradeProcess:97] Upgrading com.liferay.commerce.internal.upgrade.v8_5_0.CommerceAddressTypeUpgradeProcess
 [parallel] 2022-06-09 05:00:35.092 INFO  [Portal Dependency Manager Component Executor--1][UpgradeProcess:112] Completed upgrade process com.liferay.commerce.internal.upgrade.v8_5_0.CommerceAddressTypeUpgradeProcess in 12 ms
```

**Comment by drewbrokke** [comment]
@Sharryxue is this one good to go? If so then we can forward it.

**Comment by Sharryxue** [comment]
Manually Forwarded.
[brianchandotcom/liferay-portal#118805](https://github.com/brianchandotcom/liferay-portal/pull/118805)

**Comment by Sharryxue** [comment]
ci:close

**Pull request closed without merging**
