### PR TITLE
LPS-148855

### PR DESCRIPTION
**Pull request by mbowerman**
https://issues.liferay.com/browse/LPS-148855

### CODE REVIEW

**Comment by epark18** [comment]
Test failures are unrelated to commits.

**Review by drewbrokke — CHANGES_REQUESTED** [review]
@mbowerman thank you for sending this update. It makes sense. Would you be willing to include an integration test case for this scenario as well?

**Comment by mbowerman** [comment]
Hi @drewbrokke ,

I added an integration test. Unfortunately, I wasn't able to test it very thoroughly locally because I ran into lots of issues trying to run integration tests locally. I did manage to run just the test method itself one time and it passed, so sending it for review.

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:forward

**Comment by epark18** [comment]
Hello @mbowerman, would you be able to look at these errors? The failures appear to be related to the changes. Thank you!
[com.liferay.portal.security.permission.test.PermissionCheckerTest](https://testray.liferay.com/home/-/testray/case_results/1631785652) | [Jenkins Log](https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/803/modules-integration-mysql57-jdk8/0/2/jenkins-console.txt.gz?authuser=0)
```
     [exec] com.liferay.portal.security.permission.test.PermissionCheckerTest > testGetGuestUserRoleIdsDoesNotIncludeGuestGroupRole STARTED
     [exec] 2022-03-10 16:54:51.230 ERROR [com.liferay.portal.security.permission.test-executor-thread][BasePermissionChecker:123] null
     [exec] com.liferay.portal.kernel.exception.NoSuchUserException: No User exists with the key {companyId=20100, defaultUser=true}
     [exec] 	at com.liferay.portal.service.persistence.impl.UserPersistenceImpl.findByC_DU(UserPersistenceImpl.java:4548) ~[portal-impl.jar:?]
```
[com.liferay.portal.security.permission.test.ResourceLocalServiceTest](https://testray.liferay.com/home/-/testray/case_results/1631785671) | [Jenkins Log](https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/803/modules-integration-mysql57-jdk8/0/2/jenkins-console.txt.gz?authuser=0)
```     [exec] com.liferay.portal.security.permission.test.ResourceLocalServiceTest > testAddResourcesConcurrently STARTED
     [exec] 
     [exec] com.liferay.portal.security.permission.test.ResourceLocalServiceTest > testAddResourcesConcurrently FAILED
     [exec]     com.liferay.portal.kernel.exception.NoSuchUserException: No User exists with the key {companyId=20100, defaultUser=true} 
```
[com.liferay.portal.security.permission.test.UserBagFactoryTest](https://testray.liferay.com/home/-/testray/case_results/1631785685) | [Jenkins Log](https://testray.liferay.com/reports/production/logs/2022-03/test-1-37/test-portal-acceptance-pullrequest(master)/803/modules-integration-mysql57-jdk8/0/2/jenkins-console.txt.gz?authuser=0)
```
     [exec] com.liferay.portal.security.permission.test.UserBagFactoryTest > testGetGroups FAILED
     [exec]     com.liferay.portal.kernel.exception.NoSuchUserException: No User exists with the key {companyId=20100, defaultUser=true}
     [exec]     	at com.liferay.portal.service.persistence.impl.UserPersistenceImpl.findByC_DU(UserPersistenceImpl.java:4548)
```

**Comment by mbowerman** [comment]
Oh, it's probably because I set the defaultUser to the "_user" variable, causing it to get deleted after the test. Let me fix that.

**Comment by mbowerman** [comment]
I force-pushed a fix @epark18

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@epark18 is that a related failure?

**Comment by epark18** [comment]
These failures are unrelated.

**Comment by Sharryxue** [comment]
Hello @drewbrokke,
Not sure if this is good to forward, since there is new commit come in, this probably need a manually forward due to the relevant failure. Thanks
/cc @epark18

**Comment by drewbrokke** [comment]
ci:forwrad

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
