### PR TITLE
LPS-163311 When test add the contact information via appearance in Instance Configuration there is error

### PR DESCRIPTION
**Pull request by gislayne-vitorino**
Update for [LPS-163311](https://issues.liferay.com/browse/LPS-163311)

### CODE REVIEW

**Review by RafaelCRC — APPROVED** [review]
LGTM!

**Comment by Sharryxue** [comment]
ci:test:system

**Comment by Sharryxue** [comment]
No related issue found in ci:test:system. The failed tests more like a flaky failure.

**Review by drewbrokke — APPROVED** [review]

**Comment by gislayne-vitorino** [comment]
@drewbrokke I pushed the fix and also updated the Phone's attribute to `listTypeId`, since the [LPS-162450](https://issues.liferay.com/browse/LPS-162450) has already been merged.

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
