### PR TITLE
[TS] LPS-147639 Make profile image responsive and set margin on select button

### PR DESCRIPTION
**Pull request by evibudai**
Hi Team,

LPS: https://issues.liferay.com/browse/LPS-147639

The image is not responsive when selecting it to upload on a mobile viewport and there is no margin above the select button.
NotResponsive

Fix:
The img-fluid class is applied on the image element to make it responsive, and the mt-2 class is applied to add a top margin on the select button.
Responsive

Could you please review it?
Thank you!

### CODE REVIEW

**Comment by evibudai** [comment]
ci:test:sf

**Comment by evibudai** [comment]
ci:test:relevant

**Comment by evibudai** [comment]
Hi @liferay-usm,
could you please review my PR?
Thanks!

**Comment by pei-jung** [comment]
ci:forward

**Pull request closed without merging**
