### PR TITLE
LPS-169455 Portal URL is null in account created notification email for users added via Headless API

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by Sharryxue** [comment]
No related failure found in [ci:test:relevant](https://github.com/liferay-usm/liferay-portal/pull/885#issuecomment-1325841543).

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
@patriciajeanperez this one is good to go. I ran `forward` again but if it fails and the results look ok, go ahead and manually forward.

**Comment by patriciajeanperez** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/126965

**Pull request closed without merging**
