### PR TITLE
LPS-154715 It's possible to remove the user role from the default associations

### PR DESCRIPTION
**Pull request by gislayne-vitorino**

### CODE REVIEW

**Review by drewbrokke — CHANGES_REQUESTED** [review]
@gislayne-vitorino this looks good. Please also update the description of this property to indicate that User role is always granted, so it is not necessary to define it here.

**Comment by gislayne-vitorino** [comment]
ci:stop

**Comment by gislayne-vitorino** [comment]
ci:stop

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:reevaluate:1297401_3697

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
ci:test:relevant

**Review by drewbrokke — APPROVED** [review]

**Comment by epark18** [comment]
Ci failures are unrelated here.

**Comment by drewbrokke** [comment]
@epark18 if the failures are unrelated, I'd say this one is good go.

**Comment by epark18** [comment]
ci:close

**Pull request closed without merging**
