### PR TITLE
LPS-176492 Check if the page is My Account and, if so, hide the editing buttons

### PR DESCRIPTION
**Pull request by jonathanmccann**
This change is mirroring what is done for the other sections on this page:

Sites - https://github.com/liferay/liferay-portal/blob/master/modules/apps/users-admin/users-admin-web/src/main/resources/META-INF/resources/user/sites.jsp#L44
User Groups - https://github.com/liferay/liferay-portal/blob/master/modules/apps/users-admin/users-admin-web/src/main/resources/META-INF/resources/user/user_groups.jsp#L43

Without this check in place a user can see the "Select" button, even if they do not have permission. Clicking it leads to an error page. Likewise, users with "Delete" permission can see that button and while it does work it seems this button should also be hidden on the My Account page.

Please let me know if there are any questions or concerns.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
@drewbrokke Thanks for taking a look. I've pushed up the changes but let me know if there is anything else.

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
ci:test:sf

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
ci:reevaluate:1377401_9419

**Comment by drewbrokke** [comment]
@patriciajeanperez if this looks good to you, we can manually forward or force.

**Comment by patriciajeanperez** [comment]
ci:test:users

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
