### PR TITLE
LPS-160379 New countries and regions are inactive by default

### PR DESCRIPTION
**Pull request by gislayne-vitorino**
This is an update for [LPS-160379](https://issues.liferay.com/browse/LPS-160379).

### CODE REVIEW

**Review by RafaelCRC — APPROVED** [review]
Seems like a simple fix
LGTM :+1:

**Comment by RafaelCRC** [comment]
@drewbrokke any thoughs?

**Review by drewbrokke — APPROVED** [review]
LGTM 👍

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
