### PR TITLE
LPS-139992 User cannot assign Job Title when creating Account Users

### PR DESCRIPTION
**Pull request by erickmonteiroo**

### CODE REVIEW

**Comment by erickmonteiroo** [comment]
ci:test:relevant

**Comment by erickmonteiroo** [comment]
ci:test:account

**Comment by erickmonteiroo** [comment]
ci:test:sf

**Comment by erickmonteiroo** [comment]
@epark18 Hey! Are these failures related to the pull?

**Comment by epark18** [comment]
Failures are unrelated :) @erickmonteiroo

**Comment by erickmonteiroo** [comment]
ci:foward

**Comment by erickmonteiroo** [comment]
ci:forward

**Pull request closed without merging**
