### PR TITLE
LPS-163009 Add user registration page for new account users to sign up

### PR DESCRIPTION
**Pull request by pei-jung**
The sign up page will be accessible via this url: `http://localhost:8080/home?p_p_id=com_liferay_account_admin_web_internal_portlet_AccountUsersRegistrationPortlet&p_p_lifecycle=0&p_p_state=maximized&p_p_mode=view&_com_liferay_account_admin_web_internal_portlet_AccountUsersRegistrationPortlet_mvcRenderCommandName=%2Faccount_admin%2Fcreate_account_user&ticketKey=`

Screen Shot 2022-09-21 at 1 29 30 PM

**Login page after user created an user account**
Screen Shot 2022-09-21 at 1 35 52 PM

**Error page**
Screen Shot 2022-09-21 at 12 22 31 PM

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
Related failure found, could you please take a look into it @pei-jung, thanks in advance.
- Fail to start the Account bundle, got console error like following, refer [console log](https://testray.liferay.com/reports/production/logs/2022-09/test-1-37/test-portal-acceptance-pullrequest(master)/5169/functional-smoke-wildfly180-mariadb106-jdk8/0/0/jenkins-console.txt.gz?authuser=0).
```
    [junit] 2022-09-21 23:15:18.493 ERROR [ServerService Thread Pool -- 76][DirectoryWatcher:1173] Unable to start bundle: file:/opt/dev/projects/github/liferay-portal/bundles/osgi/modules/com.liferay.account.admin.web.jar
    [junit] org.osgi.framework.BundleException: Could not resolve module: com.liferay.account.admin.web [550]
    [junit]   Unresolved requirement: Import-Package: com.liferay.petra.portlet.url.builder
    [junit] 
```

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
ci:test:account

**Comment by Sharryxue** [comment]
No related failure found in ci:test:account.

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
