### PR TITLE
LPS-160355 Modify macros to adapt new markup

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
----
In order to replace all frontend:cards from portal we should update the users admin web module to use clay:cards

[Link to the issue](https://issues.liferay.com/browse/LPS-160355)

Proposed Solution
----
The pull includes the following changes for users and organizations

Users:
* Update UserVerticalCard to accept actions
* Creates new java class with dropdown actions
* Use clay dropdown to show actions on list and descriptive view
* Use clay user card on icon view

Organizations:
* Creates OrganizationVerticalCard
* Creates new java class with dropdown actions
* Use clay dropdown to show actions on list and descriptive view
* Use clay vertical card on icon view

Also the first two commits are about removing unused code.

Please let me know if you have any question.

### CODE REVIEW

**Comment by ealonso** [comment]
cc: @drewbrokke

**Comment by Sharryxue** [comment]
No related failure found in ci:test:relevant.

**Comment by ealonso** [comment]
Hey @drewbrokke,

Do you have any update?

I've send this one 1 month ago 😞. I want to start removing old taglibs, and this one is blocking me.

Regards,
Eudaldo

**Comment by drewbrokke** [comment]
@ealonso I'll have it reviewed by EOD today. My apologies on the delay.

**Comment by drewbrokke** [comment]
ci:reevaluate:1377401_4853

**Review by drewbrokke — APPROVED** [review]
Looks good, thanks @ealonso!

**Comment by drewbrokke** [comment]
@patriciajeanperez do you see any blocking test failures? If not, we can forward this one.

**Comment by patriciajeanperez** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/122985

**Pull request closed without merging**
