### PR TITLE
LPS-143017 Unable to close the Valid Domains modal in add account user page

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by epark18** [comment]
No related failures to pull :]

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
ci:forward

**Comment by epark18** [comment]
The CI failure looks like is resolved now according to this [Slack Thread](https://liferay.slack.com/archives/CLBE14570/p1639608215148900). Will test with a retrigger.

**Comment by epark18** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
