### PR TITLE
LPS-162450 Rename the column Phone

### PR DESCRIPTION
**Pull request by gislayne-vitorino**

### CODE REVIEW

**Review by RafaelCRC — APPROVED** [review]
LGTM! :+1:

**Comment by Sharryxue** [comment]
No related failure found in ci:test:relevant.

**Review by drewbrokke — APPROVED** [review]
LGTM 👍

**Comment by drewbrokke** [comment]
ci:forward

**Comment by Sharryxue** [comment]
Will manually forward the commits.

**Comment by Sharryxue** [comment]
ci:close

**Pull request closed without merging**
