### PR TITLE
LPS-170759 Clean up unnecessary implementations of ConfigurationVisibilityController

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-170759](https://issues.liferay.com/browse/LPS-170759).

/cc @pei-jung @ChrisKian @gislayne-vitorino

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:usm

**Comment by melodywu** [comment]
ci:test:bundle

**Comment by Sharryxue** [comment]
Related issue found in ci:test:relevant 
- [modules-semantic-versioning-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/2112740642?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2112733399%26testrayRunId%3D2112733436%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc), refer full [console log](https://testray.liferay.com/reports/production/logs/2022-12/test-1-37/test-portal-acceptance-pullrequest(master)/6878/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0). There are several semantic-versioning in it, like `social.activity.configuration`,` blogs.configuration`, `bookmarks.configuration`, `dynamic.data.mapping.configuration` and so.
```     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/dynamic-data-mapping/dynamic-data-mapping-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.dynamic.data.mapping.configuration     CHANGED    1.2.1      1.2.1      1.2.2      VERSION INCREASE REQUIRED
     [exec]     	~   interface  com.liferay.dynamic.data.mapping.configuration.DDMGroupServiceConfiguration
     [exec]     		~   annotated  com.liferay.portal.configuration.metatype.annotations.ExtendedObjectClassDefinition
     [exec]     			+   property   strictScope=true
     [exec]     * com.liferay.dynamic.data.mapping.data.provider.configuration CHANGED    1.1.0      1.1.0      1.1.1      VERSION INCREASE REQUIRED
```
- Test Fix, hello @drewbrokke, I'd like to confirm for the intended change in this PR, should we fix the failed POSHI tests here or we can leave them for the related team? I would suggest leave them for the related teams since they can decide whether remove or updated the tests. Examples of failed tests like:
  - [LocalFile.Forms#AutosaveIntervalCanBeConfigured](https://testray.liferay.com/home/-/testray/case_results/2112739492) fails due to the Forms is removed from System Settings.

  - [BlogsEntry#NotificationIsReceivedByNewEntryCreator](https://testray.liferay.com/home/-/testray/case_results/2112736844), failed due to the Blogs Service is removed

**Comment by drewbrokke** [comment]
@Sharryxue there should be **no** functional test changes needed. If there are, it is my mistake.

**Pull request closed without merging**
