### PR TITLE
LPS-161083 No limitation in country name

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-161083](https://issues.liferay.com/browse/LPS-161083).

Resent based off of https://github.com/brianchandotcom/liferay-portal/pull/123492#issuecomment-1254013790.

This actually only changes the test method name, rather than merging into `updateCountry` as requested. The reason for this is that it does not test the `updateCountry` method, but rather tests the `updateCountryLocalizations` method.

FYI @brianchandotcom

/cc @pei-jung @ChrisKian @patriciajeanperez @david-truong @gislayne-vitorino @RafaelCRC

### CODE REVIEW

**Comment by Sharryxue** [comment]
ci:test:bundle

**Comment by Sharryxue** [comment]
Seems there is a related failure when start portal, will manually confirm the issue with the bundle build in pr.
Based on the CI result, when start the bundle, there is a console error like following occurs, refer the [console log](https://testray.liferay.com/reports/production/logs/2022-09/test-1-27/test-portal-acceptance-pullrequest(master)/5110/modules-integration-mysql57-jdk8/3/4/jenkins-console.txt.gz?authuser=0).
```
[beanshell] 2022-09-21 21:38:02.007 ERROR [Start Level: Equinox Container: 74f7c108-55eb-44ea-8796-42fd0c56d1c0][DataGuardConnector:56] Encountered a problem while using 127.0.0.1:42763. Shutting down now.
[beanshell] java.net.BindException: Address already in use (Bind failed)
[beanshell] 	at java.net.PlainSocketImpl.socketBind(Native Method) ~[?:1.8.0_121]
[beanshell] 	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387) ~[?:1.8.0_121]
[beanshell] 	at java.net.ServerSocket.bind(ServerSocket.java:375) ~[?:1.8.0_121]
[beanshell] 	at java.net.ServerSocket.<init>(ServerSocket.java:237) ~[?:1.8.0_121]
```

**Comment by Sharryxue** [comment]
With the bundle build above, there is no console error when start the bundle. Added Address and Country for a quick test, there is no console error as well. The failure probably caused by CI issue, could you help me with a double check of this @patriciajeanperez? Thanks in advance.
Will retrigger the relevant while waiting for a reply.

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:forward

**Comment by patriciajeanperez** [comment]
Hi @drewbrokke, was trying to forward manually but got rebase errors. Would you please check? Thank you!

**Comment by drewbrokke** [comment]
@patriciajeanperez just force-pushed to the branch. Please let me know if you see any other issues. Thanks!

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
Will manually forward the commits. Refer https://github.com/brianchandotcom/liferay-portal/pull/123661

**Comment by Sharryxue** [comment]
ci:close

**Pull request closed without merging**
