### PR TITLE
LPS-138931 Changing pagination in a different page will hide roles

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-138931](https://issues.liferay.com/browse/LPS-138931).

@pei-jung will you take a look at these changes to make sure I didn't miss anything?

I think the takeaway from this bug is that any method that returns a `BaseModelSearchResult` and is not using indexer search should probably apply a similar fix to this one. Let's keep an eye out for other potential issues along the same lines.

/cc @pei-jung @alee8888 @ChrisKian @patriciajeanperez @lr-leo @erickmonteiroo

### CODE REVIEW

**Review by pei-jung — APPROVED** [review]
LGTM!

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by epark18** [comment]
ci:test:relevant

**Comment by epark18** [comment]
Failures are unrelated

**Comment by pei-jung** [comment]
@patriciajeanperez can we forward this?

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
