### PR TITLE
LPS-128837 As an Instance Administrator, I want to set the allowed redirection domains

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-128837](https://issues.liferay.com/browse/LPS-128837).<br/><br/>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez @epgarcia

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:forward

**Comment by Sharryxue** [comment]
Hello @drewbrokke 
There is a related failure found in the ci:test:relevant test suite, the _upgrade process for module com.liferay.redirect.service_ failed when upgrading from 7310 to master.
Error message like following. You can refer the details in [console](https://testray.liferay.com/reports/production/logs/2021-05/test-1-19/test-portal-acceptance-pullrequest(master)/8357/functional-upgrade-tomcat90-mysql57-jdk8/0/6/jenkins-console.txt.gz), [testray report](https://testray.liferay.com/zh/home/-/testray/case_results/1533950960)
```
     [java] 2021-05-19 23:20:14.014 ERROR [main][UpgradeStepRegistratorTracker:143] Failed upgrade process for module com.liferay.redirect.service
     [java] java.lang.IllegalStateException: Unable to upgrade com.liferay.redirect.service to 3.0.1 from 3.0.0
```

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
Thank you @Sharryxue for pointing that out! Fixed :)

**Pull request closed without merging**
