### PR TITLE
LPS-167687 Remove redundant usages of the method getSearchActionURL from commerce-item-selector-web

### PR DESCRIPTION
**Pull request by gislayne-vitorino**
This is an update for [subtask: LPS-167687](https://issues.liferay.com/browse/LPS-167687), [LPS-161233](https://issues.liferay.com/browse/LPS-161233)

### CODE REVIEW

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
ci:test:relevant

**Comment by melodywu** [comment]
Relevant failures are not related

**Comment by patriciajeanperez** [comment]
Sent in https://github.com/liferay-usm/liferay-portal/pull/852

**Pull request closed without merging**
