### PR TITLE
LPS-137546 Unable to select language in Language Selector

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-137546](https://issues.liferay.com/browse/LPS-137546).
This is an update for [LPS-137691](https://issues.liferay.com/browse/LPS-137691).

/cc @pei-jung @alee8888 @ChrisKian @patriciajeanperez @lr-leo

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
SF failure looks related to https://github.com/hhuijser/liferay-portal/pull/5783. Filed issue in https://issues.liferay.com/browse/LPS-137854

**Comment by drewbrokke** [comment]
Thanks @patriciajeanperez. If the relevant and stable suites pass, will you please forward to Brian?

**Comment by patriciajeanperez** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/105998

**Comment by patriciajeanperez** [comment]
ci:close

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
@brianchandotcom Can you publish the latest SF, thanks.

**Pull request closed without merging**
