### PR TITLE
LPS-144367 Optimize the query to use index

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-144367

/cc @hongvo2308 

Existing index is on classNameId, classPK and isn't currently used due to classPK being declared second. Adding classNameId to the query resolves the issue.

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:stop

**Comment by holatuwol** [comment]
ci:close

**Comment by holatuwol** [comment]
ci:reopen

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
Hi @holatuwol, the solution looks fine to me. Do you mind sending this to the core team for another look since performance tuning is more in their domain?

**Comment by holatuwol** [comment]
https://github.com/liferay-core-infra/liferay-portal/pull/166

**Pull request closed without merging**
