### PR TITLE
LPS-161019 Enable Account Administrators to edit basic user info for users who have valid email addresses

### PR DESCRIPTION
**Pull request by patriciajeanperez**
> This is an update for [LPS-161019](https://issues.liferay.com/browse/LPS-161019).

/cc @drewbrokke @pei-jung @ChrisKian @david-truong @gislayne-vitorino @RafaelCRC

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
ci:test:account

**Comment by patriciajeanperez** [comment]
Hi @drewbrokke, are these valid test cases to add or are these already covered through the backend?

- Account Admin can only edit users of the same email address as the valid domain
- Account Admin cannot edit users by default / when account domain is disabled
- Can view valid domains via widget, but cannot add or remove domain

**Comment by patriciajeanperez** [comment]
Pushed in additional test fix and no more regressions are found. Is this good to forward or is there any additional review needed for this one? Thanks! @pei-jung @drewbrokke

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:reevaluate:1267401_4950

**Comment by drewbrokke** [comment]
@patriciajeanperez if this looks good to you, I think we're ok to forward.

Any objections, @pei-jung?

**Comment by pei-jung** [comment]
Changes look good! You can go ahead and forward this @patriciajeanperez. Thanks!

**Comment by patriciajeanperez** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/122905

**Pull request closed without merging**
