### PR TITLE
LPS-167671 Remove redundant usages of the method getSearchActionURL from change-tracking-web

### PR DESCRIPTION
**Pull request by gislayne-vitorino**
This is an update for [subtask: LPS-167671](https://issues.liferay.com/browse/LPS-167671), [LPS-161233](https://issues.liferay.com/browse/LPS-161233)

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:forward

**Comment by Sharryxue** [comment]
Will retry the forward command, seems it is hanging somewhere.

**Comment by Sharryxue** [comment]
ci:forward

**Comment by pyoo47** [comment]
ci:test:stable

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
