### PR TITLE
LPS-136691 Add an API to retrieve a users's account roles for an account

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-136691](https://issues.liferay.com/browse/LPS-136691).<br/><br/>/cc @pei-jung @alee8888 @ChrisKian @patriciajeanperez @lr-leo @amosfong

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:forward

**Comment by Sharryxue** [comment]
The SF failure not related, the ci:test:relevant test suite more like failed for a CI server issue. Will retrigger the ci:test:relevant.

**Comment by Sharryxue** [comment]
ci:test:relevan

**Comment by drewbrokke** [comment]
ci:close

**Comment by drewbrokke** [comment]
See https://github.com/liferay-usm/liferay-portal/pull/222

**Pull request closed without merging**
