### PR TITLE
LPS-139045 com.liferay.commerce.account.service upgrade - Could not parse column as time - MariaDB

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-139045](https://issues.liferay.com/browse/LPS-139045).<br/><br/>/cc @pei-jung @alee8888 @ChrisKian @patriciajeanperez @lr-leo @brunoquei2105 @erickmonteiroo

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:upgrade

**Comment by patriciajeanperez** [comment]
ci:test:upgrade

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:test:upgrade

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
Upgrade failures are unrelated. is this pull ready to be forwarded? @drewbrokke

**Comment by drewbrokke** [comment]
@patriciajeanperez ready!

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
