### PR TITLE
LPS-139992 User cannot assign Job Title when creating Account Users

### PR DESCRIPTION
**Pull request by erickmonteiroo**

### CODE REVIEW

**Comment by erickmonteiroo** [comment]
ci:test:sf

**Comment by erickmonteiroo** [comment]
ci:test:relevant

**Comment by erickmonteiroo** [comment]
ci:test:account

**Comment by erickmonteiroo** [comment]
ci:test:account

**Comment by erickmonteiroo** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@patriciajeanperez are these failures related?

**Comment by patriciajeanperez** [comment]
No failures related to this pull @erickmonteiroo @drewbrokke

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by erickmonteiroo** [comment]
ci:test:sf

**Comment by erickmonteiroo** [comment]
ci:test:relevant

**Comment by erickmonteiroo** [comment]
ci:test:account

**Comment by epark18** [comment]
Failures from account are unrelated to this pull. `Accounts#CanChangePaginationInRolesList` and `Accounts#CanDefineGroupScopePermissionsInRolesAdmin` seem to be flaky and are documented. `modules-semantic-versioning-jdk8/0/2` is failing across many other PRs currently.

**Comment by erickmonteiroo** [comment]
ci:test:sf

**Comment by erickmonteiroo** [comment]
ci:test:relevant

**Comment by erickmonteiroo** [comment]
ci:test:account

**Comment by erickmonteiroo** [comment]
ci:test:sf

**Comment by erickmonteiroo** [comment]
ci:test:relevant

**Comment by erickmonteiroo** [comment]
ci:test:account

**Comment by erickmonteiroo** [comment]
ci:test:sf

**Comment by erickmonteiroo** [comment]
ci:test:relevant

**Comment by erickmonteiroo** [comment]
ci:test:account

**Comment by erickmonteiroo** [comment]
ci:test:relevant

**Review by pei-jung — APPROVED** [review]
LGTM 👍

**Comment by pei-jung** [comment]
ci:forward

**Pull request closed without merging**
