### PR TITLE
[TS] LPS-134096

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-134096

Resent from https://github.com/brianchandotcom/liferay-portal/pull/103881 with changes made.  Please let me know if you have any questions, thanks!

CC @drewbrokke

### CODE REVIEW

**Comment by drewbrokke** [comment]
LGTM 👍

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
@ChrisKian the semver changes don't look related to yours, but perhaps a rebase would solve it?

**Comment by ChrisKian** [comment]
Resent here: https://github.com/liferay-usm/liferay-portal/pull/132

**Pull request closed without merging**
