### PR TITLE
LPS-166023 Instance mail settings value should be inherited with DB Partition

### PR DESCRIPTION
**Pull request by hongvo2308**
Hi,
This is the PR for the ticket https://issues.liferay.com/browse/LPS-166023. Please help to review this and leave your comments.

**Note:**
- The actually result of [LPS-166023](https://issues.liferay.com/browse/LPS-166023) is affected by [LPS-163793](https://issues.liferay.com/browse/LPS-163793). Instead of localhost, it is blank. I have confirmed with the reporter and she said that the expected result of [LPS-166023](https://issues.liferay.com/browse/LPS-166023) should not be affected. The inherited should still inherit.
- The idea of this fix is to copy the value of the System Portal Reference for all Database Partitions and also to update them when the System Portal Reference is updated.

Thank you
CC: @tototrinh

### CODE REVIEW

**Comment by melodywu** [comment]
No related issue found in ci:test:relevant. Note still waiting for ci:test:upgrade-all results.

**Comment by melodywu** [comment]
No related issue found in ci:test:relevant and ci:test:upgrade-all.

**Comment by Sharryxue** [comment]
ci:test:system

**Comment by melodywu** [comment]
No related issue found in ci:test:system.

**Review by drewbrokke — COMMENTED** [review]
@hongvo2308 thank you for sending this change. I think we can accomplish this without copying data around. I gave it a shot and come up with something [here](https://github.com/liferay-usm/liferay-portal/pull/924). Please let me know what you think. Thanks!

**Comment by drewbrokke** [comment]
See https://github.com/liferay-usm/liferay-portal/pull/924

**Comment by tototrinh** [comment]
Hi @drewbrokke, thank you for bringing the solution. It's really nice to accomplish this without copying data around.

**Pull request closed without merging**
