### PR TITLE
LPS-173854 Headless API doesn't return clear error message for duplicate organizations

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-173854](https://issues.liferay.com/browse/LPS-173854).<br/><br/>/cc @pei-jung @ChrisKian @patriciajeanperez @david-truong @gislayne-vitorino

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:reevaluate:1387401_6095

**Comment by drewbrokke** [comment]
@patriciajeanperez any related failures here?

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
