### PR TITLE
LPS-148257 NPE is thrown when attempting to add new role

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by Sharryxue** [comment]
The failure are flaky, not related to the commits, you can also refer the results in [Sharryxue/liferay-portal#331](https://github.com/Sharryxue/liferay-portal/pull/331), all related tests passed.

**Comment by drewbrokke** [comment]
Thanks @Sharryxue. If that's the case, would you be willing to manually forward this fix? Thanks!

cc @epark18

**Comment by epark18** [comment]
Pushed to Bchan at [#113976](https://github.com/brianchandotcom/liferay-portal/pull/113976)

**Comment by epark18** [comment]
ci:close

**Pull request closed without merging**
