### PR TITLE
LPS-138864

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-138864

I have added three new tests to reproduce the issues, see commit [`c2d106e` (#256)](https://github.com/liferay-usm/liferay-portal/pull/256/commits/c2d106e532dfa2cbd7ade21453726a5a4b7e9fb9)

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Review by drewbrokke — APPROVED** [review]
Thanks for the tests @jorgediaz-lr!

**Comment by drewbrokke** [comment]
ci:forward

**Comment by jorgediaz-lr** [comment]
No problem! @drewbrokke

**Pull request closed without merging**
