### PR TITLE
LPS-130381 Eliminate "two star" wildcard usages for the emailAddress field

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:stop

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:users

**Comment by pei-jung** [comment]
ci:test:users

**Comment by pei-jung** [comment]
ci:stop

**Comment by pei-jung** [comment]
ci:test:users

**Comment by patriciajeanperez** [comment]
Failing tests from ci:test:users are unrelated.

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
Forwarded to https://github.com/brianchandotcom/liferay-portal/pull/101430

**Pull request closed without merging**
