### PR TITLE
LPS-143693 AccountRole CI Semantic Versioning failure

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-143693](https://issues.liferay.com/browse/LPS-143693).

/cc @pei-jung @alee8888 @ChrisKian @patriciajeanperez @lr-leo @erickmonteiroo

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
@patriciajeanperez are these failures related?

**Comment by patriciajeanperez** [comment]
Hey @drewbrokke, it doesn't look related. I can manually forward this one.

**Comment by patriciajeanperez** [comment]
@drewbrokke same changes were merged here: https://github.com/liferay/liferay-portal/commit/0f6913f629aad7c9812d7fb6e4d86b407ccecef7#diff-f623b622c442227749131a8585564e5cb116c80935cba55162b1476e34256b61

**Comment by patriciajeanperez** [comment]
ci:close

**Pull request closed without merging**
