### PR TITLE
[TS] LPS-139617

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-139617

Please let me know if you have any questions, or if I should forward this PR to Core Infrastucture instead, thanks!

### CODE REVIEW

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
ci:forward

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
Failures are unrelated @pei-jung @ChrisKian

**Comment by pei-jung** [comment]
@patriciajeanperez is this safe to forward manually?

**Comment by patriciajeanperez** [comment]
Yes, I can do that @pei-jung

**Comment by pei-jung** [comment]
thanks @patriciajeanperez!

**Comment by patriciajeanperez** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/107988

**Comment by patriciajeanperez** [comment]
ci:close

**Pull request closed without merging**
