### PR TITLE
LPS-138380 Changing pagination in Account Roles hides other roles

### PR DESCRIPTION
**Pull request by erickmonteiroo**

### CODE REVIEW

**Review by drewbrokke — APPROVED** [review]
LGTM 👍

**Comment by drewbrokke** [comment]
ci:forward

**Comment by erickmonteiroo** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
@erickmonteiroo failures are unrelated. will manually forward!

**Comment by patriciajeanperez** [comment]
ci:test:account

**Comment by patriciajeanperez** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/106597

**Comment by patriciajeanperez** [comment]
ci:close

**Pull request closed without merging**
