### PR TITLE
LPS-140939 As a remote System Admin, I can set the email and name of the admin when creating a virtual instance

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-140939](https://issues.liferay.com/browse/LPS-140939).<br/><br/>/cc @pei-jung @alee8888 @ChrisKian @patriciajeanperez @lr-leo @erickmonteiroo

This is a follow-up pull to add the `writeOnly` attribute to the admin info. No functional changes, just a more expressive schema.

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
ci:reevaluate:1347401_821

**Comment by drewbrokke** [comment]
@patriciajeanperez is this failure unique? This change is in a completely different module.

**Comment by patriciajeanperez** [comment]
Hey @drewbrokke, I've only seen the assertion failure for [UserAccountResourceTest.testGetUserAccountsPageWithSortDateTime](https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1/28913//testReport/com.liferay.headless.admin.user.resource.v1_0.test/UserAccountResourceTest/testGetUserAccountsPageWithSortDateTime) in this PR. The failures look similar to the one I found in another test though (https://issues.liferay.com/browse/LPS-147014). So maybe we can include this test in that LPS.

**Comment by epark18** [comment]
@drewbrokke There are no unique failures from this most recent run :]

**Comment by drewbrokke** [comment]
@epark18 thanks! Would you be willing to manually forward to Brian?

**Comment by epark18** [comment]
Pushed to BChan. 
[#113504](https://github.com/brianchandotcom/liferay-portal/pull/113504)

**Comment by epark18** [comment]
ci:close

**Pull request closed without merging**
