### PR TITLE
LPS-175159 Migrate feature flag reads to use the new API

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-175159](https://issues.liferay.com/browse/LPS-175159).

FYI @ling-alan-huang

/cc @pei-jung @ChrisKian @patriciajeanperez @david-truong @gislayne-vitorino

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
SF failures are not related to this PR.

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
Hey @drewbrokke, most of the tests are blocked by the following NPE:

`java.lang.NullPointerException
		at com.liferay.feature.flag.web.internal.feature.flag.FeatureFlagManagerImpl.lambda$isEnabled$0(FeatureFlagManagerImpl.java:41)
		at com.liferay.feature.flag.web.internal.company.feature.flags.CompanyFeatureFlagsProvider.withCompanyFeatureFlags(CompanyFeatureFlagsProvider.java:62)
		at com.liferay.feature.flag.web.internal.feature.flag.FeatureFlagManagerImpl.isEnabled(FeatureFlagManagerImpl.java:39)
		at com.liferay.feature.flag.web.internal.feature.flag.FeatureFlagManagerImpl.isEnabled(FeatureFlagManagerImpl.java:46)
		at com.liferay.portal.kernel.feature.flag.FeatureFlagManagerUtil.lambda$isEnabled$4(FeatureFlagManagerUtil.java:56)
		at com.liferay.portal.kernel.feature.flag.FeatureFlagManagerUtil._withFeatureFlagManager(FeatureFlagManagerUtil.java:66)
		at com.liferay.portal.kernel.feature.flag.FeatureFlagManagerUtil.isEnabled(FeatureFlagManagerUtil.java:55)
		at com.liferay.analytics.message.sender.model.listener.BaseEntityModelListener.onAfterCreate(BaseEntityModelListener.java:180)
		at com.liferay.analytics.message.sender.model.listener.BaseEntityModelListener.onAfterCreate(BaseEntityModelListener.java:82)
		at com.liferay.portal.kernel.service.persistence.impl.BasePersistenceImpl.update(BasePersistenceImpl.java:800)
		at com.liferay.portal.service.impl.CompanyLocalServiceImpl._addDefaultUser(CompanyLocalServiceImpl.java:1873)
		at com.liferay.portal.service.impl.CompanyLocalServiceImpl.addCompany(CompanyLocalServiceImpl.java:273)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50)
		at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69)
		at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
		at com.liferay.change.tracking.internal.aop.CTTransactionAdvice.invoke(CTTransactionAdvice.java:79)
		at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
		at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49)
		at com.sun.proxy.$Proxy86.addCompany(Unknown Source)
		at com.liferay.portal.kernel.service.CompanyLocalServiceUtil.addCompany(CompanyLocalServiceUtil.java:81)
		at com.liferay.portal.kernel.test.util.CompanyTestUtil.addCompany(CompanyTestUtil.java:48)
		at com.liferay.portal.kernel.test.util.CompanyTestUtil.addCompany(CompanyTestUtil.java:42)
		at com.liferay.portal.upgrade.test.UpgradeCompanyIdTest.testUpgradeNullValues(UpgradeCompanyIdTest.java:104)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
		at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
		at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
		at org.junit.rules.RunRules.evaluate(RunRules.java:20)
		at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:237)
		at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
		at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
		at org.junit.rules.RunRules.evaluate(RunRules.java:20)
		at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:316)
		at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
		at java.lang.Thread.run(Thread.java:745)`

**Comment by drewbrokke** [comment]
Thanks @patriciajeanperez! I'll get on it.

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@patriciajeanperez are those SF failures unique? I fixed the one re: the properties because it's relevant, but the rest shouldn't have anything to do with my changes.

**Comment by patriciajeanperez** [comment]
Hi @drewbrokke, SF failures are similar upstream. However, I will re-run relevant because there was a CI issue that wasn't running the tests.

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:sf

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/130658

**Pull request closed without merging**
