### PR TITLE
LPS-161083 No limitation in country name

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-161083](https://issues.liferay.com/browse/LPS-161083).

/cc @tototrinh @ces-huynguyen

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
No related failure found in [ci:test:relevant](https://github.com/liferay-usm/liferay-portal/pull/737#issuecomment-1250086568) result.

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
@patriciajeanperez I think this one is good to go 👍

**Comment by patriciajeanperez** [comment]
ci:forward

**Comment by drewbrokke** [comment]
ci:reevaluate:1317401_5108

**Comment by drewbrokke** [comment]
@patriciajeanperez we can forward this one.

**Comment by patriciajeanperez** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/123492

**Pull request closed without merging**
