### PR TITLE
[TS] LPS-149351

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-149351

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by Sharryxue** [comment]
Failure note related to the commit here, it's addressed in [COMMERCE-8730](https://issues.liferay.com/browse/COMMERCE-8730).

**Comment by epark18** [comment]
ci:test:relevant

**Comment by epark18** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Closing after my conversation with @jonathanmccann. I think we should always provide the User role, it should not be removable.

**Pull request closed without merging**
