### PR TITLE
LPS-162684 Add default getSearchActionURL to SearchContainerManagementToolbarDisplayContext

### PR DESCRIPTION
**Pull request by gislayne-vitorino**
This is an update for [LPS-161233](https://issues.liferay.com/browse/LPS-161233), sub-task: [LPS-162684](https://issues.liferay.com/browse/LPS-162684)

### CODE REVIEW

**Review by RafaelCRC — APPROVED** [review]
LGTM! :+1:

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@gislayne-vitorino looks like a version bump is needed. Please run `gradlew baseline` in `modules/apps/frontend-taglib/frontend-taglib-clay/`.

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
Hi @gislayne-vitorino, can you look at the issue in DIsplay Page Templates? It should be same as this [one](https://github.com/liferay-usm/liferay-portal/pull/716#issuecomment-1235591250). Thank you!

**Comment by drewbrokke** [comment]
@gislayne-vitorino need any input from me on this one?

Also, it looks like some merge conflicts are present..

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Closing in favor of https://github.com/liferay-usm/liferay-portal/pull/740

**Pull request closed without merging**
