### PR TITLE
LPS-142491 Obtain user from correct company if DBPartition is enabled

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:test:sf

**Comment by epgarcia** [comment]
ci:test:relevant

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
ci:forward

**Comment by epark18** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
@liferay-usm I don't think the issue is related to my changes. Can you confirm? Thx

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by epark18** [comment]
@epgarcia yes the failure in `semantic-versioning-jdk8/0/0` looks like was occurring across many PRs during the time the last relevant was run so your pull should not have any other issues.

**Comment by drewbrokke** [comment]
@patriciajeanperez if the failures here are unrelated, I'm ok to manually forward this change.

**Comment by patriciajeanperez** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/110118

@epgarcia @drewbrokke @epark18

**Comment by patriciajeanperez** [comment]
ci:close

**Pull request closed without merging**
