### PR TITLE
LPS-169864 Ensure that users can only impersonate users whom they have permissions to view

### PR DESCRIPTION
**Pull request by mbowerman**
Ticket: [LPS-169864](https://issues.liferay.com/browse/LPS-169864)

Re-sent from https://github.com/liferay-usm/liferay-portal/pull/888

### CODE REVIEW

**Comment by drewbrokke** [comment]
@patriciajeanperez can we please run the tests that cover `oauth2-provider` and `multi-factor-authentication`? They are potentially impacted by this change.

**Comment by Sharryxue** [comment]
ci:test:mfa

**Comment by Sharryxue** [comment]
ci:test:oauth2

**Comment by melodywu** [comment]
No related issue found in ci:test:relevant and ci:test:mfa and ci:test:oauth2.

**Comment by drewbrokke** [comment]
ci:reevaluate:1297401_5608

**Comment by drewbrokke** [comment]
ci:forward

**Review by drewbrokke — APPROVED** [review]

**Review by drewbrokke — CHANGES_REQUESTED** [review]
@mbowerman just chatted with Chris. Let's hold off on this one for a bit - I'm not entirely confident this is a true bug.

**Comment by drewbrokke** [comment]
I'm going to close this one for now pending further conversation with the AppSec team.

**Pull request closed without merging**
