### PR TITLE
LPS-154702 Fix swallowed exceptions in PortalInstanceLifecycleListenerImpl when populating countries and regions

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by Sharryxue** [comment]
Related failure found as listed, @pei-jung could you please take a look into the issues? Thanks in advance.

- _Region code is null_
```
     [exec] 2022-05-28 05:12:44.354 ERROR [main][PortalInstanceLifecycleListenerImpl:167] null
     [exec] com.liferay.portal.kernel.exception.RegionCodeException: Region code is null
     [exec] 	at com.liferay.portal.service.impl.RegionLocalServiceImpl._validate(RegionLocalServiceImpl.java:327) ~[portal-impl.jar:?]
     [exec] 	at com.liferay.portal.service.impl.RegionLocalServiceImpl.addRegion(RegionLocalServiceImpl.java:67) ~[portal-impl.jar:?]
```
- _Failed upgrade process com.liferay.portal.upgrade.v7_4_x.UpgradeCountryCode_
```
     [java] 2022-05-28 04:54:47.447 INFO  [main][UpgradeProcess:97] Upgrading com.liferay.portal.upgrade.v7_4_x.UpgradeCountryCode
     [java] 2022-05-28 04:54:47.448 INFO  [main][UpgradeProcess:112] Failed upgrade process com.liferay.portal.upgrade.v7_4_x.UpgradeCountryCode in 1 ms
     [java] 2022-05-28 04:54:47.449 INFO  [main][PortalUpgradeProcess:161] Failed upgrade process com.liferay.portal.upgrade.PortalUpgradeProcess in 9717 ms
     [java] 2022-05-28 04:54:47.449 ERROR [main][DBUpgrader:79] null
     [java] com.liferay.portal.kernel.upgrade.UpgradeException: com.liferay.portal.kernel.upgrade.UpgradeException: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'democratic-republic-of-congo' for key 'IX_19DA007B'
     [java] 	at com.liferay.portal.upgrade.PortalUpgradeProcess.upgrade(PortalUpgradeProcess.java:155) ~[portal-impl.jar:?]
     [java] 	at com.liferay.portal.kernel.upgrade.util.UpgradeProcessUtil._upgradeProcess(UpgradeProcessUtil.java:160) ~[portal-kernel.jar:?]
```

**Review by drewbrokke — APPROVED** [review]
Looks good @pei-jung. Once we solve the CI failures this seems good to go 👍

**Comment by drewbrokke** [comment]
@pei-jung My guess is that the index error happens because of the names colliding between the first couple of SQL statements during upgrade.

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
