### PR TITLE
LPS-139430 As an Administrator, I want to assign a User to Accounts

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-139430](https://issues.liferay.com/browse/LPS-139430).<br/><br/>/cc @pei-jung @alee8888 @ChrisKian @patriciajeanperez @lr-leo @erickmonteiroo

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
ci:test:account

**Comment by drewbrokke** [comment]
@patriciajeanperez I believe that the functional test failure is expected. After the last few changes, the intent is that accounts that are not available to be assigned are simply not present rather than disabled.

**Comment by patriciajeanperez** [comment]
gotcha, @drewbrokke. No other test failures are present.

**Comment by drewbrokke** [comment]
Thanks @patriciajeanperez!

**Review by pei-jung — APPROVED** [review]
LGTM! 👍

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
Thanks for the review, @pei-jung!

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
