### PR TITLE
LPS-169813 The Add Entry button is half hided when there are more entries

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-169813](https://issues.liferay.com/browse/LPS-169813).

@SelenaAungst there were two primary reasons the code was not working:
1. After removing the buttons from `InviteUsersForm`, the `onSubmit` function was no longer being used anywhere. The way to solve this was to assign the function to the `onSubmit` attribute of the `ClayForm`
2. The modal submit button added to `AccountUsersManagementToolbarPropsTransformer` was using the wrong `formId` value. This meant that the [Modal.js code that tries to retrieve and submit the form](https://github.com/drewbrokke/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/liferay/modal/Modal.js?plain=1#L116) (thus triggering the `onSubmit` function from the previous point) would not find the correct one. The solution to this was to instead use the value found in [`InviteUserForm#54`](https://github.com/drewbrokke/liferay-portal/blob/master/modules/apps/account/account-admin-web/src/main/resources/META-INF/resources/account_entries_admin/js/InviteUsersForm.tsx?plain=1#L54)

Please let me know if you have any questions or concerns with what you see here. Thanks!

/cc @pei-jung @ChrisKian @patriciajeanperez @david-truong @gislayne-vitorino

### CODE REVIEW

**Comment by drewbrokke** [comment]
@patriciajeanperez there may be functional test updates required for this one. Would you be willing to double-check that?

**Comment by patriciajeanperez** [comment]
@drewbrokke, yes! I will go and take a look

**Comment by patriciajeanperez** [comment]
ci:test:account

**Comment by drewbrokke** [comment]
Thank you @patriciajeanperez!

**Comment by patriciajeanperez** [comment]
@drewbrokke resent with test fix in https://github.com/liferay-usm/liferay-portal/pull/963

**Pull request closed without merging**
