### PR TITLE
LPS-144061 User with only Update permissions for Account Group is not navigated to the Details page when clicking on its name link


### PR DESCRIPTION
**Pull request by erickmonteiroo**
@drewbrokke @pei-jung

### CODE REVIEW

**Review by drewbrokke — CHANGES_REQUESTED** [review]
@erickmonteiroo here are the action items:

- [ ] Have the rowURL check the VIEW_ACCOUNTS permission instead of UPDATE
- [ ] Add the UPDATE permission check to the `isVisible` method in `AccountGroupDetailsScreenNavigationCategory`

**Comment by erickmonteiroo** [comment]
ci:test:sf

**Comment by erickmonteiroo** [comment]
ci:test:relevant

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
