### PR TITLE
LPS-171281 When accessing Process Builder on the Instance Virtual an error message is displayed

### PR DESCRIPTION
**Pull request by locpham97**
Hi team,
Please help review this PR and leave your comments. Thanks.
Ticket: https://issues.liferay.com/browse/LPS-171281

Note:

We don't define actions with [WorkflowConstants.RESOURCE_NAME](https://github.com/liferay/liferay-portal-ee/blob/master/portal-kernel/src/com/liferay/portal/kernel/workflow/WorkflowConstants.java#L86) or with WorkflowDefinition model so the issue will occur [here](https://github.com/liferay/liferay-portal-ee/blob/master/modules/apps/portal-workflow/portal-workflow-kaleo-runtime-integration-impl/src/main/java/com/liferay/portal/workflow/kaleo/runtime/integration/internal/security/permission/resource/WorkflowPortletResourcePermission.java#L81-L82).
Solution is to update the contains function based on the logic before applying [LPS-167189](https://issues.liferay.com/browse/LPS-167189).
Thanks,
Loc
cc:@tototrinh

### CODE REVIEW

**Comment by drewbrokke** [comment]
FYI @rafaprax would you be willing to give this one a quick check? It seems ok to me but ultimately it's not our component. Or if you prefer, let me know which user to forward to for review. Thanks!

**Comment by rafaprax** [comment]
Hey @drewbrokke, the change seems good to me. Thx

**Comment by drewbrokke** [comment]
Thanks @rafaprax!

**Comment by drewbrokke** [comment]
ci:forward

**Comment by melodywu** [comment]
No related issue found in ci:test:relevant.

**Comment by drewbrokke** [comment]
Thanks @melodywu. If this looks good to you, feel free to forward to Brian. 
FYI @patriciajeanperez

**Comment by patriciajeanperez** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/128548

**Pull request closed without merging**
