### PR TITLE
LPS-157219 User has more access rights than granted via custom role

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-157219](https://issues.liferay.com/browse/LPS-157219).<br/><br/>/cc @pei-jung @ChrisKian @patriciajeanperez @epark18 @david-truong @gislayne-vitorino @RafaelCRC

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:reevaluate:1387401_2633

**Comment by Sharryxue** [comment]
Failure not related.

**Comment by drewbrokke** [comment]
ci:reevaluate:1387401_2633

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@david-truong any other suites you want to run against this one?

**Comment by david-truong** [comment]
I think we are ready to forward

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
