### PR TITLE
LPS-127473 Bridge Commerce's Address with Portal's Address

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-127473](https://issues.liferay.com/browse/LPS-127473).<br/><br/>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

@pei-jung I'm sending this for initial CI tests. I have not had a chance to do any manual or automated testing. I'll "hand this off" to you in case you happen to have some time in the next couple of days to look at any failures, but no pressure. It can wait a couple of days if there are significant time-consuming issues.

Otherwise I'll plan to revisit this when I return on Monday.

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:commerce

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:commerce

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:commerce

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:commerce

**Comment by Sharryxue** [comment]
Related failure found:
1. Failed upgrade process com.liferay.commerce.internal.upgrade.v7_0_0.CommerceAddressUpgradeProcess when upgrading from 7310/740 to master. [Console](https://testray.liferay.com/reports/production/logs/2021-06/test-1-25/test-portal-acceptance-pullrequest(master)/2114/functional-upgrade-tomcat90-mysql57-jdk8/0/6/jenkins-console.txt.gz)
```
     [java] 2021-06-28 17:57:48.273 INFO  [main][UpgradeProcess:111] Upgrading com.liferay.commerce.internal.upgrade.v7_0_0.CommerceAddressUpgradeProcess
     [java] 2021-06-28 17:57:48.293 INFO  [main][UpgradeProcess:126] Failed upgrade process com.liferay.commerce.internal.upgrade.v7_0_0.CommerceAddressUpgradeProcess in 19 ms
     [java] 2021-06-28 17:57:48.297 ERROR [main][UpgradeStepRegistratorTracker:143] Failed upgrade process for module com.liferay.commerce.service
     [java] com.liferay.portal.kernel.upgrade.UpgradeException: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '? set' at line 1
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:120) ~[portal-kernel.jar:?]
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:138) ~[portal-kernel.jar:?]
```
2. Besides the upgrade failure, the failed commerce functional tests seems also related the commits, will double check the issue on local with the bundle.

**Comment by Sharryxue** [comment]
ci:test:bundle

**Comment by drewbrokke** [comment]
@Sharryxue thank you for the detailed report! I will address the failures.

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:commerce

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
See https://github.com/liferay-usm/liferay-portal/pull/122

**Pull request closed without merging**
