### PR TITLE
[TS] LPS-137164

### PR DESCRIPTION
**Pull request by jonathanmccann**
As far as I can see the creating user information (`userId`, `userName`) does not change within the Contact table when the creating user is modified. The only details that change is the user's information who is associated with that contact (`emailAddress`, `firstName`, etc).

If this assumption is incorrect then please let me know so I can pass that information along to the client to better explain why all of the contact models need to be updated when a single user is reindexed.

Please let me know if there are any questions.

### CODE REVIEW

**Review by drewbrokke — COMMENTED** [review]
Hey @jonathanmccann, I think this is the right call. Looking at the old behavior of the `UserIndexer`, only one contact was reindexed when a user was reindexed: [UserIndexer](https://github.com/liferay-usm/liferay-portal/commit/e4906a35a34dcabe26c7cf6397558f76507bf25e#diff-572b122399cfc77a4a5c4516081aa7e7adfce44d9eb377fa8b28690401e652ceL356). This restores that behavior.

Do you think we could add a test case to cover this change?

**Comment by jonathanmccann** [comment]
I'm not sure if we have a way to see if one model was indexed while others were not. It seems more complicated because we can't query the index for changes since the other models don't change despite being reindexed or not. If you know of a way though let me know and I can work on it.

**Comment by drewbrokke** [comment]
@jonathanmccann my initial thought would be to have the test case register a temporary `ModelDocumentContributor` that you can then use to basically peek at each model being reindexed and do assertions. Thoughts?

**Comment by jonathanmccann** [comment]
@drewbrokke Please let me know what you think of https://github.com/liferay-usm/liferay-portal/pull/204/commits/18f68824ab3a97e932743c4a57a154564d2e1205

There seem to be some troubles running integration tests on Master currently but I tested this on 7.3.x and it worked as expected.

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Review by drewbrokke — APPROVED** [review]
LGTM 👍

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
