### PR TITLE
Lps 152963 4

### PR DESCRIPTION
**Pull request by SamZiemer**
Resending from https://github.com/liferay-usm/liferay-portal/pull/811

/cc @drewbrokke

### CODE REVIEW

**Review by drewbrokke — APPROVED** [review]
Looks good, thanks @SamZiemer! Once CI passes/QA validates, we're good to go.

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by melodywu** [comment]
ci:test:upgrade-all:norebase

**Comment by patriciajeanperez** [comment]
Hey @SamZiemer, integration tests relating to search are failing due to assertion errors caused by:

`[beanshell] 2022-11-02 02:57:54.865 ERROR [com.liferay.account.test-executor-thread][SearchPermissionCheckerImpl:159] null
[beanshell] java.lang.ClassCastException: java.util.Collections$UnmodifiableRandomAccessList cannot be cast to java.util.Set
[beanshell] 	at com.liferay.portal.service.impl.RoleLocalServiceImpl.getUserRelatedRoles(RoleLocalServiceImpl.java:1245) ~[portal-impl.jar:?]`

[Here](https://testray.liferay.com/reports/production/logs/2022-11/test-1-32/test-portal-acceptance-pullrequest(master)/6524/modules-integration-mysql57-jdk8/0/0/jenkins-console.txt.gz?authuser=0) is one of the logs. Can you please take a look? Thank you!

**Comment by SamZiemer** [comment]
Hi @drewbrokke, it looks like the failures here are caused because of the change to using SetUtil requested here: https://github.com/liferay-usm/liferay-portal/pull/811#pullrequestreview-1163927251

I am going to change back to using lists and isEmpty to avoid this regression and resend the PR.

**Comment by drewbrokke** [comment]
Hey @SamZiemer I think the issue probably comes from trying to cast the result of the `DSLQuery` calls to a `Set` [like so](https://github.com/liferay-usm/liferay-portal/pull/823/files#diff-0bb5a1b2e49bed884487582f880c6cb5fb54b44acc07b1d7d3e6558d5fe86b48R1245). In that case, we can keep them as lists and use `ListUtil.isNotEmpty` instead, which is essentially the same thing. We should still be able to keep the result collection as a `Set`, right?

**Comment by SamZiemer** [comment]
Hi @drewbrokke, yes that will work. I'll use ListUtil. The resulting set isn't an issue though, that works fine.

**Comment by SamZiemer** [comment]
I've force updated the branch. @Sharryxue I will restart the tests.

**Comment by SamZiemer** [comment]
ci:test:stable

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:test:upgrade-all

**Comment by drewbrokke** [comment]
ci:reevaluate:1307401_5225

**Comment by drewbrokke** [comment]
ci:reevaluate:1307401_5225

**Comment by drewbrokke** [comment]
ci:forward

**Comment by Sharryxue** [comment]
Will manually forward the commits.

**Comment by Sharryxue** [comment]
Manually forwarded. See https://github.com/brianchandotcom/liferay-portal/pull/125857.

**Pull request closed without merging**
