### PR TITLE
LPS-151550 No dropdown when adding Session Property Vocabularies 

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-151550](https://issues.liferay.com/browse/LPS-151550).<br/><br/>/cc @Luizcarlosqueiroz

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by drewbrokke** [comment]
ci:reevaluate:1377401_1670

**Comment by drewbrokke** [comment]
ci:reevaluate:1377401_1670

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by epark18** [comment]
Hello @Luizcarlosqueiroz, all runs of relevant returned this error: [
com.liferay.segments.context.vocabulary.internal.options.provider.test.EntityFieldConfigurationFieldOptionsProviderTest](https://testray.liferay.com/home/-/testray/case_results/1667912695)  | [Error Logs](https://testray.liferay.com/reports/production/logs/2022-04/test-1-36/test-portal-acceptance-pullrequest(master)/952/modules-integration-mysql57-jdk8/0/2/jenkins-console.txt.gz?authuser=0)
`     [exec] com.liferay.segments.context.vocabulary.internal.options.provider.test.AssetVocabularyConfigurationOptionsProviderTest > testGetOption FAILED
     [exec]     java.lang.IllegalStateException: Timed out while waiting for service com.liferay.configuration.admin.definition.ConfigurationFieldOptionsProvider (&(configuration.pid=com.liferay.segments.context.vocabulary.internal.configuration.SegmentsContextVocabularyConfiguration)(configuration.field.name=assetVocabulary))
     [exec]     	at com.liferay.portal.test.rule.InjectTestBag._getServiceReference(InjectTestBag.java:199)`

Tests affected:

1. testGetOption
2. testGetOptionsWithDoubleEntityField
3. testGetOptionsWithStringEntityField

Would you be able to take a look? Thank you!

**Comment by drewbrokke** [comment]
@epark18 just pushed a fix for the test cases.

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by epark18** [comment]
ci:test:tango

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:reevaluate:1357401_1327

**Comment by drewbrokke** [comment]
Got it, thank you @YurenaC!

**Pull request closed without merging**
