### PR TITLE
LPS-149635 Login modal interface adjustments

### PR DESCRIPTION
**Pull request by pei-jung**
See screenshots for the updated UI:
Screen Shot 2022-04-13 at 7 13 31 PM

Screen Shot 2022-04-13 at 7 14 01 PM

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by melodywu** [comment]
Failures are not related to the commits here.

**Comment by epark18** [comment]
Going to take a second look and test this one locally since [OpenIDConnect#OpenIDConnectSmokeWithOkta](https://testray.liferay.com/home/-/testray/case_results/1666894911) failed twice. [Error Logs](https://testray.liferay.com/reports/production/logs/2022-04/test-1-37/test-portal-acceptance-pullrequest(master)/1660/functional-tomcat90-mysql57-jdk8/0/12/jenkins-console.txt.gz?authuser=0) | [Poshi Report](https://testray.liferay.com/reports/production/logs/2022-04/test-1-37/test-portal-acceptance-pullrequest(master)/1660/functional-tomcat90-mysql57-jdk8/0/12/LocalFile.OpenIDConnect_OpenIDConnectSmokeWithOkta/index.html.gz?authuser=0)

image

**Review by drewbrokke — APPROVED** [review]

**Comment by epark18** [comment]
[[OpenIDConnect#OpenIDConnectSmokeWithOkta](https://testray.liferay.com/home/-/testray/case_results/1666894911)](https://testray.liferay.com/home/-/testray/case_results/1666894911) looks like an existing flaky issue. No other failures.

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
ci:reevaluate:1337401_1660

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
