### PR TITLE
LRQA-73563 Formatting issues in source-format-jdk8/0/0


### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by epark18** [comment]
Failures are unrelated :]

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
ci:stop

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:forward

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
The change has already been merged into upstream.

**Pull request closed without merging**
