### PR TITLE
LPS-170345 Semantic Search System/Instance Settings doesn't render custom form after saving

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-170345](https://issues.liferay.com/browse/LPS-170345).<br/><br/>/cc @pei-jung @ChrisKian @patriciajeanperez @david-truong @gislayne-vitorino

FYI @thektan

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by melodywu** [comment]
No related issue found in ci:test:relevant.

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
