### PR TITLE
LPS-162687 Remove AccountEntry name shortening and test cases if present

### PR DESCRIPTION
**Pull request by RafaelCRC**
update for [LPS-162687](https://issues.liferay.com/browse/LPS-162687)

### CODE REVIEW

**Comment by RafaelCRC** [comment]
ci:stop

**Comment by RafaelCRC** [comment]
ci:test:sf

**Comment by RafaelCRC** [comment]
ci:test:relevant

**Review by gislayne-vitorino — APPROVED** [review]
LGTM!

**Review by drewbrokke — CHANGES_REQUESTED** [review]
@RafaelCRC Let's leave the changes to `portal-kernel` out of this one.

**Comment by RafaelCRC** [comment]
Removed the commit, should be good to go now @drewbrokke

**Comment by RafaelCRC** [comment]
ci:test:sf
ci:test:relevant

**Comment by RafaelCRC** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
Failure not related to the changes.

**Review by drewbrokke — APPROVED** [review]
@patriciajeanperez we're good to go on this one.

**Comment by Sharryxue** [comment]
Manually forward to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/123807

**Comment by Sharryxue** [comment]
ci:close

**Pull request closed without merging**
