### PR TITLE
LPS-165575 Cannot add website to Users and Organizations

### PR DESCRIPTION
**Pull request by gislayne-vitorino**
This is an update for: [LPS-165575](https://issues.liferay.com/browse/LPS-165575)

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
Hi @gislayne-vitorino, should we also look at users-admin-web?

**Comment by gislayne-vitorino** [comment]
Yes, it needs. Thanks for looking at it @patriciajeanperez , i'm going to send the updates

**Comment by gislayne-vitorino** [comment]
ci:stop

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
ci:test:relevant

**Review by RafaelCRC — APPROVED** [review]
LGTM!

**Comment by brianchandotcom** [comment]
@gislayne-vitorino @RafaelCRC merged to master and the temp branch.

**Comment by Sharryxue** [comment]
Closed the PR since the commits merged.

**Comment by Sharryxue** [comment]
ci:close

**Pull request closed without merging**
