### PR TITLE
LPS-117666 my-user-account service does not return inherited regular roles

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-117666](https://issues.liferay.com/browse/LPS-117666).

@istvansajtos will you please look over my changes and let me know if they work for you, that they meet the requirements, and whether or not you have any concerns. Thanks!

@pei-jung would you be willing to give these changes a look as well?

/cc @ChrisKian @patriciajeanperez @david-truong @gislayne-vitorino

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:reevaluate:1327401_8087

**Comment by istvansajtos** [comment]
Thanks @drewbrokke , your changes look great and work well based on my tests!

**Review by pei-jung — APPROVED** [review]
LGTM!

**Comment by drewbrokke** [comment]
@patriciajeanperez if this one looks good to you, we can manually forward.

**Comment by patriciajeanperez** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/129648

**Pull request closed without merging**
