### PR TITLE
LPS-145365 As a Guest User on a custom Site, I'd like to create a User Account to be able to use the website

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by pei-jung** [comment]
Forced push branch to fix the semantic version.

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
Hi @topolik,

We're modifying the user API to allow guest users to create their user account. This API requires authentication by default. However, customers can choose to grant access to this API without authentication by modifying the Service Access Policy as stated in this [tutorial](https://learn.liferay.com/dxp/latest/en/headless-delivery/consuming-apis/making-unauthenticated-requests.html). 

Do you see any security vulnerabilities with this approach that we might have overlooked? Thanks!

**Review by drewbrokke — APPROVED** [review]
Looks good @pei-jung. Once we get approval from Tomas I think we're good to go.

**Comment by patriciajeanperez** [comment]
Hi @pei-jung, can you please take a look at the failure in [UserAccountResourceTest.testPostUserAccountAsGuest?](https://testray.liferay.com/reports/production/logs/2022-02/test-1-29/test-portal-acceptance-pullrequest(master)/1569/modules-integration-mysql57-jdk8/0/1/jenkins-console.txt.gz)

`java.lang.IllegalArgumentException: Expected starts with '{', but found '<' in '<Forbidden xmlns=""></Forbidden>'`

Thank you!

**Comment by pei-jung** [comment]
see https://github.com/liferay-usm/liferay-portal/pull/441

**Pull request closed without merging**
