### PR TITLE
LPS-162464 Use the country's name value instead of the key in Users and Orgs admin

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-162464](https://issues.liferay.com/browse/LPS-162464).

FYI @Vy-CES

/cc @pei-jung @ChrisKian @patriciajeanperez @epark18 @david-truong @gislayne-vitorino @RafaelCRC

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
@patriciajeanperez this one is good to forward.

**Comment by Sharryxue** [comment]
Will manually forward the pr.

**Comment by Sharryxue** [comment]
ci:close

**Pull request closed without merging**
