### PR TITLE
LPS-130073 Source Formatting: Normalize configuration name lang keys

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-130073](https://issues.liferay.com/browse/LPS-130073).<br/><br/>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by Sharryxue** [comment]
No specific issue found in ci:test:relevant and ci:test:sf, the sf issue not fixed on upstream yet.

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
New SF failure seems not related, it's caused by [commit](https://github.com/liferay/liferay-portal/commit/6531f975f89eb99e153ee7c64bbf5d0913f726ec), not fixed on upstream yet.

**Comment by Sharryxue** [comment]
New SF failuresnot related, were introduced by [commit a](https://github.com/liferay/liferay-portal/commit/2a7f49331c322cf9d6dd22d1b700f0a3ecb6acc7) and [commit b](https://github.com/liferay/liferay-portal/commit/78b20a75b0638817452c36d4a265a560bd3df3c0).

**Comment by Sharryxue** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
For the SF issues.
_DataRemovalTest.java_ need updating the file using HashMapDictionaryBuilder instead.
_site_settings/details.jsp_ failed due to the setParameter lines not in alphabetical order.
Hello @drewbrokke, not sure if it's better to ping the file authur or we can fix it here.
/cc @hhuijser

**Comment by drewbrokke** [comment]
@Sharryxue I'm ok to just fix it inline with this change.

**Comment by Sharryxue** [comment]
Thanks @drewbrokke, I'd tried to fix the SF failures and send in [liferay-usm/liferay-portal#24](https://github.com/liferay-usm/liferay-portal/pull/24), would you please take a review when you get a chance? Thanks in advance.

**Pull request closed without merging**
