### PR TITLE
[TS] LPS-136376

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-136376

Discussed in PTR-2569 to be the correct approach.  Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by Sharryxue** [comment]
No related failure found in ci:test:relevant .

**Comment by drewbrokke** [comment]
@patriciajeanperez would you be willing to manually forward this one for us?

**Comment by patriciajeanperez** [comment]
Manually forwarded to https://github.com/brianchandotcom/liferay-portal/pull/105018

**Comment by patriciajeanperez** [comment]
ci:close

**Pull request closed without merging**
