### PR TITLE
LPS-168022 Remove redundant usages of the method getSearchActionURL from the app trash

### PR DESCRIPTION
**Pull request by gislayne-vitorino**
This is an update for [subtask: LPS-168022](https://issues.liferay.com/browse/LPS-168022), [LPS-161233](https://issues.liferay.com/browse/LPS-161233)

### CODE REVIEW

**Comment by melodywu** [comment]
No related issue found in ci:test:relevant.

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:test:stable

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
