### PR TITLE
LPS-158863 Trigger ServicePreAction when User's password changed.

### PR DESCRIPTION
**Pull request by hongvo2308**
Dear team,
This PR is to fix an issue related to User management as described in https://issues.liferay.com/browse/LPS-158863
please review it and leave your comment.

The solution for this one is that if the Admin changes the password, the request will activate the ServicePreAction to initiate the ThemeDisplay. Therefore, I add this step.

Thank you

### CODE REVIEW

**Comment by hongvo2308** [comment]
The previous PR was at https://github.com/liferay-core-infra/liferay-portal/pull/1967.
Thank you.

**Comment by Sharryxue** [comment]
No related issue found [in ci:test:relevant](https://github.com/liferay-usm/liferay-portal/pull/805#issuecomment-1291563470).

**Comment by patriciajeanperez** [comment]
ci:test:security

**Comment by patriciajeanperez** [comment]
ci:test:usm

**Review by drewbrokke — COMMENTED** [review]
@hongvo2308 thank you for sending this change. This seems ok to me, but ultimately this needs to go through the @liferay-appsec team. Please send this pull request to https://github.com/liferay-appsec/liferay-portal. Thank you!

**Comment by hongvo2308** [comment]
@drewbrokke 
Yes, I have forwarded this to https://github.com/liferay-appsec/liferay-portal/pull/883.
Thank you.

**Pull request closed without merging**
