### PR TITLE
LPS-151908 As a developer using headless endpoints, I'd like to create a country and know which fields are required

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-151908](https://issues.liferay.com/browse/LPS-151908).<br/><br/>/cc @pei-jung @erickmonteiroo @ChrisKian @patriciajeanperez @epark18 @david-truong

### CODE REVIEW

**Review by pei-jung — APPROVED** [review]
LGTM!  👍

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
ci:reevaluate:1287401_2972

**Comment by drewbrokke** [comment]
Closing to fix semantic failures.

**Comment by drewbrokke** [comment]
See https://github.com/liferay-usm/liferay-portal/pull/546

**Pull request closed without merging**
