### PR TITLE
[TS] LPS-168314

### PR DESCRIPTION
**Pull request by crodriguezy**

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:account

**Comment by melodywu** [comment]
ci:test:account

**Comment by melodywu** [comment]
ci:test:bundle

**Comment by crodriguezy** [comment]
Hello team, any update? Thanks! :)

**Comment by melodywu** [comment]
No related issue found in ci:test:relevant and ci:test:account.

**Review by drewbrokke — APPROVED** [review]
Looks good, thanks @crodriguezy!

**Comment by drewbrokke** [comment]
ci:forward

**Comment by melodywu** [comment]
No related issue found in ci:test:relevant.

**Comment by crodriguezy** [comment]
Hi team, according to @melodywu and @drewbrokke' comments could this please be merged then? There is a LXC customer waiting for it.
Thank you

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
