### PR TITLE
LPS-153684 Regions do not get translated or ordered properly when changing display language

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:reevaluate:1357401_1620

**Comment by pei-jung** [comment]
@epark18 are these failures related?

**Comment by epark18** [comment]
@pei-jung This looks good to me!

**Comment by epark18** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
No related failure found.

**Pull request closed without merging**
