### PR TITLE
LPS-163009 Add user registration page for new account users to sign up

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by pei-jung** [comment]
@patriciajeanperez the failure looks unrelated. Can we re-run the test or manually forward?

**Comment by patriciajeanperez** [comment]
@pei-jung Hi Pei! I can manually forward but will run more Accounts tests to make sure. Thanks!

**Comment by patriciajeanperez** [comment]
ci:test:account

**Comment by patriciajeanperez** [comment]
@pei-jung can you take a look at this? Thank you!

```
com.liferay.portlet.title.localization.test.PortletTitleTest > testPortletTitles FAILED
     [exec]     java.lang.AssertionError: Please update the Language.properties files for the following portlets: [com_liferay_account_admin_web_internal_portlet_AccountUsersRegistrationPortlet]
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
```

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:forward

**Pull request closed without merging**
