### PR TITLE
LPS-141342 The permissions can not be displayed correctly after adding a folder with specific permissions

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-141342](https://issues.liferay.com/browse/LPS-141342).<br/><br/>/cc @pei-jung @alee8888 @ChrisKian @patriciajeanperez @lr-leo @erickmonteiroo

### CODE REVIEW

**Review by pei-jung — APPROVED** [review]
LGTM 👍

**Comment by drewbrokke** [comment]
ci:reevaluate:1277401_775

**Comment by drewbrokke** [comment]
ci:reevaluate:1277401_775

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
@patriciajeanperez are the failures related to the changes in this PR?

**Comment by jpince** [comment]
forwarded to Brian Chan: https://github.com/brianchandotcom/liferay-portal/pull/109719

**Comment by jpince** [comment]
ci:close

**Pull request closed without merging**
