### PR TITLE
LPS-155961 Account Address as system object

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-155961](https://issues.liferay.com/browse/LPS-155961).<br/><br/>/cc @pei-jung @ChrisKian @patriciajeanperez @epark18 @david-truong @gislayne-vitorino @RafaelCRC @victorcdp

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
No related failure found.

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
