### PR TITLE
[TS] LPS-131467

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@jonathanmccann in a case like this when the key is already translated and the key does not change, it's best if we manually copy the keys among the properties files instead of relying on `buildLang`. Otherwise we lose translation work. 

This is the script I use for this situation: https://gist.github.com/drewbrokke/5252c81c725fc3cf518defd2766171ca

I'm gonna close this one for now, please resend. Thanks!

**Comment by jonathanmccann** [comment]
Thank you for the script, it worked great.

**Comment by drewbrokke** [comment]
You're welcome!

**Pull request closed without merging**
