### PR TITLE
LPS-143802 Create GET UserGroup by ExternalReferenceCode for User Group Headless API

### PR DESCRIPTION
**Pull request by erickmonteiroo**
@drewbrokke @pei-jung

### CODE REVIEW

**Comment by epark18** [comment]
@erickmonteiroo Hello! Looks like there's two unique failures to take a closer look at. One is a rest/service builder failure so it needs a regen [Error Logs](https://testray.liferay.com/reports/production/logs/2022-01/test-1-29/test-portal-acceptance-pullrequest(master)/1398/rest-builder-jdk8/0/0/jenkins-console.txt.gz) `     [echo] diff --git a/modules/apps/headless/headless-admin-user/headless-admin-user-impl/src/main/java/com/liferay/headless/admin/user/internal/graphql/query/v1_0/Query.java b/modules/apps/headless/headless-admin-user/headless-admin-user-impl/src/main/java/com/liferay/headless/admin/user/internal/graphql/query/v1_0/Query.java
     [echo] index cf4717c44014..6f6edc442ac6 100644
     [echo] --- a/modules/apps/headless/headless-admin-user/headless-admin-user-impl/src/main/java/com/liferay/headless/admin/user/internal/graphql/query/v1_0/Query.java
     [echo] +++ b/modules/apps/headless/headless-admin-user/headless-admin-user-impl/src/main/java/com/liferay/headless/admin/user/internal/graphql/query/v1_0/Query.java
     [echo] @@ -1009,6 +1009,24 @@ public class Query {
     [echo]  				userAccountId));
     [echo]  	}
     [echo]  
     [echo] +	/**
     [echo] +	 * Invoke this method with the command line:
     [echo] +	 *
     [echo] +	 * curl -H 'Content-Type: text/plain; charset=utf-8' -X 'POST' 'http://localhost:8080/o/graphql' -d $'{"query": "query {userGroupByExternalReferenceCode(externalReferenceCode: ___){actions, description, externalReferenceCode, id, name, usersCount}}"}' -u 'test@liferay.com:test'
     [echo] +	 */
     [echo] +	@GraphQLField
     [echo] +	public UserGroup userGroupByExternalReferenceCode(
     [echo] +			@GraphQLName("externalReferenceCode") String externalReferenceCode)
     [echo] +		throws Exception {
     [echo] +
     [echo] +		return _applyComponentServiceObjects(
     [echo] +			_userGroupResourceComponentServiceObjects,
     [echo] +			this::_populateResourceContext,
     [echo] +			userGroupResource ->
     [echo] +				userGroupResource.getUserGroupByExternalReferenceCode(
     [echo] +					externalReferenceCode));
     [echo] +	}
     [echo] +
     [echo]  	/**
     [echo]  	 * Invoke this method with the command line:
     [echo]  	 *
     [echo] @@ -1127,6 +1145,29 @@ public class Query {
     [echo]  
     [echo]  	}
     [echo]  
     [echo] +	@GraphQLTypeExtension(Account.class)
     [echo] +	public class GetUserGroupByExternalReferenceCodeTypeExtension {
     [echo] +
     [echo] +		public GetUserGroupByExternalReferenceCodeTypeExtension(
     [echo] +			Account account) {
     [echo] +
     [echo] +			_account = account;
     [echo] +		}
     [echo] +
     [echo] +		@GraphQLField
     [echo] +		public UserGroup userGroupByExternalReferenceCode() throws Exception {
     [echo] +			return _applyComponentServiceObjects(
     [echo] +				_userGroupResourceComponentServiceObjects,
     [echo] +				Query.this::_populateResourceContext,
     [echo] +				userGroupResource ->
     [echo] +					userGroupResource.getUserGroupByExternalReferenceCode(
     [echo] +						_account.getExternalReferenceCode()));
     [echo] +		}
     [echo] +
     [echo] +		private Account _account;
     [echo] +
     [echo] +	}
     [echo] +
     [echo]  	@GraphQLTypeExtension(Account.class)
     [echo]  	public class GetAccountAccountRolesPageTypeExtension {`

The other is an IllegalArgumentException that is causing a lot of tests to fail. Here is one example [Case Results](https://testray.liferay.com/home/-/testray/case_results/1601716293) [Error Logs](https://testray.liferay.com/reports/production/logs/2022-01/test-1-29/test-portal-acceptance-pullrequest(master)/1398/modules-integration-mysql57-jdk8/0/1/jenkins-console.txt.gz) `     [exec] com.liferay.headless.admin.user.resource.v1_0.test.UserGroupResourceTest > testGraphQLGetUserGroupByExternalReferenceCode FAILED
     [exec]     java.lang.IllegalArgumentException: Expected starts with '{', but found 'n' in 'null'
     [exec]     	at com.liferay.headless.admin.user.client.json.BaseJSONParser._assertStartsWithAndEndsWith(BaseJSONParser.java:259)`

**Comment by erickmonteiroo** [comment]
ci:test:sf

**Comment by erickmonteiroo** [comment]
ci:test:relevant

**Comment by erickmonteiroo** [comment]
ci:test:relevant

**Pull request closed without merging**
