### PR TITLE
LPS-163826 Inconsistent display name in country

### PR DESCRIPTION
**Pull request by RafaelCRC**
update for [LPS-163826](https://issues.liferay.com/browse/LPS-163826)

### CODE REVIEW

**Review by gislayne-vitorino — APPROVED** [review]
LGTM

**Review by drewbrokke — CHANGES_REQUESTED** [review]
@RafaelCRC let's leave the `portal-kernel` changes out of this pull as well.

**Comment by RafaelCRC** [comment]
Done! @drewbrokke

**Comment by RafaelCRC** [comment]
ci:test:sf
ci:test:relevant

**Comment by RafaelCRC** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
No related issue found in ci:test:relevant.

**Review by drewbrokke — APPROVED** [review]
@patriciajeanperez we're good to go on this one as well.

**Comment by patriciajeanperez** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/123774

**Pull request closed without merging**
