### PR TITLE
LPS-157443

### PR DESCRIPTION
**Pull request by SelenaAungst**
This is an update for [LPS-157443](https://issues.liferay.com/browse/LPS-157443) with my changes added to the contents of [this PR](https://github.com/liferay-usm/liferay-portal/pull/652).

@drewbrokke Please let me know if I am missing anything!

### CODE REVIEW

**Review by drewbrokke — CHANGES_REQUESTED** [review]
@SelenaAungst the changes look good, but in this case I think it's best to squash your changes into a single commit.

**Comment by SelenaAungst** [comment]
ci:test:sf

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:reevaluate:1357401_2079

**Review by drewbrokke — APPROVED** [review]

**Comment by epark18** [comment]
This PR passed all checks here https://github.com/epark18/liferay-portal/pull/34. Looks good on my end.

**Review by drewbrokke — APPROVED** [review]
LGTM 👍

**Comment by drewbrokke** [comment]
@epark18 this one looks good to go on my end 👍

**Comment by epark18** [comment]
Pushed to Brian. https://github.com/brianchandotcom/liferay-portal/pull/120711.

**Comment by epark18** [comment]
ci:close

**Pull request closed without merging**
