### PR TITLE
LPS-131639 Rename variables in CSSClassNames

### PR DESCRIPTION
**Pull request by erickmonteiroo**

### CODE REVIEW

**Review by drewbrokke — CHANGES_REQUESTED** [review]
@erickmonteiroo the changes look good. 

I think in the spirit of this changes, we should also just rename the whole class to `CSSClassesUtil`. I think it's appropriate because typically `*Util` classes are made up of static methods anyways.

**Comment by erickmonteiroo** [comment]
ci:test:sf

**Comment by erickmonteiroo** [comment]
ci:test:relevant

**Review by drewbrokke — COMMENTED** [review]
Looks good @erickmonteiroo!

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
