### PR TITLE
Commerce 6843 migrate account rest to admin-user headless

### PR DESCRIPTION
**Pull request by luca-pellizzon**
@drewbrokke  this is the PR about the account migration

cc @riccardo-alberti

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@luca-pellizzon looks like a semver issue. Go ahead and run baseline and push your changes here.

**Comment by drewbrokke** [comment]
@patriciajeanperez is the smoke test failure related?

**Comment by luca-pellizzon** [comment]
@drewbrokke added baseline run, but again conflicts because Brian is setting up the branch for the release

**Comment by patriciajeanperez** [comment]
hey @drewbrokke, smoke test failure for upgrades is not related

**Comment by drewbrokke** [comment]
ci:test:relevant

**Review by drewbrokke — COMMENTED** [review]
@luca-pellizzon so far this looks good. Thank you for committing the changes systematically :) I'll do a second review on Monday to be sure, but assuming CI passes this seems ready.

**Comment by drewbrokke** [comment]
@pei-jung I requested a review from you as well. With a change this large, I'd appreciate another person's review besides mine. Thanks!

**Review by pei-jung — APPROVED** [review]
LGTM! 👍

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
Resent here: https://github.com/liferay-usm/liferay-portal/pull/179

**Pull request closed without merging**
