### PR TITLE
[TS] LPS-169258

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-169258

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by Sharryxue** [comment]
No related issue found in [ci:test:relevant](https://github.com/liferay-usm/liferay-portal/pull/876#issuecomment-1323031799).

**Review by drewbrokke — APPROVED** [review]
LGTM 👍 Thanks @ChrisKian!

**Comment by drewbrokke** [comment]
ci:forward

**Comment by Sharryxue** [comment]
Manually forwarded to BChan. Refer https://github.com/brianchandotcom/liferay-portal/pull/126781.

**Comment by Sharryxue** [comment]
ci:close

**Pull request closed without merging**
