### PR TITLE
LPS-133728 Remove Account_ table and service

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-133728](https://issues.liferay.com/browse/LPS-133728).<br/><br/>/cc @pei-jung @alee8888 @ChrisKian @patriciajeanperez

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
@patriciajeanperez is this a real failure?

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:upgrade

**Comment by Sharryxue** [comment]
Related issue found
- Oracle specific issues found in [UpgradeOracleTest](https://testray.liferay.com/home/-/testray/case_results/1546260311), refer [console](https://testray.liferay.com/reports/production/logs/2021-07/test-1-25/test-portal-acceptance-pullrequest(master)/2730/modules-integration-oracle193-jdk8/0/1/jenkins-console.txt.gz), hello @drewbrokke , would you please double check the issue? Thanks 
```
     [exec]     Caused by: Error : 942, Position : 0, Sql = alter table ACCOUNT_ modify INDUSTRY varchar2(300 BYTE), OriginalSql = alter table ACCOUNT_ modify INDUSTRY varchar2(300 BYTE), Error Msg = ORA-00942: table or view does not exist
     [exec] 
     [exec]     	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:513)
     [exec]     	... 50 more
     [exec] 
     [exec]     java.sql.SQLSyntaxErrorException: ORA-00942: table or view does not exist
```

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:upgrade

**Comment by Sharryxue** [comment]
ci:test:bundle

**Comment by Sharryxue** [comment]
No specific issue found in latest ci:test:relevant and ci:test:upgrade suites, hello @drewbrokke, just wanna confirm would this be ready for manually forward?

**Comment by drewbrokke** [comment]
@Sharryxue thank you for confirming. I will actually be making updates to the upgrade process, so I will push and re-run the suites myself. Thank you!

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:upgrade

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:upgrade

**Comment by drewbrokke** [comment]
Rebased and resent here: https://github.com/liferay-usm/liferay-portal/pull/145

**Comment by drewbrokke** [comment]
ci:stop

**Pull request closed without merging**
