### PR TITLE
LPS-143045 Create DELETE UserGroup for User Group Headless API

### PR DESCRIPTION
**Pull request by erickmonteiroo**
Rebased on [LPS-143044](https://issues.liferay.com/browse/LPS-143044)

### CODE REVIEW

**Comment by erickmonteiroo** [comment]
ci:test:sf

**Comment by erickmonteiroo** [comment]
ci:test:relevant

**Comment by erickmonteiroo** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:relevant

**Review by drewbrokke — CHANGES_REQUESTED** [review]
@erickmonteiroo you'll need to implement `testDeleteUserGroup_addUserGroup` in the test case. Other than that this looks good to go.

**Comment by drewbrokke** [comment]
Looks like there may be a semver failure as well. Try rebasing and re-running gw baseline in the API module

**Comment by erickmonteiroo** [comment]
ci:test:sf

**Comment by erickmonteiroo** [comment]
ci:test:relevant

**Review by drewbrokke — APPROVED** [review]
ci:forward

**Comment by erickmonteiroo** [comment]
ci:forward

**Pull request closed without merging**
