### PR TITLE
LPS-162652 Rename remaining method names

### PR DESCRIPTION
**Pull request by gislayne-vitorino**
This is an update for [LPS-155969](https://issues.liferay.com/browse/LPS-155969), sub-task: [LPS-162652](https://issues.liferay.com/browse/LPS-162652).

### CODE REVIEW

**Review by RafaelCRC — APPROVED** [review]
LGTM! :+1: 
Just check for any related failures in CI when its done!

**Comment by drewbrokke** [comment]
ci:reevaluate:1327401_5699

**Comment by patriciajeanperez** [comment]
No regressions found

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
@patriciajeanperez we're GTG on this one.

**Comment by patriciajeanperez** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/123126

**Pull request closed without merging**
