### PR TITLE
LPS-153991 As a developer using auto-generated configuration interfaces, I want to display translations from language keys as the default values of a LocalizedValueMap

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-153991](https://issues.liferay.com/browse/LPS-153991).<br/><br/>/cc @pei-jung @erickmonteiroo @ChrisKian @patriciajeanperez @epark18 @david-truong

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:reevaluate:1347401_1898

**Comment by drewbrokke** [comment]
ci:reevaluate:1347401_1898

**Review by pei-jung — APPROVED** [review]
LGTM! 👍

**Comment by pei-jung** [comment]
ci:forward

**Comment by drewbrokke** [comment]
ci:reevaluate:1297401_3024

**Comment by drewbrokke** [comment]
ci:reevaluate:1297401_3024

**Comment by Sharryxue** [comment]
No related failure found.

**Comment by pei-jung** [comment]
@epark18 can we manually forward this to Brian?

**Comment by pei-jung** [comment]
Thanks @epark18!

**Pull request closed without merging**
