### PR TITLE
LPS-178826 Update User_ table to support user types

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:upgrade

**Comment by pei-jung** [comment]
Hi @patriciajeanperez, are the failures related?

**Comment by patriciajeanperez** [comment]
ci:test:upgrade

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:forward:force

**Comment by pei-jung** [comment]
Manually forwarded to https://github.com/liferay-usm/liferay-portal/pull/1034.

**Pull request closed without merging**
