### PR TITLE
LPS-155553 Allow custom styling for Account Modals

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:account

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
ci:reevaluate:1267401_3389

**Comment by drewbrokke** [comment]
ci:reevaluate:1267401_3390

**Comment by drewbrokke** [comment]
@epark18 are these failures related?

**Comment by drewbrokke** [comment]
@epark18 Looks good to me, thanks!

**Comment by epark18** [comment]
Pushed to Brian. https://github.com/brianchandotcom/liferay-portal/pull/118617

**Comment by epark18** [comment]
ci:close

**Pull request closed without merging**
