### PR TITLE
LPS-103437 The number field should be validated in System Settings

### PR DESCRIPTION
**Pull request by alee8888**
@drewbrokke @pei-jung 

https://issues.liferay.com/browse/LPS-103437

### CODE REVIEW

**Comment by epark18** [comment]
Good morning @alee8888! The failure in relevant looks related to your [commit](https://github.com/liferay-usm/liferay-portal/pull/334/commits/f946105fc3bde9a691e3cb35e8c65757b7bdfe0c) here and is showing an Assertion Error. [Error Logs](https://testray.liferay.com/reports/production/logs/2021-11/test-1-20/test-portal-acceptance-pullrequest(master)/9506/modules-unit-jdk8/0/0/jenkins-console.txt.gz)

`     [exec] com.liferay.configuration.admin.web.internal.util.ConfigurationModelToDDMFormConverterTest > testGetWithIntegerField FAILED
     [exec]     org.junit.ComparisonFailure: expected:<[text]> but was:<[numeric]>
     [exec]         at org.junit.Assert.assertEquals(Assert.java:115)
     [exec]         at org.junit.Assert.assertEquals(Assert.java:144)`

**Comment by alee8888** [comment]
@epark18 Thank you Eric!

**Comment by alee8888** [comment]
ci:test:sf

**Comment by alee8888** [comment]
ci:test:relevant

**Comment by alee8888** [comment]
ci:test:sf

**Comment by epark18** [comment]
ci:reevaluate:1057401_8269

**Comment by epark18** [comment]
ci:test:relevant

**Review by drewbrokke — APPROVED** [review]
LGTM 👍

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
