### PR TITLE
LPS-161774 Modified patterns-description language key description.

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
FWD: https://github.com/fortunatomaldonado/liferay-portal/pull/46

Let me know if there are any questions or comments about this.
Thank you!

> [LPS-161774](https://issues.liferay.com/browse/LPS-161774) Modified patterns-description language key description.

### CODE REVIEW

**Review by gislayne-vitorino — COMMENTED** [review]
This is looking good to me, but apparently it needs a version bump in order to fix the semantic versioning, @fortunatomaldonado, @SelenaAungst check [here](https://github.com/liferay-usm/liferay-portal/pull/752#issuecomment-1255555550) . Thoughts about it @drewbrokke?

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
ci:reevaluate:1377401_5197

**Comment by drewbrokke** [comment]
This change should not require any version changes, my guess is that it's an issue in upstream.

**Comment by drewbrokke** [comment]
@patriciajeanperez we're good to go here 👍

**Comment by drewbrokke** [comment]
ci:forward

**Comment by patriciajeanperez** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/124057

**Pull request closed without merging**
