### PR TITLE
LPS-133728 Remove Account_ table and service

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-133728](https://issues.liferay.com/browse/LPS-133728).<br/><br/>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
Seems related failure found in the ci:test:relevant test suite, hello @drewbrokke would you please doubel check? refer [console ](https://testray.liferay.com/reports/production/logs/2021-07/test-1-18/test-portal-acceptance-pullrequest(master)/6062/unit-jdk8/0/0/jenkins-console.txt.gz), thanks.
```
    [junit] Could not build http://localhost:8080/Portal_AccountService?wsdl
    [junit] 	at org.apache.axis.tools.ant.wsdl.Wsdl2javaAntTask.execute(Wsdl2javaAntTask.java:288)
    [junit] 	at com.liferay.util.ant.Wsdl2JavaTask.generateJava(Wsdl2JavaTask.java:51)
    [junit] 	at com.liferay.portal.tools.PortalClientBuilder.<init>(PortalClientBuilder.java:101)
    [junit] 	at com.liferay.portal.tools.PortalClientBuilder.main(PortalClientBuilder.java:63)
    [junit] 	at com.liferay.portal.tools.PortalClientBuilderTest.testPortalClientBuilder(PortalClientBuilderTest.java:49)
    [junit] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [junit] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    [junit] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [junit] 	at java.lang.reflect.Method.invoke(Method.java:498)
    [junit] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
    [junit] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    [junit] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
    [junit] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    [junit] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
    [junit] 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
    [junit] 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
    [junit] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
    [junit] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
    [junit] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
    [junit] 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
    [junit] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
    [junit] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
    [junit] 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
    [junit] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
    [junit] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    [junit] 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    [junit] 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
    [junit] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
    [junit] 	at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:50)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:532)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:1179)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:1030)
    [junit] Caused by: org.xml.sax.SAXParseException; systemId: http://localhost:8080/Portal_AccountService?wsdl; lineNumber: 380; columnNumber: 3; The element type "br" must be terminated by the matching end-tag "</br>".
    [junit] 	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
    [junit] 	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
    [junit] 	at org.apache.axis.utils.XMLUtils.newDocument(XMLUtils.java:369)
    [junit] 	at org.apache.axis.utils.XMLUtils.newDocument(XMLUtils.java:420)
    [junit] 	at org.apache.axis.wsdl.symbolTable.SymbolTable.populate(SymbolTable.java:482)
    [junit] 	at org.apache.axis.wsdl.gen.Parser$WSDLRunnable.run(Parser.java:361)
    [junit] 	at java.lang.Thread.run(Thread.java:745)
```
In addition, there is an failure on upstream related COMMERCEADDRESS with following errors on console, not sure if it was introduced by commits in [liferay-usm/liferay-portal#122](https://github.com/liferay-usm/liferay-portal/pull/122), refer [console](https://testray.liferay.com/reports/production/logs/2021-07/test-1-18/test-portal-acceptance-pullrequest(master)/6062/modules-unit-jdk8/0/0/jenkins-console.txt.gz), issue is addressed in [LRQA-68428]( https://issues.liferay.com/browse/LRQA-68428)
```
     [exec] com.liferay.portal.tools.sample.sql.builder.SampleSQLBuilderTest > testGenerateAndInsertSampleSQL FAILED
     [exec]     java.sql.SQLSyntaxErrorException: user lacks privilege or object not found: COMMERCEADDRESS
     [exec]         at org.hsqldb.jdbc.JDBCUtil.sqlException(JDBCUtil.java:376)
     [exec]         at org.hsqldb.jdbc.JDBCUtil.sqlException(JDBCUtil.java:247)
     [exec]         at org.hsqldb.jdbc.JDBCStatement.fetchResult(JDBCStatement.java:1817)
```

**Comment by drewbrokke** [comment]
Resent here: https://github.com/liferay-usm/liferay-portal/pull/142

**Pull request closed without merging**
