### PR TITLE
LPS-121269 Save OpenId

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
----
Fix the issue where the OpenId is not save when we are editing a user

[Link to the issue](https://issues.liferay.com/browse/LPS-121269)

Proposed Solution
----

Adds the necessary logic on **UpdateUserContactInformationFormMVCActionCommand.java** to save OpenId field
How to test it

Step-by-Step:
---
1. Add a new User
2. Go to Contact > Contact Information
3. Scroll to the bottom and add value in OpenID field
4. Save

### CODE REVIEW

**Comment by gislayne-vitorino** [comment]
Hello @ealonso , your changes seems to be working fine. However it uses a [deprecated method](https://github.com/liferay-usm/liferay-portal/pull/680/files#:~:text=_userLocalService.updateOpenId(user.getUserId()%2C%20openId)%3B). Looking into that you can see that there's no replacement for the method, that's because the OpenId data is [deprecated](https://issues.liferay.com/browse/LPS-118154), now knowing that this pull will be closed in order to open a new one to remove the OpenId field. Thanks for your work

**Comment by ealonso** [comment]
Hey @gislayne-vitorino,

Who is going to do that?, this regression issue was created almost two years ago.

Should I remove OpenId from the user interface? Should I remove all openId related code in portal?

As I can see, we are still using deprecated methods on other places like in **CreateAccountMVCActionCommand** to create users:

```
User user = _userService.addUserWithWorkflow(
```
Shouldn't we removed those deprecated usages?

Please let me know, What we should do in order to fix this regression issue?

cc: @drewbrokke @pei-jung

**Comment by gislayne-vitorino** [comment]
Hi @ealonso,  
I believe that at the moment we must wait for the creation of a new ticket and the closure of the one that is still open. Yes, we still use other deprecated methods, but the problem in the present ticket doesn't seem to be the erasure of the data, but the fact that the field [still exists](https://issues.liferay.com/browse/LPS-118154), furthermore there is not other usages of the OpenId in other parts of the portal, so in my point of view it would be the best to just remove its field from the form and database. Do you have other thoughts about this @drewbrokke ?

**Comment by drewbrokke** [comment]
> Should I remove OpenId from the user interface? Should I remove all openId related code in portal?

Correct, we should definitely remove OpenId from the interface. That can be done immediately.

I've pinged @arthurchan35 and he says that OpenId is basically deprecated everywhere, and that his team hopes to remove it completely from portal soon.

> As I can see, we are still using deprecated methods on other places like in CreateAccountMVCActionCommand to create users:

Yup agree those should be removed. But in any case we should avoid adding any new usages of deprecated methods.

For now, let's prioritize removing the field from the UI. Thank you!

**Comment by drewbrokke** [comment]
@ealonso Sorry just saw that you updated the pull! Thanks! :)

**Comment by drewbrokke** [comment]
@ealonso Sorry just saw that you updated the pull! Thanks!

**Comment by ealonso** [comment]
Hey @drewbrokke, 

Sorry about that, but I put the comment in other pr, 😅 

> Hey @gislayne-vitorino,
> I've updated the pr to removed the openId from UI, also for action commands and poshi tests. It is still pending to remove it from backend, database and other places.
> 
> cc: @drewbrokke

**Comment by drewbrokke** [comment]
Great, thanks @ealonso!

**Comment by epark18** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@epark18 are these failures related?

**Comment by epark18** [comment]
@drewbrokke Failures are unrelated here.

**Comment by ealonso** [comment]
Hey @drewbrokke,

Please let me know if you need something else from my side.

Regards,
Eudaldo

**Comment by drewbrokke** [comment]
Hey @ealonso sorry about the delay on this. I'll finalize this either today or tomorrow.

**Review by drewbrokke — APPROVED** [review]
LGTM 👍 Thanks @ealonso!

**Comment by drewbrokke** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by Sharryxue** [comment]
No related failure found, will manually forward the commits.

**Comment by Sharryxue** [comment]
Manually forwarded to BChan. View https://github.com/brianchandotcom/liferay-portal/pull/121951.

**Pull request closed without merging**
