### PR TITLE
LPS-168598 Add custom fields to Account Headless API

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-168598](https://issues.liferay.com/browse/LPS-168598).<br/><br/>/cc @pei-jung @ChrisKian @patriciajeanperez @david-truong @gislayne-vitorino

### CODE REVIEW

**Comment by drewbrokke** [comment]
Just pushed a fix for the SF failure.

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:reevaluate:1297401_5681

**Comment by melodywu** [comment]
ci:test:relevant

**Pull request closed without merging**
