### PR TITLE
LPS-157176 Add site descriptive name to SiteBriefs in headless API

### PR DESCRIPTION
**Pull request by RafaelCRC**

### CODE REVIEW

**Comment by epark18** [comment]
Failures are unrelated here.

**Comment by epark18** [comment]
@melodywu this is the fix for the story you're testing under the same ticket number.

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
ci:forward

**Comment by epark18** [comment]
ci:forward

**Pull request closed without merging**
