### PR TITLE
LPS-145365 As a Guest User on a custom Site, I'd like to create a User Account to be able to use the website

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
Hi @pei-jung, [UserAccountResourceWhenPostingUserAccountAsGuestTest.testShouldThrowExceptionWithInvalidCaptcha](https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1/32005/testReport/com.liferay.headless.admin.user.resource.v1_0.test/UserAccountResourceWhenPostingUserAccountAsGuestTest/testShouldThrowExceptionWithInvalidCaptcha/) is failing with the following error:

`java.lang.AssertionError: Thread Thread[http-nio-8080-exec-8,5,main] caught concurrent failure: java.lang.AssertionError: {level=ERROR, loggerName=com.liferay.captcha.simplecaptcha.SimpleCaptchaImpl, message=CAPTCHA text is null. User 20104 may be trying to circumvent the CAPTCHA.
java.lang.AssertionError: {level=ERROR, loggerName=com.liferay.captcha.simplecaptcha.SimpleCaptchaImpl, message=CAPTCHA text is null. User 20104 may be trying to circumvent the CAPTCHA.`

Would you please check? Thanks!

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by epark18** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@pei-jung I'm going to close this pull for now so we can have a smaller diff once you're done with the unit tests.

**Pull request closed without merging**
