### PR TITLE
[TS] LPS-157252

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-157252

This could be a core or lima issue, but I'll send to our team first to at least run the test suite.

In the scenario where the user is requesting their default language, the portal and user default language is the same, but the current virtualHost's default language is different, then the portal will still provide the URL without any language code.  This is because the portal is not taking into account the virtualHost's default language when (not) setting the i18nPath to the requested language.  Further, having a virtualHost default language works against the `LOCALE_PREPEND_FRIENDLY_URL_STYLE` 3 (which is the default value) because now the specified virtualHost (without languageId in the URL) only points to one language, instead of any available language.

With my changes, the portal now considers if the virtualHost has a default language, and will include a `i18nPath` value if the requested language is different.

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by crodriguezy** [comment]
Hello @ChrisKian , is there any update about this fix? Do you think it's safe to send it to the customer or we must wait?

**Comment by ChrisKian** [comment]
Hi @crodriguezy,

I've tested and didn't find any issues, and all CI tests are passing, but there's always a chance for bugs to slip through the cracks.  That being said, the fix should be safe for an SDH, since it can be reverted at any time without any lasting effects.

Please let me know if you have any questions, thanks!

**Review by drewbrokke — COMMENTED** [review]
I haven't been able to test this, but it seems ok to me @ChrisKian

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
Seems to me like Echo should take a look at this one too. Thoughts @ChrisKian?

**Comment by ChrisKian** [comment]
Hey @drewbrokke, I'm not sure about Echo, I'd say Core Infra if anything.  We can talk in our standup about it.

**Comment by ChrisKian** [comment]
Forwarded to https://github.com/liferay-core-infra/liferay-portal/pull/1070

**Pull request closed without merging**
