### PR TITLE
LPS-133728 Remove Account_ table and service

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-133728](https://issues.liferay.com/browse/LPS-133728).<br/><br/>/cc @pei-jung @alee8888 @ChrisKian @patriciajeanperez @lr-leo

### CODE REVIEW

**Comment by drewbrokke** [comment]
@patriciajeanperez are these failures related?

**Comment by patriciajeanperez** [comment]
Failures are unrelated. @drewbrokke can you look at the conflicting files? I can manually forward after. Thanks!

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/106148

**Pull request closed without merging**
