### PR TITLE
LPS-170474 There is error of AccountEntryLocalServiceTest > testSearchByAccountGroupIds FAILED

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-170474](https://issues.liferay.com/browse/LPS-170474).<br/><br/>/cc @pei-jung @ChrisKian @patriciajeanperez @david-truong @gislayne-vitorino

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:account

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
FYI @tototrinh

**Comment by drewbrokke** [comment]
ci:test:account

**Review by pei-jung — APPROVED** [review]

**Comment by drewbrokke** [comment]
ci:reevaluate:1327401_7496

**Comment by drewbrokke** [comment]
ci:reevaluate:1257401_5772

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:account

**Comment by drewbrokke** [comment]
@Sharryxue it passed for me locally. I rebased to include the original revert, let's see if that fixes it.

**Comment by drewbrokke** [comment]
@patriciajeanperez are these failures related?

**Comment by nikki-pru** [comment]
ci:test:bundle

**Comment by nikki-pru** [comment]
ci:test:analytics-cloud

**Comment by melodywu** [comment]
Hello @drewbrokke, the test still failed on ci:test:account

[AccountEntryLocalServiceTest > testSearchByAccountGroupIds](https://testray.liferay.com/home/-/testray/case_results/2135551984?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2135541571%26testrayRunId%3D2135551385%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) keep fails, refer [console log](https://testray.liferay.com/reports/production/logs/2022-12/test-1-26/test-portal-acceptance-pullrequest(master)/6466/modules-integration-mysql57-jdk8/0/1/jenkins-console.txt.gz?authuser=0)

```
[exec] com.liferay.account.service.test.AccountEntryLocalServiceTest > testSearchByAccountGroupIds FAILED
     [exec]     com.liferay.portal.kernel.exception.NoSuchUserException: No User exists with the primary key 59718
     [exec]     	at com.liferay.portal.service.persistence.impl.UserPersistenceImpl.findByPrimaryKey(UserPersistenceImpl.java:8676)
     [exec]     	at com.liferay.portal.service.persistence.impl.UserPersistenceImpl.findByPrimaryKey(UserPersistenceImpl.java:8692)
     [exec]     	at com.liferay.portal.service.impl.UserLocalServiceImpl.getUserById(UserLocalServiceImpl.java:2797)
     [exec]     	at sun.reflect.GeneratedMethodAccessor353.invoke(Unknown Source)
```

**Comment by drewbrokke** [comment]
Thanks @melodywu, I'll take a look.

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:account

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by melodywu** [comment]
No related issue found in ci:test:relevant and ci:test:account.

**Comment by drewbrokke** [comment]
@melodywu @Sharryxue if this one looks good to you, we can manually forward to Brian.

**Comment by patriciajeanperez** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/128130

**Pull request closed without merging**
