### PR TITLE
LPS-168928 Create ConfigurationScreen for viewing and modifying Feature Flags

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-168928](https://issues.liferay.com/browse/LPS-168928).<br/><br/>/cc @pei-jung @ChrisKian @patriciajeanperez @david-truong @gislayne-vitorino

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:help

**Comment by melodywu** [comment]
ci:test:object

**Comment by melodywu** [comment]
ci:test:bundle

**Comment by melodywu** [comment]
ci:test:object

**Comment by drewbrokke** [comment]
ci:reevaluate:1287401_5391

**Comment by Sharryxue** [comment]
No related issue found in ci:test:relevant.

**Comment by drewbrokke** [comment]
@patriciajeanperez @Sharryxue if this looks good to you, we can manually forward to Brian

**Comment by Sharryxue** [comment]
Manual forward to BChan. Refer https://github.com/brianchandotcom/liferay-portal/pull/127704.

**Comment by Sharryxue** [comment]
ci:close

**Pull request closed without merging**
