### PR TITLE
LPS-165197 - show exceptions for uppercase , symbols and numbers

### PR DESCRIPTION
**Pull request by antonio91dev**
LPS-165197 - show exceptions for uppercase , symbols and numbers﻿

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Review by drewbrokke — CHANGES_REQUESTED** [review]
@antonio91dev looks like there are a number of SF failures.

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by melodywu** [comment]
ci:test:relevant

**Review by drewbrokke — APPROVED** [review]
Looks good, thanks @antonio91dev!

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
