### PR TITLE
LPS-138606 Include more Address fields as searchable

### PR DESCRIPTION
**Pull request by erickmonteiroo**

### CODE REVIEW

**Review by drewbrokke — CHANGES_REQUESTED** [review]
@erickmonteiroo can you please include test coverage for these changes? We already have some address search test cases in AddressLocalServiceTest so you can build off what is there. Thanks!

**Comment by erickmonteiroo** [comment]
ci:test:relevant

**Review by drewbrokke — APPROVED** [review]
LGTM 👍

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
