### PR TITLE
LPS-162300 Allow to get users of User groups that belong to Team

### PR DESCRIPTION
**Pull request by hongvo2308**
Hi,
Please help review this PR and leave your comments. Thanks.
Ticket: https://issues.liferay.com/browse/LPS-162300

CC: @tototrinh

### CODE REVIEW

**Comment by tototrinh** [comment]
ci:test:sf

**Review by drewbrokke — CHANGES_REQUESTED** [review]
@hongvo2308 @tototrinh thank you for sending this change. Overall it looks good, but we should also include integration test coverage for this issue. Can you please add test coverage and either force-push or resend? 

Please let me know if you have any questions. Thank you!

**Comment by tototrinh** [comment]
Thanks, @drewbrokke for taking a look at this. I update the test based on the case mentioned on the ticket. Thanks.

**Comment by tototrinh** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by melodywu** [comment]
ci:test:relevant

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
ci:forward

**Comment by patriciajeanperez** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/125393

**Pull request closed without merging**
