### PR TITLE
LPS-169794 Duplicate value can be added in the text box when invite user to account

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-169794](https://issues.liferay.com/browse/LPS-169794).

/cc @pei-jung @ChrisKian @patriciajeanperez @david-truong @gislayne-vitorino

Screen Recording 2023-01-26 at 1 15 06 PM

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:test:account

**Review by pei-jung — APPROVED** [review]

**Comment by pei-jung** [comment]
ci:forward

**Pull request closed without merging**
