### PR TITLE
LPS-171373 Backend Test Fix - AssertionError on RolesAdminPortletDataHandlerTest and OrganizationLocalServiceTest

### PR DESCRIPTION
**Pull request by quanhuynhces**
Hi team,
This PR is for fixing integration test of https://issues.liferay.com/browse/LPS-171373
Please review and leave your comment.
Thanks,
Quan
cc @locpham97

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
No related issue found in ci:test:relevant.

**Comment by melodywu** [comment]
ci:test:sf

**Review by drewbrokke — COMMENTED** [review]
@quanhuynhces thanks for sending this. This issue should be fixed by the changes from https://issues.liferay.com/browse/LPS-170474. I'll close this for now, if it is not fixed we can revisit the issue. Thanks!

**Pull request closed without merging**
