### PR TITLE
LPS-142501 Allow multiple Listeners per Configuration

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-142501](https://issues.liferay.com/browse/LPS-142501).<br/><br/>/cc @pei-jung @alee8888 @ChrisKian @patriciajeanperez @lr-leo @erickmonteiroo

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@patriciajeanperez are these failures related?

**Comment by epark18** [comment]
ci:test:relevant

**Comment by epark18** [comment]
Failures don't appear to be related. Rerunning relevant to confirm.

**Comment by drewbrokke** [comment]
ci:reevaluate:1127401_5119

**Comment by patriciajeanperez** [comment]
Failures are unrelated

**Comment by drewbrokke** [comment]
ci:reevaluate:1127401_5119

**Comment by drewbrokke** [comment]
@patriciajeanperez if these are unrelated, would you be willing to manually forward this change? Thanks!

**Comment by epark18** [comment]
@drewbrokke Looks like Patricia is out today, but I can take care of this :]

**Comment by drewbrokke** [comment]
Thanks @epark18 !

**Comment by epark18** [comment]
Pushed to BChan:
[#110219](https://github.com/brianchandotcom/liferay-portal/pull/110219)

**Comment by epark18** [comment]
ci:close

**Pull request closed without merging**
