### PR TITLE
LPS-143949 NPE in AccountResourceTest

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Review by drewbrokke — APPROVED** [review]

**Comment by epark18** [comment]
ci:test:relevant

**Comment by epark18** [comment]
These failures are unrelated

**Comment by patriciajeanperez** [comment]
ci:test:account

**Comment by patriciajeanperez** [comment]
Account test failures above are unrelated.

**Comment by pei-jung** [comment]
@patriciajeanperez is this safe to forward?

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
