### PR TITLE
users-admin-impl: preserves user full name case when indexing

### PR DESCRIPTION
**Pull request by drewbrokke**

### CODE REVIEW

**Comment by drewbrokke** [comment]
Hey @patriciajeanperez, which test suites should we run to put the user search indexer through its paces? This change could potentially have an impact on it.

**Comment by drewbrokke** [comment]
FYI @david-truong

**Comment by patriciajeanperez** [comment]
Hey @drewbrokke, did you mean UserIndexerTest? Relevant actually ran them already. See [console](https://testray.liferay.com/reports/production/logs/2022-08/test-1-32/test-portal-acceptance-pullrequest(master)/5237/modules-integration-mysql57-jdk8/0/2/jenkins-console.txt.gz?authuser=0) for UserIndexerIndexedFieldsTest failures.

**Comment by lipusz** [comment]
Ironic... https://github.com/lipusz/liferay-portal/commit/3f041120adfd79b1027f10a95e42547bc341bf2a @drewbrokke :innocent:

**Pull request closed without merging**
