### PR TITLE
LPS-157442 NPE when updating password through API updateUserAccount while that user is logged in

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:reevaluate:1317401_4055

**Comment by pei-jung** [comment]
The failures look related. I'll take a look.

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Review by drewbrokke — COMMENTED** [review]
Looks good @pei-jung. Would it be reasonable effort to add test coverage for this?

**Review by drewbrokke — APPROVED** [review]

**Comment by pei-jung** [comment]
@drewbrokke It will be complicated to add an integration test for this since we need to create an http session for the user. I'll check with Eric to see if it's possible to have a functional test for this.

**Comment by drewbrokke** [comment]
ci:reevaluate:1327401_4671

**Comment by drewbrokke** [comment]
@pei-jung this one is good to go IMO, so we can manually forward it assuming the CI failures are unrelated. (@epark18)

**Comment by epark18** [comment]
I am unsure of this one. Going to run tests locally.

**Comment by epark18** [comment]
[portal-license-smoke-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/1899935677) is failing consistently with these errors: [Logs](https://testray.liferay.com/reports/production/logs/2022-07/test-1-32/test-portal-acceptance-pullrequest(master)/4671/portal-license-smoke-jdk8/0/0/jenkins-console.txt.gz?authuser=0)
```    [junit] Testcase: testScanXMLLog(com.liferay.portal.log.assertor.PortalLogAssertorTest):	FAILED
    [junit] 
    [junit] Portal log assert failure, see above log for more information: 
    [junit] Declarative Service Unsatisfied Component Checker check result: 
    [junit] Bundle {id: 136, name: com.liferay.site.welcome.site.initializer, version: 1.0.19}
    [junit] 	Declarative Service {id: 6129, name: com.liferay.site.welcome.site.initializer.internal.instance.lifecycle.AddDefaultLayoutPortalInstanceLifecycleListener, unsatisfied references: 
    [junit] 		{name: _siteInitializer, target: (site.initializer.key=com.liferay.site.initializer.welcome)}
    [junit] 	}
    [junit] Bundle {id: 734, name: com.liferay.headless.admin.user.impl, version: 5.0.56}
    [junit] 	Declarative Service {id: 2327, name: com.liferay.headless.admin.user.internal.resource.v1_0.factory.UserAccountResourceFactoryImpl, unsatisfied references: 
    [junit] 		{name: _componentServiceObjects, target: null}
    [junit] 	}
    [junit] 	Declarative Service {id: 2283, name: com.liferay.headless.admin.user.internal.graphql.servlet.v1_0.ServletDataImpl, unsatisfied references: 
    [junit] 		{name: _userAccountResourceComponentServiceObjects, target: null}
    [junit] 	}
    [junit] 	Declarative Service {id: 2313, name: com.liferay.headless.admin.user.internal.resource.v1_0.UserAccountResourceImpl, unsatisfied references: 
    [junit] 		{name: _cookiesManager, target: null}
    [junit] 	}
    [junit] Bundle {id: 1102, name: com.liferay.site.initializer.extender, version: 1.0.48}
    [junit] 	Declarative Service {id: 4309, name: com.liferay.site.initializer.extender.internal.file.backed.servlet.FileBackedThumbnailServlet, unsatisfied references: 
    [junit] 		{name: _siteInitializerExtender, target: null}
    [junit] 	}
    [junit] 	Declarative Service {id: 4308, name: com.liferay.site.initializer.extender.internal.SiteInitializerExtender, unsatisfied references: 
    [junit] 		{name: _userAccountResourceFactory, target: null}
    [junit] 	}
    [junit] junit.framework.AssertionFailedError: 
    [junit] Declarative Service Unsatisfied Component Checker check result: 
    [junit] Bundle {id: 136, name: com.liferay.site.welcome.site.initializer, version: 1.0.19}
    [junit] 	Declarative Service {id: 6129, name: com.liferay.site.welcome.site.initializer.internal.instance.lifecycle.AddDefaultLayoutPortalInstanceLifecycleListener, unsatisfied references: 
    [junit] 		{name: _siteInitializer, target: (site.initializer.key=com.liferay.site.initializer.welcome)}
    [junit] 	}
    [junit] Bundle {id: 734, name: com.liferay.headless.admin.user.impl, version: 5.0.56}
    [junit] 	Declarative Service {id: 2327, name: com.liferay.headless.admin.user.internal.resource.v1_0.factory.UserAccountResourceFactoryImpl, unsatisfied references: 
    [junit] 		{name: _componentServiceObjects, target: null}
    [junit] 	}
    [junit] 	Declarative Service {id: 2283, name: com.liferay.headless.admin.user.internal.graphql.servlet.v1_0.ServletDataImpl, unsatisfied references: 
    [junit] 		{name: _userAccountResourceComponentServiceObjects, target: null}
    [junit] 	}
    [junit] 	Declarative Service {id: 2313, name: com.liferay.headless.admin.user.internal.resource.v1_0.UserAccountResourceImpl, unsatisfied references: 
    [junit] 		{name: _cookiesManager, target: null}
    [junit] 	}
    [junit] Bundle {id: 1102, name: com.liferay.site.initializer.extender, version: 1.0.48}
    [junit] 	Declarative Service {id: 4309, name: com.liferay.site.initializer.extender.internal.file.backed.servlet.FileBackedThumbnailServlet, unsatisfied references: 
    [junit] 		{name: _siteInitializerExtender, target: null}
    [junit] 	}
    [junit] 	Declarative Service {id: 4308, name: com.liferay.site.initializer.extender.internal.SiteInitializerExtender, unsatisfied references: 
    [junit] 		{name: _userAccountResourceFactory, target: null}
    [junit] 	}
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest.scanXMLLogFile(PortalLogAssertorTest.java:171)
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:98)
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:88)
    [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2670)
    [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2742)
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest.testScanXMLLog(PortalLogAssertorTest.java:86)```

**Comment by drewbrokke** [comment]
@pei-jung looks like the `cookies` module group is ignored in the release. We can't depend on `cookies-api` yet in any released module.

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
