### PR TITLE
LPS-143805 Account type field is not capitalized

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-143805](https://issues.liferay.com/browse/LPS-143805).<br/><br/>/cc @pei-jung @alee8888 @ChrisKian @patriciajeanperez @lr-leo @erickmonteiroo

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
ci:test:account

**Comment by drewbrokke** [comment]
@patriciajeanperez are the test failures real, or is this one good to go?

**Comment by patriciajeanperez** [comment]
ci:test:bundle

**Comment by patriciajeanperez** [comment]
Resent with test fix: https://github.com/liferay-usm/liferay-portal/pull/381

**Comment by patriciajeanperez** [comment]
ci:close

**Pull request closed without merging**
