### PR TITLE
[TS] LPS-141903

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-141903

CC @huynguyen-codeengine, @thuycao-gs

### CODE REVIEW

**Comment by epark18** [comment]
Some checks failed due to timeout, rerunning relevant.

**Comment by epark18** [comment]
ci:test:relevant

**Review by drewbrokke — CHANGES_REQUESTED** [review]
The changes look good, just one SF/refactor needed. 

Also, please include a test case or assertion inside of `RoleLocalServiceTest`.

Thanks!

**Comment by ChrisKian** [comment]
Thanks @drewbrokke, I'll reassign the LPS to Thuy and work with her as-needed.

**Pull request closed without merging**
