### PR TITLE
LPS-136087 Include shared account roles in the get account roles headless endpoint

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-136087](https://issues.liferay.com/browse/LPS-136087).<br/><br/>/cc @pei-jung @alee8888 @ChrisKian @patriciajeanperez @lr-leo 

/cc @luca-pellizzon

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
Portal compile error, BChan is working on fix the issue.
```
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/object/object-dynamic-data-mapping/src/main/java/com/liferay/object/dynamic/data/mapping/internal/storage/ObjectDDMStorageAdapter.java:263: error: cannot find symbol
     [exec] 						defaultLocale, objectFieldTypes.get(objectFieldName),
     [exec] 						^
     [exec]   symbol:   variable defaultLocale
     [exec]   location: class ObjectDDMStorageAdapter
     [exec] 1 error
     [exec] Note: Some input files use or override a deprecated API.
     [exec] Note: Recompile with -Xlint:deprecation for details.
     [exec] Note: Some input files use unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] 
     [exec] > Task :apps:object:object-dynamic-data-mapping:compileJava FAILED

```

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:forward

**Comment by Sharryxue** [comment]
Related compile error found in ci:test:relevant test suite, hello @drewbrokke, would you please take a look into the issue? Thanks.
```
     [exec] 2021-08-12 15:08:18.299 INFO  [fileinstall-directory-watcher][BundleStartStopLogger:46] STARTED org.apache.aries.util_1.1.1 [1384]
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/headless/headless-admin-user/headless-admin-user-test/src/testIntegration/java/com/liferay/headless/admin/user/resource/v1_0/test/AccountRoleResourceTest.java:170: error: method does not override or implement a method from a supertype
     [exec] 	@Override
     [exec] 	^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/headless/headless-admin-user/headless-admin-user-test/src/testIntegration/java/com/liferay/headless/admin/user/resource/v1_0/test/AccountRoleResourceTest.java:178: error: cannot find symbol
     [exec] 				testGetAccountRolesByExternalReferenceCodePage_getExternalReferenceCode(),
     [exec] 				^
     [exec]   symbol:   method testGetAccountRolesByExternalReferenceCodePage_getExternalReferenceCode()
     [exec]   location: class AccountRoleResourceTest
```

**Comment by drewbrokke** [comment]
See https://github.com/liferay-usm/liferay-portal/pull/218

**Pull request closed without merging**
