### PR TITLE
LPS-157176 Add site descriptive name to SiteBriefs in headless API

### PR DESCRIPTION
**Pull request by RafaelCRC**

### CODE REVIEW

**Comment by RafaelCRC** [comment]
ci:test:relevant

**Comment by RafaelCRC** [comment]
ci:test:relevant

**Comment by epark18** [comment]
ci:stop

**Comment by epark18** [comment]
ci:test:relevant

**Comment by epark18** [comment]
ci:test:relevant

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
