### PR TITLE
LPS-126912 Migrate Commerce account roles to Portal account roles

### PR DESCRIPTION
**Pull request by pei-jung**
@achaparro @riccardo-alberti

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
@pei-jung just tested with minium demo + a site role used as both account and site role. I get this exception: 
`Caused by: com.liferay.portal.kernel.log.LogSanitizerException: org.postgresql.util.PSQLException: ERROR: syntax error at or near "Group"_  Position: 86 [Sanitized]
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440) ~[postgresql.jar:42.2.5]
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183) ~[postgresql.jar:42.2.5]
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308) ~[postgresql.jar:42.2.5]
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441) ~[postgresql.jar:42.2.5]
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365) ~[postgresql.jar:42.2.5]
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143) ~[postgresql.jar:42.2.5]
        at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:106) ~[postgresql.jar:42.2.5]
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[hikaricp.jar:?]
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) ~[hikaricp.jar:?]
        at com.liferay.commerce.account.internal.upgrade.v9_1_0.CommerceAccountRoleUpgradeProcess._hasNonaccountEntryGroup(CommerceAccountRoleUpgradeProcess.java:171) ~[?:?]
        at com.liferay.commerce.account.internal.upgrade.v9_1_0.CommerceAccountRoleUpgradeProcess.doUpgrade(CommerceAccountRoleUpgradeProcess.java:81) ~[?:?]
        at com.liferay.portal.kernel.upgrade.UpgradeProcess.lambda$upgrade$0(UpgradeProcess.java:114) ~[portal-kernel.jar:?]
        at com.liferay.portal.db.partition.DBPartitionUtil.forEachCompanyId(DBPartitionUtil.java:113) ~[portal-impl.jar:?]
        at com.liferay.portal.dao.db.BaseDB.process(BaseDB.java:307) ~[portal-impl.jar:?]
        at com.liferay.portal.kernel.dao.db.BaseDBProcess.process(BaseDBProcess.java:225) ~[portal-kernel.jar:?]
        at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:101) ~[portal-kernel.jar:?]
        ... 112 more
`

**Comment by pei-jung** [comment]
@riccardo-alberti sorry, there was a typo in the query. I fixed it and forced push the change.

**Comment by pei-jung** [comment]
ci:test:upgrade

**Comment by patriciajeanperez** [comment]
@pei-jung the upgrade failures are not related.

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
@pei-jung yep i tested and it looks good to me. thanks

**Comment by pei-jung** [comment]
Great! Thanks for verifying, @riccardo-alberti!

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
