### PR TITLE
LPS-164522 Rename the column Contact_

### PR DESCRIPTION
**Pull request by gislayne-vitorino**
This is an update for: [subtask: LPS-164522](https://issues.liferay.com/browse/LPS-164522), Task: [LPS-155969](https://issues.liferay.com/browse/LPS-155969)

### CODE REVIEW

**Review by RafaelCRC — APPROVED** [review]
LGTM! :+1:

**Comment by melodywu** [comment]
Relevant failures are not related.  Note : For the `Failed prior to running test` testcases are failed by  LPS-165074.

**Comment by Sharryxue** [comment]
Hello @gislayne-vitorino,
Could you please help with double checking if the [semantic-versioning](https://testray.liferay.com/en/home/-/testray/case_results/2002761777) failure related? Refer the full [jenkins console](https://testray.liferay.com/reports/production/logs/2022-10/test-1-39/test-portal-acceptance-pullrequest(master)/812/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0). Thanks in advance.
```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/portal-security/portal-security-ldap-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.portal.security.ldap.exportimport      MAJOR      1.1.0      1.1.0      2.0.0      VERSION INCREASE REQUIRED
     [exec]     	>   class      com.liferay.portal.security.ldap.exportimport.LDAPUser
     [exec]     		-   method     getPrefixId()
     [exec]     			-   return     long
     [exec]     		+   method     getPrefixListTypeId()
```
/cc @melodywu

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
ci:test:relevant

**Comment by melodywu** [comment]
Relevant failures are not related

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
The [semantic-versioning](https://testray.liferay.com/home/-/testray/case_results/2007198927) failures probably related, refer the [full console](https://testray.liferay.com/reports/production/logs/2022-10/test-1-27/test-portal-acceptance-pullrequest(master)/5370/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0). Hello @gislayne-vitorino , could you please help with double check? Thanks in advance. No other related issue found in [ci:test:relevant](https://github.com/liferay-usm/liferay-portal/pull/776#issuecomment-1279665142) result.
```
     [exec] > Task :apps:headless:headless-portal-instances:headless-portal-instances-api:baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.headless.portal.instances.dto.v1_0     MAJOR      2.2.1      3.0.0      4.0.0      VERSION INCREASE REQUIRED
     [exec] 	+   class      com.liferay.headless.portal.instances.dto.v1_0.Admin
```

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by melodywu** [comment]
Relevant failures are not related.

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
ci:test:relevant

**Review by drewbrokke — APPROVED** [review]
Looks great @gislayne-vitorino.

**Comment by drewbrokke** [comment]
@patriciajeanperez I think we're good to go on this one.

**Comment by drewbrokke** [comment]
ci:forward

**Comment by patriciajeanperez** [comment]
ci:test:usm

**Comment by patriciajeanperez** [comment]
ci:test:usm

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@patriciajeanperez if this one looks ok to you the we're good to forward.

**Comment by patriciajeanperez** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/125378

**Pull request closed without merging**
