### PR TITLE
LPS-167836 Remove redundant usages of the method getSearchActionURL from oauth2-provider-web

### PR DESCRIPTION
**Pull request by gislayne-vitorino**
This is an update for [subtask: LPS-167836](https://issues.liferay.com/browse/LPS-167836), [LPS-161233](https://issues.liferay.com/browse/LPS-161233)

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:test:stable

**Comment by melodywu** [comment]
No related issue found in ci:test:relevant.

**Comment by patriciajeanperez** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/126086

**Pull request closed without merging**
