### PR TITLE
LPS-133375 add field users.reminder.queries.enabled for portal property.

### PR DESCRIPTION
**Pull request by balazsmatyassyliferay**
Hi,
could you please process this pull request?

Up until 7.2, it was possible to set certain portal properties on a per-instance basis, by using the per-instance property files feature. But this feature has been removed from 7.3, and apparently we will decide on a per-case basis which such properties can continue to be configurable on a per-instance basis, by moving them to Control Panel/Instance Settings as needed.

I have asked questions about the modification on the following PTR:
https://issues.liferay.com/browse/PTR-2449
@ChrisKian

Thank you!
Greetings
Balázs

### CODE REVIEW

**Comment by balazsmatyassyliferay** [comment]
ci:test:sf

**Review by drewbrokke — CHANGES_REQUESTED** [review]
@balazsmatyassyliferay this change looks fine, but I think that it's probably best for us to act on all of the `users.reminder.queries.*` portal properties at one time. There should be five of them: https://github.com/liferay/liferay-portal/blob/ca00c3b11f7a6aa04d7216b586cfdac6b5e88423/portal-impl/src/portal.properties#L2458-L2493

Will you please place them all on a new view under the same parent category, as a sibling to the `General` tab where you find this view? You can copy the pattern seen in https://github.com/liferay/liferay-portal/blob/ca00c3b11f7a6aa04d7216b586cfdac6b5e88423/modules/apps/portal-settings/portal-settings-web/src/main/java/com/liferay/portal/settings/web/internal/portal/settings/configuration/admin/display/GeneralAuthenticationEditCompanyPortalSettingsConfigurationScreenContributor.java. We can just call it "Reminder Queries".

Also, be sure to include any help text found in the portal properties as help keys on the inputs.

Please let me know if you have any questions. Thanks!

**Comment by drewbrokke** [comment]
@balazsmatyassyliferay this commit should serve as a good template for creating a new entry: https://github.com/brianchandotcom/liferay-portal/pull/71488/commits/9254ec8c2da2bab6037598486afb72dba98b4dbd

**Comment by drewbrokke** [comment]
cc @ChrisKian

**Comment by balazsmatyassyliferay** [comment]
Closing pull request. I will redo the update with you proposed changes. After it I will resend the pull request.

**Comment by balazsmatyassyliferay** [comment]
Dear @drewbrokke ,
I tried to add the properties in a new Java class.

@Component(service = PortalSettingsConfigurationScreenContributor.class)
public class
	PasswordReminderQueriesEditCompanyPortalSettingsConfigurationScreenContributor
		extends BaseEditCompanyPortalSettingsConfigurationScreenContributor {
		[...]

I built the bundle a deployed it to a local Liferay instance.
The strange thing was that apparently my new service is not detected by OSGi.

I added a test constructor to the new class and to an existing one.
The "Hello World" message only appeared in System.out while the existing class was instantiated.

Do you have an idea what I am missing?
Why is my bean not detected by OSGi?

Thank you for your help!

Greetings
Balázs

**Comment by drewbrokke** [comment]
Hi @balazsmatyassyliferay, sorry to hear you're having issues. I can't say much without seeing your code, but if what you posted is accurate, perhaps the `@component` annotation should be capitalized?

**Pull request closed without merging**
