### PR TITLE
LPS-163921 Rename the column EmailAddress

### PR DESCRIPTION
**Pull request by gislayne-vitorino**

### CODE REVIEW

**Review by RafaelCRC — APPROVED** [review]
LGTM! :+1:

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
ci:test:relevant

**Comment by gislayne-vitorino** [comment]
ci:test:relevant

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Review by pei-jung — APPROVED** [review]
Nice work! Thanks @gislayne-vitorino!

**Comment by drewbrokke** [comment]
ci:reevaluate:1267401_5281

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
ci:test:relevant

**Comment by gislayne-vitorino** [comment]
ci:stop

**Comment by gislayne-vitorino** [comment]
ci:stop

**Comment by gislayne-vitorino** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Looks like a real failure in `directory-web` @gislayne-vitorino. Check https://github.com/liferay/liferay-portal/blob/03adef1fd8882afcb058bfae20826209f8bd17ff/modules/apps/archived/directory-web/src/main/resources/META-INF/resources/common/additional_email_addresses.jsp#L42.

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@patriciajeanperez any objections to forwarding this one? It looks good on my end.

**Comment by patriciajeanperez** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/124318

**Pull request closed without merging**
