### PR TITLE
LPS-155692 Refuse access to user pages via plid

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
ci:forward

**Comment by pei-jung** [comment]
@epark18 is the failure related?

**Comment by epark18** [comment]
@pei-jung This is unrelated.

**Comment by epark18** [comment]
Forwarded to Brian. https://github.com/brianchandotcom/liferay-portal/pull/120890.

**Comment by epark18** [comment]
ci:close

**Pull request closed without merging**
