### PR TITLE
LPS-160355 Update frontend:cards with clay:cards

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
----
In order to replace all frontend:cards from portal we should update the users admin web module to use clay:cards

[Link to the issue](https://issues.liferay.com/browse/LPS-160355)

Proposed Solution
----
The pull includes the following changes for users and organizations

Users:
* Update UserVerticalCard to accept actions
* Creates new java class with dropdown actions
* Use clay dropdown to show actions on list and descriptive view
* Use clay user card on icon view

Organizations:
* Creates OrganizationVerticalCard
* Creates new java class with dropdown actions
* Use clay dropdown to show actions on list and descriptive view
* Use clay vertical card on icon view

Also the first two commits are about removing unused code.

Please let me know if you have any question.

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:test:usm

**Comment by patriciajeanperez** [comment]
Thank you, @ealonso! I reviewed the test results and our functional tests caught some issues with the PR: 

**Users Admin:**
- Ellipsis for users are not aligned to the user
ellipsis

**Organizations Admin:**

The following issues for Organizations might be caused by: 
`2022-08-15 18:20:07.666 ERROR [http-nio-8080-exec-5][IncludeTag:128] Current URL /group/control_panel/manage?p_p_id=com_liferay_users_admin_web_portlet_UsersAdminPortlet&p_p_lifecycle=0&p_p_state=maximized&p_p_mode=view&_com_liferay_users_admin_web_portlet_UsersAdminPortlet_mvcRenderCommandName=%2Fusers_admin%2Fview&_com_liferay_users_admin_web_portlet_UsersAdminPortlet_organizationId=73938&_com_liferay_users_admin_web_portlet_UsersAdminPortlet_toolbarItem=view-all-organizations&_com_liferay_users_admin_web_portlet_UsersAdminPortlet_usersListView=tree generates exception: /user_action.jsp`

- Assign Organization Roles modal is empty

- Missing Add Organization menu item when adding a suborganization

- Missing ellipsis or menu items for users assigned to organization

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:usm

**Comment by ealonso** [comment]
Hey @patriciajeanperez,

Sorry about that, I've already fix the issues. But, I don't know if we need to update some poshi tests.

Regards,
Eudaldo

**Comment by patriciajeanperez** [comment]
Hi @ealonso! The missing ellipsis and menu items are fixed but these are the issues that are still present:

- Remove menu item in removing users is not responsive


- Assign Organization Roles modal is still empty
184786541-2a1e72f7-82d3-47f9-b257-2108be4d1ce2

I will be sending you a PR with the test fixes. Would you be able to send in a new PR with the test fixes and the fixes for the above issues? Thank you!

**Comment by patriciajeanperez** [comment]
Sent test fixes in https://github.com/ealonso/liferay-portal/pull/3215

**Comment by ealonso** [comment]
Hey @patriciajeanperez,

I've already fixed those cases and I updated the pr, it also includes your test fixes 

Thanks for letting me know and your help

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:usm

**Comment by ealonso** [comment]
ci:reevaluate:1317401_4623

**Comment by ealonso** [comment]
ci:test:usm

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
Failures are unrelated

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
Failure are unrelated

**Comment by ealonso** [comment]
ci:reopen

**Comment by drewbrokke** [comment]
@ealonso sorry about the delay on this one. Go ahead and re-send a new PR and I'll review it this week. Thanks!

**Comment by ealonso** [comment]
@drewbrokke please see: https://github.com/liferay-usm/liferay-portal/pull/722

**Pull request closed without merging**
