### PR TITLE
LPS-163483 add available localizations for auto-generated regions

### PR DESCRIPTION
**Pull request by ces-huynguyen**
LPS-163483 add available localizations for auto-generated regions

### CODE REVIEW

**Comment by Sharryxue** [comment]
No related failure found in ci:test:relevant.

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
ci:reevaluate:1307401_4707

**Comment by drewbrokke** [comment]
ci:forwrad

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
