### PR TITLE
COMMERCE-6843 Migrate account-rest endpoints to headless-admin-user module

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [COMMERCE-6843](https://issues.liferay.com/browse/COMMERCE-6843).<br/><br/>/cc @pei-jung @alee8888 @ChrisKian @patriciajeanperez @lr-leo

### CODE REVIEW

**Comment by drewbrokke** [comment]
cc @luca-pellizzon

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
Hey @drewbrokke the tests failing for UserAccountResourceTest.testPostAccountUser(UserAccountResourceTest.java:398) is due to the externalReferenceCode set as readOnly for the User. This end up with the method "postAccountUser" receiving a UserAccount with externalReferenceCode = null.
Change done yesterday by Amos 0e5fa6bfe327653224007499150a8e04286c51f6
We all agreed, some time ago, not to merge changes before this PR, but now every day we are facing issues because of conflicts or tests failing because of new code merged.

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:forward

**Comment by patriciajeanperez** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/105169

**Comment by patriciajeanperez** [comment]
ci:close

**Pull request closed without merging**
