### PR TITLE
LPS-176902 There should be a default service account for each virtual instance

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
Hi @pei-jung! Can you take a look at this [test failure](https://testray.liferay.com/reports/production/logs/2023-04/test-1-40/test-portal-acceptance-pullrequest(master)/1447/modules-integration-mysql57-jdk8/4/5/jenkins-console.txt.gz?authuser=0)?

     [exec] com.liferay.user.service.test.UserLocalServiceTest > testSearch FAILED
     [exec]     java.lang.AssertionError: [] expected:<1> but was:<0>

Thank you!

**Comment by patriciajeanperez** [comment]
ci:test:users

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:users

**Comment by pei-jung** [comment]
@patriciajeanperez are these failures related?

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:forward:force

**Pull request closed without merging**
