### PR TITLE
LPS-165244 Rename the column Organization

### PR DESCRIPTION
**Pull request by gislayne-vitorino**
This is an update for: [subtask: LPS-165244](https://issues.liferay.com/browse/LPS-165244), [LPS-155969](https://issues.liferay.com/browse/LPS-155969)

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
ci:test:users

**Review by RafaelCRC — COMMENTED** [review]
Please check the commit 2452e9a30f32495e9a071f7d172d330e86aa18ce
It seems empty. 
For the rest of the PR everything looks good!

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
Hi @gislayne-vitorino! I am still compiling but based from the test failures, it looks like Organizations do not get saved. Please take a look. Thank you!

**Comment by Sharryxue** [comment]
ci:test:bundle

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
ci:test:relevant

**Comment by melodywu** [comment]
ci:test:bundle

**Comment by melodywu** [comment]
Hi @gislayne-vitorino! Organizations still do not get saved. Please take a look. Thank you!

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:test:users

**Comment by melodywu** [comment]
No related failure found in ci:test:relevant and ci:test:users.

**Comment by drewbrokke** [comment]
ci:reevaluate:1307401_5118

**Review by drewbrokke — APPROVED** [review]
Looks great @gislayne-vitorino!

**Comment by drewbrokke** [comment]
ci:forward

**Comment by patriciajeanperez** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/125161

**Pull request closed without merging**
