### PR TITLE
LPS-141291 Migrate portal property auth.login.prompt.enabled to site scoped configuration

### PR DESCRIPTION
**Pull request by erickmonteiroo**

### CODE REVIEW

**Comment by erickmonteiroo** [comment]
ci:test:upgrade

**Comment by erickmonteiroo** [comment]
ci:test:sf

**Comment by erickmonteiroo** [comment]
ci:test:relevant

**Comment by erickmonteiroo** [comment]
ci:test:relevant

**Comment by erickmonteiroo** [comment]
ci:test:relevant

**Comment by erickmonteiroo** [comment]
ci:test:sf

**Comment by erickmonteiroo** [comment]
ci:test:relevant

**Comment by erickmonteiroo** [comment]
ci:test:upgrade

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Review by pei-jung — CHANGES_REQUESTED** [review]
Nicely done, Erick! 

You can combine all the commits that adds the new language keys into a single commit since they're related and are used for the new configuration.

**Comment by erickmonteiroo** [comment]
ci:test:sf

**Comment by erickmonteiroo** [comment]
ci:test:relevant

**Review by pei-jung — APPROVED** [review]
Changes look good. Nice work, @erickmonteiroo!

**Comment by pei-jung** [comment]
Hi @epark18, are the failures related?

**Comment by epark18** [comment]
> Hi @epark18, are the failures related?

Failures in relevant are unrelated.

**Comment by erickmonteiroo** [comment]
Looks like there's a conflict. I will rebase it.

**Comment by erickmonteiroo** [comment]
ci:stop

**Comment by erickmonteiroo** [comment]
ci:test:sf

**Comment by erickmonteiroo** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:forward

**Pull request closed without merging**
