### PR TITLE
LPS-178158 Adding account Group doesn't show expando fields

### PR DESCRIPTION
**Pull request by jgarcialr**

### CODE REVIEW

**Review by drewbrokke — CHANGES_REQUESTED** [review]
@jgarcialr thank you for sending this change! Unfortunately, it is not complete. The fields render in the form now, but the values of the form are neither read nor saved.

You'll need to get the expando attributes off of the request inside of `EditAccountGroupMVCActionCommand`.

**Comment by jgarcialr** [comment]
Hi @drewbrokke,
Sorry, I forgot the backend side :facepalm: 

I've seen we haven't got methods that have/use serviceContext in the service layer. 
I've created those methods to handle the add or update inside the service layer instead of doing it in the actionCommand class.
I've tested it, and it saves and retrieve the expando info as expected.

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
Hi @drewbrokke ,

Do you have time to review the PR?

Thanks in advance.

**Review by drewbrokke — APPROVED** [review]
Looks good, thank you @jgarcialr!

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
