### PR TITLE
LPS-163845 Send email to invited user

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:account

**Comment by melodywu** [comment]
ci:test:bundle

**Comment by melodywu** [comment]
Hello @pei-jung 
Could you please help with double checking if the [modules-semantic-versioning-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/2009994721?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2009994581%26testrayRunId%3D2009994636%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) failure related? Refer the full [jenkins console](https://testray.liferay.com/reports/production/logs/2022-10/test-1-32/test-portal-acceptance-pullrequest(master)/6258/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0). Thanks in advance.

```
[exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/account/account-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.account.service                        MINOR      7.5.0      7.5.0      7.6.0      VERSION INCREASE REQUIRED
     [exec]     	<   class      com.liferay.account.service.AccountEntryUserRelLocalServiceUtil
     [exec]     		+   method     inviteUser(com.liferay.account.model.AccountEntry,long[],java.lang.String,com.liferay.portal.kernel.model.User,com.liferay.portal.kernel.service.ServiceContext)
     [exec]     			+   access     static
     [exec]     			+   return     void
     [exec]     	<   class      com.liferay.account.service.AccountEntryUserRelLocalServiceWrapper
     [exec]     		+   method     inviteUser(com.liferay.account.model.AccountEntry,long[],java.lang.String,com.liferay.portal.kernel.model.User,com.liferay.portal.kernel.service.ServiceContext)
     [exec]     			+   return     void
     [exec]     	<   interface  com.liferay.account.service.AccountEntryUserRelLocalService
     [exec]     		+   method     inviteUser(com.liferay.account.model.AccountEntry,long[],java.lang.String,com.liferay.portal.kernel.model.User,com.liferay.portal.kernel.service.ServiceContext)
     [exec]     			+   access     abstract
     [exec]     			+   return     void
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 12.4.0
     [exec]         at org.junit.Assert.fail(Assert.java:88)
     [exec]         at org.junit.Assert.assertTrue(Assert.java:41)
     [exec]         at org.junit.Assert.assertFalse(Assert.java:64)
     [exec]         at com.liferay.semantic.versioning.SemanticVersioningTest.testSemanticVersioning(S

```

**Comment by patriciajeanperez** [comment]
Will push test fixes and re-run the Accounts tests after review @pei-jung @drewbrokke

**Comment by melodywu** [comment]
Hello @pei-jung There is a issue when assign user for account role. 
**Steps：**
1. Add new user
2. Add new account
3. Go to account -> Click role tab -> Add a new role
4. Go to new role -> Click Assignees tab ----> Click "+" button
Actual behavior
Can not add new user.
Sorry for the issue find delay. Thanks in advance.

**Comment by melodywu** [comment]
> Will push test fixes and re-run the Accounts tests after review @pei-jung @drewbrokke

before2 (1)

**Comment by pei-jung** [comment]
Resent as https://github.com/liferay-usm/liferay-portal/pull/798

**Pull request closed without merging**
