### PR TITLE
LPS-139430 As an Administrator, I want to assign a User to Accounts

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-139430](https://issues.liferay.com/browse/LPS-139430).<br/><br/>/cc @pei-jung @alee8888 @ChrisKian @patriciajeanperez @lr-leo @erickmonteiroo

### CODE REVIEW

**Comment by drewbrokke** [comment]
@pei-jung the last few commits add changes to the AccountEntry indexer that allow excluding Person Accounts that already have a user assigned. That way we don't have to deal with any enable/disable logic for those accounts in the selection modals.

FYI @epark18

**Comment by patriciajeanperez** [comment]
ci:test:account

**Comment by patriciajeanperez** [comment]
ci:test:bundle

**Comment by drewbrokke** [comment]
See https://github.com/liferay-usm/liferay-portal/pull/440 for the JSP failure fix.

**Pull request closed without merging**
