### PR TITLE
LPS-167693 Remove redundant usages of the method getSearchActionURL from depot-web

### PR DESCRIPTION
**Pull request by gislayne-vitorino**
This is an update for [subtask: LPS-167693](https://issues.liferay.com/browse/LPS-167693), [LPS-161233](https://issues.liferay.com/browse/LPS-161233)

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
ci:test:depot

**Comment by melodywu** [comment]
No related failure found in ci:test:relevant.

**Comment by patriciajeanperez** [comment]
ci:test:stable

**Comment by patriciajeanperez** [comment]
ci:stop

**Comment by patriciajeanperez** [comment]
ci:forward

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
