### PR TITLE
LPS-175187 Add endpoints to update user profile pic

### PR DESCRIPTION
**Pull request by gislayne-vitorino**
This is an update for: [LPS-175187](https://issues.liferay.com/browse/LPS-175187)

### CODE REVIEW

**Review by pei-jung — APPROVED** [review]
LGTM! Thanks @gislayne-vitorino @drewbrokke!

**Comment by drewbrokke** [comment]
@gislayne-vitorino looks like a compile error on this one. Can you please check it?

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
@gislayne-vitorino no related failures, just a version increase required for `com.liferay.headless.admin.user.resource.v1_0.UserAccountResource`

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:reevaluate:1297401_6524

**Comment by drewbrokke** [comment]
@gislayne-vitorino looks like some diffs in the RestBuilder output. Try updating your local branch and re-running rest builder.

**Comment by drewbrokke** [comment]
See https://github.com/liferay-usm/liferay-portal/pull/999

**Pull request closed without merging**
