### PR TITLE
LPS-168768 Roles don't use h# tags in search container descriptive view

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-168768

This updates the markup to use `div` instead of `h#` tags. I updated the classes to follow Clay's hierarchy for text in list-group. It changed the color of the 2nd line text to `$gray-900` from `$secondary`. I need to check with Lexicon to see if this is correct. It doesn't look like it from https://liferay.design/lexicon/core-components/List/. We will update it in Clay and it will update when Clay is updated.

roles-admin

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
ci:test:roles

**Comment by patriciajeanperez** [comment]
No regressions, but a test fix is needed. I can send another PR with the fix after your guys' review. Thanks! @drewbrokke @pei-jung

**Review by drewbrokke — CHANGES_REQUESTED** [review]
Hey @pat270 looks good, but I think you've got the wrong ticket number in the commit. Can you please double-check that? Thanks!

**Comment by pat270** [comment]
@drewbrokke just updated the commit message, thanks for the catch.

**Review by drewbrokke — APPROVED** [review]
Looks good, thanks @pat270!

**Comment by drewbrokke** [comment]
@patriciajeanperez we're good to go when you are.

**Comment by patriciajeanperez** [comment]
See https://github.com/liferay-usm/liferay-portal/pull/958

**Pull request closed without merging**
