### PR TITLE
LPS-156788 As a Sales Admin, I would like to view and modify the External Reference Code with the UI

### PR DESCRIPTION
**Pull request by RafaelCRC**

### CODE REVIEW

**Review by drewbrokke — CHANGES_REQUESTED** [review]
@RafaelCRC nice work. Just the one suggestion, but other than that it's good to go.

**Comment by RafaelCRC** [comment]
ci:stop

**Comment by RafaelCRC** [comment]
Should be good to go now @drewbrokke

**Comment by epark18** [comment]
Failures are unrelated here.

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
@epark18 if the failures are unrelated, this one should be good to go.

**Comment by epark18** [comment]
Pushed to Brian. https://github.com/brianchandotcom/liferay-portal/pull/120650.

**Pull request closed without merging**
