### PR TITLE
LPS-149125 As an admin, I want to add regular Users to Accounts

### PR DESCRIPTION
**Pull request by epark18**
https://issues.liferay.com/browse/LPS-149125

Resend from [liferay-usm#508](https://github.com/liferay-usm/liferay-portal/pull/508) with test fixes added.

cc/ @pei-jung, @drewbrokke, @sharryxue

### CODE REVIEW

**Comment by epark18** [comment]
ci:test:account

**Comment by epark18** [comment]
ci:test:relevant

**Comment by epark18** [comment]
Tests will need to be rerun. There is currently an issue with CI that is preventing some tests from being triggered.

**Comment by epark18** [comment]
ci:test:relevant

**Comment by epark18** [comment]
ci:test:account

**Comment by epark18** [comment]
ci:test:account

**Comment by epark18** [comment]
Failure is unrelated to the changes.

**Comment by drewbrokke** [comment]
@epark18 in your opinion, is this one good to go?

**Comment by epark18** [comment]
@drewbrokke yes! Looks good to me.

**Comment by drewbrokke** [comment]
Thanks @epark18 !

**Pull request closed without merging**
