### PR TITLE
[TS] LPS-134096

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-134096

Resent from https://github.com/liferay-usm/liferay-portal/pull/107 with refactoring done.  Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by drewbrokke** [comment]
@ChrisKian looks like a semver failure. Can you please rebase and force-push?

**Review by drewbrokke — APPROVED** [review]
@ChrisKian LGTM! 👍

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
The failure not related to the commits, the failed POSHI test is more like due to CI server issue.

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
No related failure found.

**Comment by drewbrokke** [comment]
@Sharryxue if you have found no unique failures, then it should be safe to forward manually.

**Comment by Sharryxue** [comment]
Manually forward the commits [brianchandotcom/liferay-portal#103881](https://github.com/brianchandotcom/liferay-portal/pull/103881).

**Pull request closed without merging**
