### PR TITLE
LPS-165685 Rename the column OrgLabor

### PR DESCRIPTION
**Pull request by gislayne-vitorino**

### CODE REVIEW

**Comment by gislayne-vitorino** [comment]
ci:stop

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:test:users

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by melodywu** [comment]
> ci:test:relevant

For the testcases "Aborted prior to running test" failure cause build time out. Then run ci:test:relevant again.

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
@gislayne-vitorino looks like there's a merge conflict on this pull. Please fix and force-push.

**Comment by gislayne-vitorino** [comment]
ci:stop

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
Issues not related.

**Review by drewbrokke — CHANGES_REQUESTED** [review]
@gislayne-vitorino I think the failure in `directory-web` is real. Please double-check this jsp in that module: `src/main/resources/META-INF/resources/organization/services.jsp`.

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:reevaluate:1277401_5581

**Comment by patriciajeanperez** [comment]
No relevant failures. Is this pull good to go? @drewbrokke

**Review by drewbrokke — APPROVED** [review]
LGTM 👍

**Comment by drewbrokke** [comment]
@patriciajeanperez good to go

**Comment by patriciajeanperez** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/125411

**Pull request closed without merging**
