### PR TITLE
LPS-158690

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LPS-158690

@drewbrokke @pei-jung, follow-up pull from https://github.com/liferay-usm/liferay-portal/pull/742 (this time, w/o the Language.properties file copies).  Let me know if there's anything else I should change.  Thanks!

cc @Sharryxue

### CODE REVIEW

**Comment by Sharryxue** [comment]
No related issue found in ci:test:relevant.

**Review by drewbrokke — APPROVED** [review]
Looks good @brianwulbern!

**Comment by drewbrokke** [comment]
@patriciajeanperez we're good to go here.

**Comment by patriciajeanperez** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/123770

**Pull request closed without merging**
