### PR TITLE
LPS-169651 After add Duplicate External Reference Codes accounts there isn' error message

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-169651](https://issues.liferay.com/browse/LPS-169651).<br/><br/>/cc @pei-jung @ChrisKian @patriciajeanperez @david-truong @gislayne-vitorino

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test:bundle

**Comment by melodywu** [comment]
Hello @drewbrokke, There is a related failure found in ci:test:relevant result, [modules-semantic-versioning-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/2116108399?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2116091626%26testrayRunId%3D2116099527%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)
```
 [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/dxp/apps/search-experiences/search-experiences-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.search.experiences.exception           MAJOR      4.0.0      4.0.0      5.0.0      VERSION INCREASE REQUIRED
     [exec]     	>   class      com.liferay.search.experiences.exception.DuplicateSXPBlueprintExternalReferenceCodeException
     [exec]     		+   extends    com.liferay.portal.kernel.exception.DuplicateExternalReferenceCodeException
     [exec]     		-   extends    com.liferay.portal.kernel.exception.SystemException
     [exec]     	>   class      com.liferay.search.experiences.exception.DuplicateSXPElementExternalReferenceCodeException
     [exec]     		+   extends    com.liferay.portal.kernel.exception.DuplicateExternalReferenceCodeException
     [exec]     		-   extends    com.liferay.portal.kernel.exception.SystemException
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 20.0.0
     [exec]         at org.junit.Assert.fail(Assert.java:88)
     [exec]         at org.junit.Assert.assertTrue(Assert.java:41)
     [exec]         at org.junit.Assert.assertFalse(Assert.java:64)
     [exec]         at com.liferay.semantic.versioning.SemanticVersioni
```
Could you help with confirm [@RafaelCRC](https://github.com/RafaelCRC)? Thanks in advance.

**Comment by drewbrokke** [comment]
Thanks @melodywu, I'll take care of it.

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Review by pei-jung — APPROVED** [review]
LGTM!

**Comment by drewbrokke** [comment]
ci:reevaluate:1307401_5714

**Comment by melodywu** [comment]
Hi @pei-jung, No related issue found in ci:test:relevant.

**Comment by drewbrokke** [comment]
@melodywu if this one seems good to you, then we can manually forward.

**Pull request closed without merging**
