### PR TITLE
LPS-164299 NPE in AddressUtilTest

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-164299](https://issues.liferay.com/browse/LPS-164299).<br/><br/>/cc @pei-jung @ChrisKian @patriciajeanperez @david-truong @gislayne-vitorino @RafaelCRC

### CODE REVIEW

**Review by pei-jung — APPROVED** [review]

**Comment by pei-jung** [comment]
@patriciajeanperez are the test failures related?

**Comment by patriciajeanperez** [comment]
Hi @pei-jung, I see the same failures in [com.liferay.text.localizer.taglib.internal.address.*](https://testray.liferay.com/reports/production/logs/2022-09/test-1-34/test-portal-acceptance-pullrequest(master)/2898/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0). Can you help me check if they are related or if it would be better to create a new ticket? Thank you!

**Comment by pei-jung** [comment]
Thanks for checking @patriciajeanperez! The failures look related. We'll look into it.

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
