### PR TITLE
LPS-173475 SqlExceptionHelper getting ORA-01795 during and after startup w/ Oracle

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-173475](https://issues.liferay.com/browse/LPS-173475).<br/><br/>/cc @pei-jung @ChrisKian @patriciajeanperez @david-truong @gislayne-vitorino

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:environments

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Review by pei-jung — APPROVED** [review]
LGTM!

**Comment by patriciajeanperez** [comment]
No related failures in relevant and environments. `ci:test:environments` currently does not run on SQL Server so I ran them here: https://github.com/patriciajeanperez/liferay-portal/pull/732. No related failures.

**Comment by patriciajeanperez** [comment]
ci:test:roles

**Comment by patriciajeanperez** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/129151

**Pull request closed without merging**
