### PR TITLE
LPS-150977 Filter by name in getAccountUserAccountsByExternalReferenceCode

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by melodywu** [comment]
Hi @pei-jung , After we analysis The failure [com.liferay.headless.admin.user.resource.v1_0.test.UserAccountResourceTest](https://testray.liferay.com/home/-/testray/case_results/1657229838?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1657229670%26testrayRunId%3D1657229752%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) maybe related with the commits. Could you take a look at it? Thanks a lot

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
