### PR TITLE
LPS-127473 Bridge Commerce's Address with Portal's Address

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-127473](https://issues.liferay.com/browse/LPS-127473).<br/><br/>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:commerce

**Comment by drewbrokke** [comment]
@patriciajeanperez are these commerce failures unique?

**Comment by patriciajeanperez** [comment]
Hi @drewbrokke, finished analysis and found no unique failures :)

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
