### PR TITLE
LPS-133510 Exporting factory configurations in System Settings UI result in a file name ending with -default.config

### PR DESCRIPTION
**Pull request by erickmonteiroo**

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
@erickmonteiroo looks like there's a couple of test cases than need updated assertions.

**Comment by erickmonteiroo** [comment]
> @erickmonteiroo looks like there's a couple of test cases than need updated assertions.

@drewbrokke I will be sending the update later. Thanks!

**Comment by erickmonteiroo** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
