### PR TITLE
[TS] LPS-147496

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-147496

CC @liferay-appsec since we are no longer escaping a value.  In my testing, the user.getFullName() value was already escaped once, and setting the first name to something like "`<script type="text/javascript"> alert("hello！"); </script>`" like in [LPS-60560](https://issues.liferay.com/browse/LPS-60560) did not reproduce the XSS issue.

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by Sharryxue** [comment]
The unique failure probably fluky, will retrigger the relevant tests.

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by epark18** [comment]
Failures from CI are not related to PR :]

**Comment by stian-sigvartsen** [comment]
The auto escaping behavior is enabled via the search container btw. So when Cards are used to render within that context, it should honor that setting really. 

```
<liferay-ui:search-container-row
	className="com.liferay.portal.kernel.model.User"
	escapedModel="<%= true %>"
	keyProperty="userId"
	modelVar="user2"
	rowIdProperty="screenName"
>
```

**Review by drewbrokke — APPROVED** [review]
@ChrisKian the change looks good on our end. Thanks!

**Comment by drewbrokke** [comment]
@stian-sigvartsen it also seems possible that since the name is rendered via a React component, the output will be escaped in any case. I've not played with this but I did find these docs: https://reactjs.org/docs/introducing-jsx.html#jsx-prevents-injection-attacks. Thoughts?

**Comment by stian-sigvartsen** [comment]
@drewbrokke that looks very plausible! I lack the experience with React to say for sure, but maybe someone from the frontend team should explore this.

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by epark18** [comment]
The automation test failures do not seem to be related, but I am double checking here https://github.com/epark18/liferay-portal/pull/4. Other than that there is an error in semantic versioning | [Error Logs](https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=24/36531//consoleText)
`     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.portal.servlet                         MAJOR      7.0.0      7.0.0      8.0.0      VERSION INCREASE REQUIRED
     [exec] 	-   class      com.liferay.portal.servlet.ThreadLocalFacadeHttpServletRequestWrapper
     [exec] 		-   extends    com.liferay.portal.kernel.servlet.PersistentHttpServletRequestWrapper
     [exec] 		-   implements java.io.Closeable
     [exec] 		-   method     <init>(javax.servlet.ServletRequestWrapper,javax.servlet.http.HttpServletRequest)
     [exec] 			-   return     void
     [exec] 		-   method     clone()
     [exec] 			-   access     protected
     [exec] 			-   return     java.lang.Object`

**Comment by ChrisKian** [comment]
The SemVer issue isn't related to this specific change.  The error is saying the major version needs to increase due to an API change in the `ThreadLocalFacadeHttpServletRequest*` classes, however my change doesn't modify that class, use it, or modify API in any way.

**Comment by drewbrokke** [comment]
@epark18 seems ok to forward to me.

**Comment by epark18** [comment]
Thank you guys! 
Pushed to BChan at https://github.com/brianchandotcom/liferay-portal/pull/113986

**Comment by epark18** [comment]
ci:close

**Comment by ChrisKian** [comment]
Followup PR: https://github.com/liferay-usm/liferay-portal/pull/471

**Pull request closed without merging**
