### PR TITLE
LPS-151425 Remove deprecated methods in account modules

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by drewbrokke** [comment]
@pei-jung can you please resend this one? Looks like a rebase error.

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by epark18** [comment]
Hi @pei-jung, the only issue is the SemVer error in account.service.
```     [exec] > Task :apps:account:account-api:baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec]   com.liferay.account.service                        UNCHANGED  7.0.0      6.1.0      6.1.0      EXCESSIVE VERSION INCREASE
     [exec] 	-   version    6.1.0
     [exec] 	+   version    7.0.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/tools/sdk/dist/com.liferay.account.api-9.0.0.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay/com.liferay.account.api/8.2.0/a05031dfd2983ce129b288eda33a0b230d2e5884/com.liferay.account.api-8.2.0.jar```

**Comment by epark18** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
Hi @epark18, any update on this?

**Comment by epark18** [comment]
Hi @pei-jung I am currently still looking into it, and running some different potential solutions locally. I will reach out to the appropriate team to get a more conclusive solution today. Sorry for the delay!

**Comment by Sharryxue** [comment]
Hello @pei-jung,
By waiting the investigate result from Eric, based on the [article](https://liferay.atlassian.net/wiki/spaces/ENGCOREUPGRADE/pages/1997637391/Pull+Request+Review+Guidelines), seems the related jar need remove as well, not sure if the way described in the article can fix the issue. Both Eric and I tried the command locally under portal-impl but failed due to compile issue.
BTW, I had try to increase the version in [modules/modules.properties](https://github.com/Sharryxue/liferay-portal/pull/385/commits/d4e727bc25117a07bd24e38a847732c204502e53#diff-c32f67e0571aa37798907caec54f5c8426939405a87c5ac3fc21f5ac6f23d1be), and it run into the same semantic versioning issue.

> Check semantic versioning
> 
> If the ci:test:relevant tests fail, check if the semantic versioning was the reason for the fail, if so run ant -Dbaseline.jar.report.level=persist clean jar for portal-impl upgrade changes, and gradlew baseline for module changes.

**Pull request closed without merging**
