### PR TITLE
LPS-146998 Assertion error at com.liferay.headless.admin.user.resource.v1_0.test.AccountResourceTest.testPostAccount

### PR DESCRIPTION
**Pull request by erickmonteiroo**
This is a follow up PR for [LPS-146998](https://issues.liferay.com/browse/LPS-146998).
See [Brian's comment](https://github.com/brianchandotcom/liferay-portal/commit/abab4e772512c90dbcefb00e2bf282593b54ff76).

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:stop

Stopping and restarting due to ci-infrastructure bug

**Comment by pyoo47** [comment]
ci:test:relevant

**Review by drewbrokke — CHANGES_REQUESTED** [review]
@erickmonteiroo this is the right fix, but will you please change `"DuplicateAccountEntryExternalReferenceCodeException"` to `DuplicateAccountEntryExternalReferenceCodeException.class.getSimpleName()`? That way we get type safety and guard against typos.

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
ci:forward

**Comment by erickmonteiroo** [comment]
ci:forward

**Comment by drewbrokke** [comment]
ci:forward

**Comment by epark18** [comment]
Test failure is unrelated. Would you like me to manually forward?

**Comment by erickmonteiroo** [comment]
@epark18 Sure! Thank you!! 😄

**Comment by epark18** [comment]
Pushed to BChan. 
[#113528](https://github.com/brianchandotcom/liferay-portal/pull/113528)

**Comment by epark18** [comment]
ci:close

**Pull request closed without merging**
