### PR TITLE
LPS-163648

### PR DESCRIPTION
**Pull request by natocesarrego**
Hi,

Basically, this pull introduces a new entry in Instance Settings to allow the user configure the default portlet decorator. This is a demand from a customer in pure LXC. Perhaps, @liferay-core-infra, would like to take a look on this pull since it manipulates the usage of the portal property `default.portlet.decorator.id`.

Thanks in advance for your review! :smile: 

Jira ticket: https://issues.liferay.com/browse/LPS-163648

### CODE REVIEW

**Review by drewbrokke — APPROVED** [review]
Thanks @natocesarrego!

**Comment by drewbrokke** [comment]
ci:forward

**Comment by melodywu** [comment]
No related issue found in ci:test:relevant.

**Comment by natocesarrego** [comment]
Thanks, @drewbrokke and @melodywu! I'll manually forward this pull to Brian. :slightly_smiling_face:

**Comment by natocesarrego** [comment]
Manually forwarded to Brian: https://github.com/brianchandotcom/liferay-portal/pull/126854

**Pull request closed without merging**
