### PR TITLE
LPS-166843 Privilege escalation using role permission permission

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-166843](https://issues.liferay.com/browse/LPS-166843).<br/><br/>/cc @pei-jung @ChrisKian @patriciajeanperez @david-truong @gislayne-vitorino

### CODE REVIEW

**Comment by melodywu** [comment]
No related issue found in ci:test:relevant.

**Review by pei-jung — APPROVED** [review]
LGTM!

**Comment by drewbrokke** [comment]
@melodywu @Sharryxue if this looks good to you, we are ready to forward.

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
