### PR TITLE
LPS-154609 Remove OrgGroupRole model and services

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by Sharryxue** [comment]
ci:test:upgrade-all

**Review by drewbrokke — APPROVED** [review]
LGTM 👍

**Review by drewbrokke — CHANGES_REQUESTED** [review]
Just the versioning failures.

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:upgrade-all

**Comment by drewbrokke** [comment]
@Sharryxue any issues with the upgrade failures?

**Comment by Sharryxue** [comment]
No related failure found.

**Comment by drewbrokke** [comment]
Thanks @Sharryxue!

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
