### PR TITLE
[SUPPORT] LPS 154503

### PR DESCRIPTION
**Pull request by JavierMoral**
Hi team,
this pull fixes [LPS-154503](https://issues.liferay.com/browse/LPS-154503). It extends the search made from roles administration to also search by titles. Right now, only the name (key) and description fields were being considered in searches.
Could you please take a look at it?
Thanks!

### CODE REVIEW

**Comment by JavierMoral** [comment]
ci:test:relevant

**Comment by JavierMoral** [comment]
ci:test:relevant

**Review by drewbrokke — APPROVED** [review]
Looks good, thanks @JavierMoral!

**Comment by drewbrokke** [comment]
ci:forward

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
ci:stop

**Comment by Sharryxue** [comment]
The semantic-versioning issue should be fixed by [commit](https://github.com/brianchandotcom/liferay-portal/commit/42238ff2e2dbd5526373d512a83898729f51aaa0). Will manually forward the commits here.

**Comment by Sharryxue** [comment]
Manually forwarded the pr [brianchandotcom/liferay-portal#118127](https://github.com/brianchandotcom/liferay-portal/pull/118127).

**Comment by epark18** [comment]
ci:close

**Pull request closed without merging**
