### PR TITLE
LPS-165028 Creates new vertical card for users

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
=======
In order to stop using old frontend taglib replace the usages on user group of frontend vertical cards and replace with clay card

[LPS-165028](https://issues.liferay.com/browse/LPS-165028)

Proposed Solution
========
Creates new vertical card for users and replace the usages on jsps

----------

**NOTE** Right now the UI change a little bit since it is not possible to show the icon as a single Icon and after the changes it is showing a dropdown with the action.

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:test:users

**Comment by Sharryxue** [comment]
No related failure found in ci:test:users.

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
