### PR TITLE
LPS-155383 Fix upgrade

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:upgrade-all

**Comment by epark18** [comment]
@sharryxue will need help manually testing and analyzing results for this PR. Updates should go in this [Slack Thread](https://liferay.slack.com/archives/CLA7D1CNL/p1654638464031109).
BChan is already publishing this fix, so we don't need to forward this PR after analysis. 

[LPS-155383](https://issues.liferay.com/browse/LPS-155383?focusedCommentId=2697156&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2697156)

**Comment by Sharryxue** [comment]
ci:test:bundle

**Comment by epark18** [comment]
ci:test:security

**Comment by epark18** [comment]
Results look good. The UpgradeCountryCode error is no longer present in any of the linked tests.
[MultiFactorAuthenticationUpgrade#ViewMFAConfigurationInInstanceLevelAfterUpgrade7310](https://testray.liferay.com/home/-/testray/case_results/1871721631)
[OAuth2Upgrade#ViewOAuth2ApplicationInInstanceLevelAfterUpgrade72101](https://testray.liferay.com/home/-/testray/case_results/1871721672)
[OAuth2Upgrade#ViewOAuth2ApplicationInInstanceLevelAfterUpgrade720](https://testray.liferay.com/home/-/testray/case_results/1871721686)
[OAuth2Upgrade#ViewOAuth2ApplicationInInstanceLevelAfterUpgrade713
](https://testray.liferay.com/home/-/testray/case_results/1871721681)[OAuth2Upgrade#ViewOAuth2ApplicationInInstanceLevelAfterUpgrade71103
](https://testray.liferay.com/home/-/testray/case_results/1871721694)

Thank you again @pei-jung!!

**Comment by Sharryxue** [comment]
Manually tested this with the related dump from [MultiFactorAuthenticationUpgrade#ViewMFAConfigurationInInstanceLevelAfterUpgrade7310](https://testray.liferay.com/home/-/testray/case_results/1871721631) on both mysql/DB2, UpgradeCountryCode process completed without any error as expected.

**Comment by drewbrokke** [comment]
@epark18 do we need to keep this pull open?

**Comment by epark18** [comment]
ci:close

**Pull request closed without merging**
