### PR TITLE
LPS-138929 Number of Account Roles is not accurate with the pagination set

### PR DESCRIPTION
**Pull request by erickmonteiroo**
@pei-jung @drewbrokke see Brian's [comment.](https://github.com/brianchandotcom/liferay-portal/pull/107917#issuecomment-929636649)

### CODE REVIEW

**Comment by erickmonteiroo** [comment]
ci:stop

**Comment by erickmonteiroo** [comment]
ci:test:sf

**Comment by erickmonteiroo** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:test:account

**Comment by patriciajeanperez** [comment]
No failures in account

**Comment by erickmonteiroo** [comment]
ci:test:sf

**Comment by erickmonteiroo** [comment]
ci:test:relevant

**Pull request closed without merging**
