### PR TITLE
Lps 143575

### PR DESCRIPTION
**Pull request by amosfong**
@drewbrokke FYI

I only regenerated accounts for now, also I did not add any upgrade classes. If it looks good, then I can regenerate everything

### CODE REVIEW

**Comment by drewbrokke** [comment]
@amosfong I'm not seeing any changes to `account-service/service.xml` file. Was that intentionally omitted?

**Comment by amosfong** [comment]
@drewbrokke, that is taken care of by servicebuilder change

**Comment by drewbrokke** [comment]
@amosfong looks good, let's go for it.

**Comment by amosfong** [comment]
ci:test

**Pull request closed without merging**
