### PR TITLE
LPS-169971 Add help text for Email Address and Roles fields

### PR DESCRIPTION
**Pull request by pei-jung**
Screen Shot 2022-11-30 at 2 08 30 PM

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:account

**Comment by melodywu** [comment]
No related issue found in ci:test:relevant and ci:test:account

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
ci:forward

**Comment by Sharryxue** [comment]
Will manually forward the commit.

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:forward

**Pull request closed without merging**
