### PR TITLE
LPS-156573 As a user I'd like to have Commerce's MANAGE_AVAILABLE_ACCOUNTS permission available in portal

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-156573](https://issues.liferay.com/browse/LPS-156573).

/cc @pei-jung @ChrisKian @patriciajeanperez @epark18 @david-truong @gislayne-vitorino @RafaelCRC

~I did not have a chance to test this via the UI yet (no time today, I'll do it first thing tomorrow), but the integration tests should give a good idea of what's expected.~

It seems to work well in the UI.

@luca-pellizzon will you (or one of your team members) please take a look at these changes and let me know if I'm missing something or have anything incorrect? Thanks!

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
Looks fine to me, but the real test will be when we'll fully use AccountEntry's services ecc, now everything should work because we are still using commerce stuff.

**Comment by drewbrokke** [comment]
Two new scenarios that need addressing before this is ready:

- [ ] The permission needs to apply to search results as well.
- [ ] The permission needs to grant permissions to accounts linked to sub-organizations

**Comment by drewbrokke** [comment]
@luca-pellizzon is there any kind of a test run that your team can perform to validate this?

**Comment by luca-pellizzon** [comment]
@drewbrokke we have the commerce tests suite "ci:test:commerce".
It's broken at the moment because of a wrong commit, but will be fixed soon.

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
ci:test:bundle

**Comment by drewbrokke** [comment]
@epark18 are the `relevant` failures...relevant?

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by epark18** [comment]
@drewbrokke The former relevant results look good to me. I'll do a final comparison with the new run when the tests finish.

**Comment by epark18** [comment]
ci:test:relevant

**Review by pei-jung — APPROVED** [review]
LGTM!

**Comment by epark18** [comment]
ci:stop

**Comment by drewbrokke** [comment]
Superseded by https://github.com/liferay-usm/liferay-portal/pull/674.

**Comment by drewbrokke** [comment]
ci:stop

**Pull request closed without merging**
