### PR TITLE
LPS-137813 Patch in User APIs remove the profile picture

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-137813](https://issues.liferay.com/browse/LPS-137813).<br/><br/>/cc @pei-jung @alee8888 @ChrisKian @patriciajeanperez @lr-leo @erickmonteiroo

### CODE REVIEW

**Comment by epark18** [comment]
Failures in ci are unrelated to the pull :]

**Comment by drewbrokke** [comment]
ci:test:relevant

**Review by pei-jung — CHANGES_REQUESTED** [review]
Changes look good. However, the ticket number in the commit messages is wrong.

**Comment by drewbrokke** [comment]
> Changes look good. However, the ticket number in the commit messages is wrong.

Oh good catch! I'll fix it and force-push

**Comment by drewbrokke** [comment]
See https://github.com/liferay-usm/liferay-portal/pull/407

**Pull request closed without merging**
