### PR TITLE
LPS-167294 Rename "Account Entry" to "Account" in the UI

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-167294](https://issues.liferay.com/browse/LPS-167294).

Screen Shot 2022-11-02 at 1 05 53 PM

Screen Shot 2022-11-02 at 1 06 35 PM

@david-truong There is a piece of the workflow instance screen that we do not have control over. It will always render the name based on the java resource name:

Screen Shot 2022-11-02 at 1 02 08 PM

/cc @pei-jung

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:account

**Comment by melodywu** [comment]
No related failure found in ci:test:account.

**Comment by drewbrokke** [comment]
@pei-jung any objections to forwarding this one?

**Review by pei-jung — APPROVED** [review]
LGTM!

**Comment by pei-jung** [comment]
ci:forward

**Pull request closed without merging**
