### PR TITLE
LPS-166677 Merge override language item displays with all language item displays list

### PR DESCRIPTION
**Pull request by MirnaGama**
**Bug found:** Custom language keys are not appearing in the list after creation.
Please check: https://issues.liferay.com/browse/LPS-166677

### CODE REVIEW

**Comment by MirnaGama** [comment]
ci:test:sf

**Comment by MirnaGama** [comment]
ci:test:relevant

**Comment by MirnaGama** [comment]
Hi @drewbrokke . Currently, the first state (no filter) only shows the default language keys from the portal. 
The other states ("Any Language" and "Selected Language") only shows the overriden language keys. 

The customer is reporting that new custom languages ​​are not showing up unless they select a filter, but when doing that the default language keys do not appear.

The solution was to treat "Any Language" and No Filter state as if they were the same from the user's point of view, as the default language keys also contain any language.

Let me know if further information or any code change is required.

Thanks

**Comment by drewbrokke** [comment]
@MirnaGama I double-checked just now, and the "No filter" state shows both default language keys and overridden keys:

Screen Shot 2022-10-26 at 12 11 11 PM

You can also test this in the "No Filter" state by searching for the new key using the search bar.

Would you be willing to verify this? I apologize if I am misunderstanding the situation.

**Comment by MirnaGama** [comment]
@drewbrokke Yes, it is

**Comment by drewbrokke** [comment]
@MirnaGama thank you for confirming. Following those steps, I am still able to see the created key in the unfiltered view.
Screen Shot 2022-10-26 at 1 08 26 PM

Anything else I can try?

**Comment by drewbrokke** [comment]
@MirnaGama sure thing, please use the email address found in my Slack profile.

**Comment by MirnaGama** [comment]
@drewbrokke 

_Additional remarks:_

The dump restores 3 databases:

- lportal - principal instance (admin-i2d8.lxc.liferay.com)
- lpartition_42323 - vale.lxc.liferay.com
- lpartition_44549 -  vale-uat.lxc.liferay.com

The issue was reported in the UAT environment. The users for instance UAT are located in table user_  inside db lpartition_44549. I used a query to change the values of their passwords. 

Let me know if you need any other information.

**Comment by drewbrokke** [comment]
Thanks @MirnaGama. I have the database, but I won't be able to analyze this right away, so at this point my response is this:

- We should maintain the three filter states.
- If the "unfiltered" state is not showing overridden or new keys, we need to debug and figure out why it is not returning them. My suggestion would be to put a breakpoint in [ViewDisplayContextFactory.java#L171](https://github.com/liferay-usm/liferay-portal/blob/master/modules/apps/portal-language/portal-language-override-web/src/main/java/com/liferay/portal/language/override/web/internal/display/context/ViewDisplayContextFactory.java?plain=1#L171) and inspect the `keyPLOEntriesMap` variable. It _should_ contain the created keys. If it does not, we have an issue with the database/service layer. If it does, we need to verify the logic that uses the map to construct the results.

I'm going to close the PR for now, but feel free to ping me if you need any additional info. Thanks!

**Comment by MirnaGama** [comment]
Resent: https://github.com/liferay-usm/liferay-portal/pull/862

**Pull request closed without merging**
