### PR TITLE
LPS-138614 Pagination does not work in the Account Groups tab

### PR DESCRIPTION
**Pull request by erickmonteiroo**

### CODE REVIEW

**Comment by erickmonteiroo** [comment]
ci:test:sf

**Comment by erickmonteiroo** [comment]
ci:test:relevant

**Review by pei-jung — APPROVED** [review]

**Comment by pei-jung** [comment]
ci:reevaluate:1327401_191

**Comment by pei-jung** [comment]
@patriciajeanperez are the failures related?

**Comment by patriciajeanperez** [comment]
Hi @pei-jung, the failure is not related. I'll be manually forwarding this pr.

**Comment by patriciajeanperez** [comment]
Pushed to BChan.
brianchandotcom#106867

**Comment by patriciajeanperez** [comment]
ci:close

**Pull request closed without merging**
