### PR TITLE
LPS-111992 Increment the Marketplace plugin CLIENT_BUILD version

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-111992](https://issues.liferay.com/browse/LPS-111992).<br/><br/>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez @lionah

### CODE REVIEW

**Comment by Sharryxue** [comment]
The semantic versionings have updated since then, will retrigger the ci:test:relevant test.

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:forward

**Comment by Sharryxue** [comment]
The failed test not related, will manually forward the commits.

**Comment by Sharryxue** [comment]
Manually forward the commits [brianchandotcom/liferay-portal#103881](https://github.com/brianchandotcom/liferay-portal/pull/103881).

**Pull request closed without merging**
