### PR TITLE
LRQA-71764 Fix OnDemandAdminPermissionCheckerWrapperTest

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
Failures are unrelated

**Comment by pei-jung** [comment]
@patriciajeanperez is this safe to forward?

**Comment by drewbrokke** [comment]
ci:reevaluate:1127401_5120

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
@epark18 would you be willing to manually forward this one also? Thanks!

**Comment by epark18** [comment]
Pushed to Bchan.
[110220](https://github.com/brianchandotcom/liferay-portal/pull/110220)

**Comment by epark18** [comment]
ci:close

**Pull request closed without merging**
