### PR TITLE
LPS-143444 UI Bug - Active displays lengthways on the page

### PR DESCRIPTION
**Pull request by erickmonteiroo**

### CODE REVIEW

**Comment by erickmonteiroo** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:reevaluate:1347401_377

**Comment by epark18** [comment]
@erickmonteiroo CI failure is likely a fluke based on the changes made to the file, but rerunning the CI checks will probably fail due to a [regression bug](https://issues.liferay.com/browse/LPS-143439). Can possibly manually forward if needed

**Review by drewbrokke — COMMENTED** [review]
This issue seems to be widespread in portal. I think a fix inside of `aui:input` is needed. I've sent a message to the frontend infra team giving a couple of examples.

**Pull request closed without merging**
