### PR TITLE
LPS-168532 User Profile and Dashboard links should announce more descriptive text on screen readers

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-168532

I updated the links to recently changed Lexicon styles (for accessibility) in https://github.com/liferay/clay/issues/5283. I also changed the text from "Open Pages" to "My Profile" and "My Dashboard". I thought it would be more descriptive, let me know if I should change it back.

profile-and-dashboard

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
ci:reevaluate:1377401_9082

**Comment by pat270** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
