### PR TITLE
Lps 148295 4

### PR DESCRIPTION
**Pull request by amosfong**

### CODE REVIEW

**Comment by amosfong** [comment]
ci:test:relevant

**Comment by epark18** [comment]
ci:test:relevant

**Comment by epark18** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by epark18** [comment]
Failures are unrelated. The failure in [com.liferay.headless.delivery.resource.v1_0.test.CommentResourceTest
](https://testray.liferay.com/home/-/testray/case_results/1632514848) looks like it occurs flakily in [upstream ](https://testray.liferay.com/home/-/testray/case_results/1634088049).

**Comment by drewbrokke** [comment]
ci:reevaluate:1357401_1024

**Comment by drewbrokke** [comment]
@epark18 are these failures related? If not, then this seems good to go.

**Comment by epark18** [comment]
This looks good to me, I will forward this to Brian.

**Comment by epark18** [comment]
ci:close

**Pull request closed without merging**
