### PR TITLE
[TS] LPS-141217

### PR DESCRIPTION
**Pull request by ChrisKian**
From @tototrinh:

> Hi, please help me review this PR and give me your feedback. Thanks.
> The issue is described in https://issues.liferay.com/browse/LPP-42946
> 
> I found that the difference in the parameter's name caused this issue:
> https://github.com/liferay/liferay-portal/blob/master/modules/apps/users-admin/users-admin-web/src/main/resources/META-INF/resources/user/personal_information.jsp#L35
> https://github.com/liferay/liferay-portal/blob/master/modules/apps/users-admin/users-admin-web/src/main/resources/META-INF/resources/user/personal_information.jsp#L75-L77
> https://github.com/liferay/liferay-portal/blob/master/modules/apps/users-admin/users-admin-web/src/main/java/com/liferay/users/admin/web/internal/portlet/action/EditUserMVCActionCommand.java#L136-L137

### CODE REVIEW

**Comment by drewbrokke** [comment]
@ChrisKian @tototrinh I'd like to try a different solution. Even with fixing the parameter name, we are losing other parameters from the original URL like `redirect`. We have used `onErrorRedirect` in another circumstance to specify a unique redirect when an exception is thrown.

See [view_tree.jsp#L109](https://github.com/liferay/liferay-portal/blob/ebb6727f3eeed5cb2d4a2867ce330575fb2ee32e/modules/apps/users-admin/users-admin-web/src/main/resources/META-INF/resources/view_tree.jsp#L109) and [DeleteOrganizationsAndUsersMVCActionCommand.java#L100-L101](https://github.com/liferay/liferay-portal/blob/ebb6727f3eeed5cb2d4a2867ce330575fb2ee32e/modules/apps/users-admin/users-admin-web/src/main/java/com/liferay/users/admin/web/internal/portlet/action/DeleteOrganizationsAndUsersMVCActionCommand.java#L100-L101).

Thanks!

**Comment by tototrinh** [comment]
@drewbrokke thanks for your feedback. I will look at it and resend the PR.

**Comment by tototrinh** [comment]
Hi @drewbrokke, @ChrisKian
With my fix above, the URL will be:
`http://localhost:8080/group/control_panel/manage?p_p_id=com_liferay_users_admin_web_portlet_UsersAdminPortlet&p_p_lifecycle=0&p_p_state=maximized&p_p_mode=view&_com_liferay_users_admin_web_portlet_UsersAdminPortlet_birthday=01%2F01%2F1970&_com_liferay_users_admin_web_portlet_UsersAdminPortlet_lastName=User+5&p_p_lifecycle=1&_com_liferay_users_admin_web_portlet_UsersAdminPortlet_p_u_i_d=0&_com_liferay_users_admin_web_portlet_UsersAdminPortlet_suffixValue=&_com_liferay_users_admin_web_portlet_UsersAdminPortlet_jobTitle=&_com_liferay_users_admin_web_portlet_UsersAdminPortlet_screenName=user5&_com_liferay_users_admin_web_portlet_UsersAdminPortlet_birthdayMonth=0&_com_liferay_users_admin_web_portlet_UsersAdminPortlet_emailAddress=postmaster%40gg.com&_com_liferay_users_admin_web_portlet_UsersAdminPortlet_screenNavigationEntryKey=&_com_liferay_users_admin_web_portlet_UsersAdminPortlet_addOrganizationIds=40701&_com_liferay_users_admin_web_portlet_UsersAdminPortlet_birthdayYear=1970&_com_liferay_users_admin_web_portlet_UsersAdminPortlet_screenNavigationCategoryKey=general&_com_liferay_users_admin_web_portlet_UsersAdminPortlet_javax.portlet.action=%2Fusers_admin%2Fedit_user&_com_liferay_users_admin_web_portlet_UsersAdminPortlet_mvcPath=%2Fedit_user.jsp&_com_liferay_users_admin_web_portlet_UsersAdminPortlet_comments=&_com_liferay_users_admin_web_portlet_UsersAdminPortlet_formDate=1635826016628&_com_liferay_users_admin_web_portlet_UsersAdminPortlet_languageId=en_US&_com_liferay_users_admin_web_portlet_UsersAdminPortlet_prefixValue=&_com_liferay_users_admin_web_portlet_UsersAdminPortlet_firstName=User&_com_liferay_users_admin_web_portlet_UsersAdminPortlet_birthdayDay=1&_com_liferay_users_admin_web_portlet_UsersAdminPortlet_onErrorRedirect=http%3A%2F%2Flocalhost%3A8080%2Fgroup%2Fcontrol_panel%2Fmanage%3Fp_p_id%3Dcom_liferay_users_admin_web_portlet_UsersAdminPortlet%26p_p_lifecycle%3D0%26p_p_state%3Dmaximized%26p_p_mode%3Dview%26_com_liferay_users_admin_web_portlet_UsersAdminPortlet_redirect%3Dhttp%253A%252F%252Flocalhost%253A8080%252Fgroup%252Fcontrol_panel%252Fmanage%253Fp_p_id%253Dcom_liferay_users_admin_web_portlet_UsersAdminPortlet%2526p_p_lifecycle%253D0%2526p_p_state%253Dmaximized%2526p_p_mode%253Dview%2526_com_liferay_users_admin_web_portlet_UsersAdminPortlet_toolbarItem%253Dview-all-organizations%2526_com_liferay_users_admin_web_portlet_UsersAdminPortlet_usersListView%253Dflat-organizations%2526_com_liferay_users_admin_web_portlet_UsersAdminPortlet_displayStyle%253Dlist%2526_com_liferay_users_admin_web_portlet_UsersAdminPortlet_cur%253D1%2526_com_liferay_users_admin_web_portlet_UsersAdminPortlet_delta%253D20%2526_com_liferay_users_admin_web_portlet_UsersAdminPortlet_city%253D%2526_com_liferay_users_admin_web_portlet_UsersAdminPortlet_countryId%253D0%2526_com_liferay_users_admin_web_portlet_UsersAdminPortlet_name%253D%2526_com_liferay_users_admin_web_portlet_UsersAdminPortlet_parentOrganizationId%253D0%2526_com_liferay_users_admin_web_portlet_UsersAdminPortlet_regionId%253D0%2526_com_liferay_users_admin_web_portlet_UsersAdminPortlet_street%253D%2526_com_liferay_users_admin_web_portlet_UsersAdminPortlet_type%253D%2526_com_liferay_users_admin_web_portlet_UsersAdminPortlet_zip%253D%2526_com_liferay_users_admin_web_portlet_UsersAdminPortlet_orderByCol%253Dname%2526_com_liferay_users_admin_web_portlet_UsersAdminPortlet_orderByType%253Dasc%26_com_liferay_users_admin_web_portlet_UsersAdminPortlet_mvcRenderCommandName%3D%252Fusers_admin%252Fedit_user%26_com_liferay_users_admin_web_portlet_UsersAdminPortlet_organizationsSearchContainerPrimaryKeys%3D40701&_com_liferay_users_admin_web_portlet_UsersAdminPortlet_middleName=&_com_liferay_users_admin_web_portlet_UsersAdminPortlet_cmd=add`

-> **Looks like the URL still contains the original parameter?**

I tried to change code [here](https://github.com/liferay/liferay-portal-ee/blob/master/modules/apps/users-admin/users-admin-web/src/main/java/com/liferay/users/admin/web/internal/portlet/action/EditUserMVCActionCommand.java#L357-L368) like below:
`if (exception instanceof CompanyMaxUsersException ||
	exception instanceof RequiredUserException ||
        exception instanceof UserEmailAddressException ) {

	String redirect = portal.escapeRedirect(
		ParamUtil.getString(actionRequest, "onErrorRedirect"));

	if (Validator.isNotNull(redirect)) {
		sendRedirect(actionRequest, actionResponse, redirect);

		return;
	}
}`

with `onErrorRedirect` being the current URL

`http://localhost:8080/group/control_panel/manage?p_p_id=com_liferay_users_admin_web_portlet_UsersAdminPortlet&p_p_lifecycle=0&p_p_state=maximized&p_p_mode=view&_com_liferay_users_admin_web_portlet_UsersAdminPortlet_redirect=http%3A%2F%2Flocalhost%3A8080%2Fgroup%2Fcontrol_panel%2Fmanage%3Fp_p_id%3Dcom_liferay_users_admin_web_portlet_UsersAdminPortlet%26p_p_lifecycle%3D0%26p_p_state%3Dmaximized%26p_p_mode%3Dview%26_com_liferay_users_admin_web_portlet_UsersAdminPortlet_toolbarItem%3Dview-all-organizations%26_com_liferay_users_admin_web_portlet_UsersAdminPortlet_usersListView%3Dflat-organizations%26_com_liferay_users_admin_web_portlet_UsersAdminPortlet_displayStyle%3Dlist%26_com_liferay_users_admin_web_portlet_UsersAdminPortlet_cur%3D1%26_com_liferay_users_admin_web_portlet_UsersAdminPortlet_delta%3D20%26_com_liferay_users_admin_web_portlet_UsersAdminPortlet_city%3D%26_com_liferay_users_admin_web_portlet_UsersAdminPortlet_countryId%3D0%26_com_liferay_users_admin_web_portlet_UsersAdminPortlet_name%3D%26_com_liferay_users_admin_web_portlet_UsersAdminPortlet_parentOrganizationId%3D0%26_com_liferay_users_admin_web_portlet_UsersAdminPortlet_regionId%3D0%26_com_liferay_users_admin_web_portlet_UsersAdminPortlet_street%3D%26_com_liferay_users_admin_web_portlet_UsersAdminPortlet_type%3D%26_com_liferay_users_admin_web_portlet_UsersAdminPortlet_zip%3D%26_com_liferay_users_admin_web_portlet_UsersAdminPortlet_orderByCol%3Dname%26_com_liferay_users_admin_web_portlet_UsersAdminPortlet_orderByType%3Dasc&_com_liferay_users_admin_web_portlet_UsersAdminPortlet_mvcRenderCommandName=%2Fusers_admin%2Fedit_user&_com_liferay_users_admin_web_portlet_UsersAdminPortlet_organizationsSearchContainerPrimaryKeys=40701`

**And I see that all input's value will be lost. I don't think this is expected behavior. -> I am still concerned about this case. Could you please help explain more? **

Sorry if I misunderstood anything.
Thanks.

**Comment by drewbrokke** [comment]
@tototrinh thanks for bringing this up. I will double-check the scenario in case I misunderstood.

**Comment by drewbrokke** [comment]
Your fix is correct @tototrinh. See https://github.com/liferay-usm/liferay-portal/pull/327.

**Pull request closed without merging**
