### PR TITLE
[TS] LPS-132255

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
The failure not related and the [fix commit 1](https://github.com/brianchandotcom/liferay-portal/pull/101993), [fix commit 2](https://github.com/brianchandotcom/liferay-portal/pull/101994) just got merged, will retrigger the relavant test later.

**Comment by Sharryxue** [comment]
ci:test:relevant

**Review by drewbrokke — APPROVED** [review]
LGTM 👍

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
@jonathanmccann looks good! Please send a follow-up pull that adds a test case for these new conditions when you have a chance. Thanks!

**Pull request closed without merging**
