### PR TITLE
LPS-153684 Regions do not get translated or ordered properly when changing display language

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-153684](https://issues.liferay.com/browse/LPS-153684).<br/><br/>/cc @pei-jung @ChrisKian @patriciajeanperez @epark18 @david-truong @gislayne-vitorino @RafaelCRC @victorcdp

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Review by pei-jung — APPROVED** [review]
LGTM!

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
