### PR TITLE
[TS] LPS-161024

### PR DESCRIPTION
**Pull request by ChrisKian**
Resent from https://github.com/liferay-usm/liferay-portal/pull/704

### CODE REVIEW

**Comment by Sharryxue** [comment]
ci:test:upgrade-all

**Comment by patriciajeanperez** [comment]
ci:test:upgrade

**Comment by patriciajeanperez** [comment]
ci:forward

**Comment by patriciajeanperez** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/122732

**Comment by patriciajeanperez** [comment]
ci:close

**Pull request closed without merging**
