### PR TITLE
LPS-168289 HR_344 SR should read Addresses as "Addresses heading level 2"

### PR DESCRIPTION
**Pull request by veroglez**

### CODE REVIEW

**Review by drewbrokke — APPROVED** [review]
@veroglez this seems fine, but I'm frankly a bit foggy on when to use headers and when to use header-like span tags. Can you link me to some docs on this?

cc @pat270

**Comment by veroglez** [comment]
Hi @drewbrokke! In the past the use of headers has been very controversial in Liferay, because the header structure can be broken very easily and this always creates accessibility issues.
We just need to ensure that the page has correct semantics so that assistive technologies can navigate it correctly.
If a list already exists on the page, as in this case, it's not necessary to add headers within that list, the list itself is already semantically correct.

**Comment by drewbrokke** [comment]
@veroglez makes sense, thank you for the explanation!

**Comment by pat270** [comment]
@veroglez I'm just adding some details to help clarify the confusion. I think @drewbrokke is referencing other places where it was suggested to get rid of `h#` tags. We have mark up in Edit User > General > Organizations that looks like:
```html
<h3 class="autofit-row sheet-subtitle">
  <div class="autofit-col autofit-col-expand">
    <span class="heading-text">Organizations</span>
  </div>
  <div class="autofit-col">
    <span class="heading-end">
      <span class="modify-link">
        <a href="javascript:void(0);" target="_self" class="btn btn-secondary btn-sm lfr-icon-item taglib-icon" id="_com_liferay_users_admin_web_portlet_UsersAdminPortlet_selectOrganizationLink">
          <span class="taglib-text ">Select</span>
        </a>
      </span>
    </span>
  </div>
</h3>
```

It has text and a button inside a `h3` tag.  The screen reader announces it "Heading Level 3 2 items, ORGANIZATIONS Select" because the text and button are both inside the `h3` tag.

In this pr, the mark up looks like:
```html
<div class="sheet-header">
  <div class="autofit-row sheet-title">
    <div class="autofit-col autofit-col-expand">
      <h2 class="heading-text">Addresses</h2>
    </div>
    <div class="autofit-col">
      <span class="heading-end">
        <a class="add-address-link btn btn-secondary btn-sm" role="button" href="" aria-label="Add Addresses">Add</a>
      </span>
    </div>
  </div>
</div>
```

The screen reader announces it "Heading Level 2, Addresses" because the `h#` tag only encompasses the text. 

We also had other issues where the `h#` tag was unnecessary (https://issues.liferay.com/browse/LPS-168768).

**Pull request closed without merging**
