### PR TITLE
LPS-138941 Support doc links in configuration forms

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by pei-jung** [comment]
@drewbrokke Ended up using attributes on the `ExtendedObjectClassDefinition` instead of providing an SPI because there are configurations in the static modules, such as `BundleBlacklistConfiguration`, and modules in the `modules/apps/static` dir cannot have dependency on the `configuration-admin-api` module. Doing so will cause a startup error with unresolved dependency.

Here is the look of the doc link on the configuration form
Screen Shot 2021-09-09 at 10 14 39 PM

**Comment by pei-jung** [comment]
ci:test:relevant

**Review by drewbrokke — APPROVED** [review]
The changes look great @pei-jung 👍 This is probably a much better solution in any case. 

@jhinkey please take a look at the [last commit](https://github.com/liferay-usm/liferay-portal/pull/259/commits/1f8de90cd2b4be738ee650f3ab450d5e3e31c76c) for an example usage and the [screenshot](https://github.com/liferay-usm/liferay-portal/pull/259/#issuecomment-916642656) for the rendered result.

**Comment by jhinkey** [comment]
@pei-jung and @drewbrokke - That looks great! Thanks so much. :-)

**Comment by drewbrokke** [comment]
@pei-jung after CI passes we can go ahead and forward.

**Comment by pei-jung** [comment]
ci:forward

**Pull request closed without merging**
