### PR TITLE
LPS-173281 As a developer, I'd like a feature flag to depend on another feature flag

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-173281](https://issues.liferay.com/browse/LPS-173281).

Visible under the feature flag: `feature.flag.LPS-167698=true`

/cc @pei-jung @ChrisKian @patriciajeanperez @david-truong @gislayne-vitorino

### CODE REVIEW

**Comment by drewbrokke** [comment]
Declare dependencies in `portal.properties`:

Screen Shot 2023-01-19 at 5 19 15 PM

Screen Shot 2023-01-19 at 5 19 42 PM

The toggle is disabled when the dependencies are not satisfied:

Screen Shot 2023-01-19 at 5 15 08 PM

The toggle is toggle-able when the dependencies are satisfied:

Screen Shot 2023-01-19 at 5 15 24 PM

Screen Shot 2023-01-19 at 5 15 32 PM

Multiple dependencies can be declared:

Screen Shot 2023-01-19 at 5 16 40 PM

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:reevaluate:1287401_5590

**Comment by drewbrokke** [comment]
Here are a couple of shots of the entire view:

Screen Shot 2023-01-20 at 3 42 03 PM

Screen Shot 2023-01-20 at 3 42 40 PM

**Review by pei-jung — APPROVED** [review]
Nice work, @drewbrokke! Changes look great!

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
