### PR TITLE
LPS-138612 Control menu in Account Groups is not consistent with other tabs

### PR DESCRIPTION
**Pull request by erickmonteiroo**

### CODE REVIEW

**Comment by erickmonteiroo** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:reevaluate:1327401_192

**Review by pei-jung — APPROVED** [review]

**Comment by pei-jung** [comment]
@patriciajeanperez are the failures related?

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
@pei-jung same error with the Account Groups pr. will also manually forward this pull.

**Comment by patriciajeanperez** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/106867

**Comment by patriciajeanperez** [comment]
ci:close

**Pull request closed without merging**
