### PR TITLE
LPS-160393 Add search by ISO codes

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-160393](https://issues.liferay.com/browse/LPS-160393).<br/><br/>@pei-jung will you please take a look at my change and let me know your thoughts\? I tried to make things consistent between the two classes.

### CODE REVIEW

**Review by pei-jung — APPROVED** [review]
LGTM, thanks @drewbrokke! 👍

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:reevaluate:1357401_2359

**Comment by drewbrokke** [comment]
ci:reevaluate:1357401_2359

**Comment by pei-jung** [comment]
@patriciajeanperez are the failures related? If not, can you manually forward this to Brian? Thanks!

**Comment by pei-jung** [comment]
Resent with test fixes here: https://github.com/liferay-usm/liferay-portal/pull/700

**Pull request closed without merging**
