### PR TITLE
LPS-147272 As a developer using Headless Admin User endpoints, I want to search for an AccountRole by name

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-147272](https://issues.liferay.com/browse/LPS-147272).<br/><br/>/cc @pei-jung @ChrisKian @patriciajeanperez @lr-leo @erickmonteiroo

### CODE REVIEW

**Comment by epark18** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:forward

**Comment by epark18** [comment]
It didn't appear that the errors are related, but the Upgrades tests for [PortalSmokeUpgrade#ViewPortalSmokeArchive621021](https://testray.liferay.com/home/-/testray/case_results/1627070320), [PortalSmokeUpgrade#ViewPortalSmokeArchive70106](https://testray.liferay.com/home/-/testray/case_results/1627070298), [PortalSmokeUpgrade#ViewPortalSmokeArchive7310](https://testray.liferay.com/home/-/testray/case_results/1627070256)  are failing on just this PR with this warning. The tests are still completing, but they are showing `  [exec]     Finished reindexing after 30 seconds.
     [exec]     LIFERAY_ERROR: null
     [exec]     LIFERAY_ERROR: null
     [exec]     LIFERAY_ERROR: null
     [exec]     LIFERAY_ERROR: null
     [exec] 
     [exec]     BUILD FAILED: 
     [exec]     ##
     [exec]     ## 4 Liferay Exceptions were thrown
     [exec]     ##
     [exec] 
     [exec]     LIFERAY_ERROR: null
     [exec]     LIFERAY_ERROR: null
     [exec]     LIFERAY_ERROR: null
     [exec]     LIFERAY_ERROR: null
     [exec] 
     [exec] 
     [exec]     /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/upgrades/PortalSmokeUpgrade.testcase[ViewPortalSmokeArchive70106]:127`
[Full Console](https://testray.liferay.com/reports/production/logs/2022-03/test-1-30/test-portal-acceptance-pullrequest(master)/2354/functional-upgrade-tomcat90-mysql57-jdk8/0/1/jenkins-console.txt.gz?authuser=0) | [Poshi Report](https://testray.liferay.com/reports/production/logs/2022-03/test-1-30/test-portal-acceptance-pullrequest(master)/2354/functional-upgrade-tomcat90-mysql57-jdk8/0/1/LocalFile.PortalSmokeUpgrade_ViewPortalSmokeArchive70106/index.html.gz?authuser=0)

**Comment by Sharryxue** [comment]
Hello @drewbrokke,
The failure `NoSuchResourceActionException: com.liferay.account.model.AccountRole#VIEW` seems related, would you please double check? Thanks. Here are partial of the failure, more details refer [Jenkins log](https://testray.liferay.com/reports/production/logs/2022-03/test-1-30/test-portal-acceptance-pullrequest(master)/2354/functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0/jenkins-console.txt.gz?authuser=0)
```
     [exec] 2022-03-04 15:15:51.631 ERROR [default-15][SearchPermissionCheckerImpl:144] null
     [exec] com.liferay.portal.kernel.exception.NoSuchResourceActionException: com.liferay.account.model.AccountRole#VIEW
     [exec] 	at com.liferay.portal.service.impl.ResourceActionLocalServiceImpl.getResourceAction(ResourceActionLocalServiceImpl.java:327) ~[portal-impl.jar:?]
     [exec] 	at sun.reflect.GeneratedMethodAccessor175.invoke(Unknown Source) ~[?:?]
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
```

**Comment by drewbrokke** [comment]
See https://github.com/liferay-usm/liferay-portal/pull/482

**Pull request closed without merging**
