### PR TITLE
LPS-174157 remove the restriction requiring company admin

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-174157](https://issues.liferay.com/browse/LPS-174157).<br/><br/>/cc @pei-jung @ChrisKian @patriciajeanperez @david-truong @gislayne-vitorino

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
Failures in relevant are not related

**Comment by drewbrokke** [comment]
ci:reevaluate:1277401_6749

**Comment by drewbrokke** [comment]
ci:reevaluate:1277401_6749

**Comment by drewbrokke** [comment]
ci:reevaluate:1277401_6749

**Review by pei-jung — APPROVED** [review]
LGTM!

**Comment by drewbrokke** [comment]
@patriciajeanperez this one is ready to go.

**Comment by patriciajeanperez** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/129661

**Pull request closed without merging**
