### PR TITLE
LPS-154973 Update ALL the files with the permissions sent 

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-154973](https://issues.liferay.com/browse/LPS-154973).

@boton this pull request uses the React component for all checkboxes. I made a couple of adjustments to the `PermissionCheckbox` component:

1. Moved the dynamic state to dedicated state variables
2. Inlined some of the props that don't need to be dynamic _yet_ (value, indeterminateValue).
3. Removed `cssClass`, which we can re-add when it's needed

I also was curious to know what advantage is gained (or problem avoided) by not passing in to the `ClayCheckbox` the `prepareProps` variables (e.g. `_componentId`, `_locale`). I see that done a few places, is it a problem to allow them to pass through with `otherProps`? In my testing it didn't seem to change anything, but I could be missing something.

Thanks!

/cc @pei-jung @AliciaGarciaGarcia

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
LGTM

**Comment by boton** [comment]
Thanks, @drewbrokke awesome work. I'm totally ok with your changes.

And sorry about transferring the complexity of the CheckboxTag here, is much better after your refactor [a3c56f3](https://github.com/liferay-usm/liferay-portal/pull/676/commits/a3c56f3318c37b56e2d3ab55e01e3ca7e0530548) 😄  


> I also was curious to know what advantage is gained (or problem avoided) by not passing in to the ClayCheckbox the prepareProps variables (e.g. _componentId, _locale). I see that done a few places, is it a problem to allow them to pass through with otherProps? In my testing it didn't seem to change anything, but I could be missing something.

Yep, it's precisely for pruning the `otherProps` before passing to the ClayCheckbox and passing down cleanest as possible, in some cases react launch a warning about trying to convert props into HTML attr.

In this case, after you simplify the component a lot ❤️. Maybe it is a good idea cherry pick the values we need and drop `otherProps`.

Something like https://github.com/boton/liferay-portal/commit/296f8d402350913907be65556a97461ed0d22024 feel free to add the commit or the code if works for you too or ignore it.

**Comment by drewbrokke** [comment]
@boton thanks for the feedback, glad it works for you! I think it's ok to prune the `otherProps`, since we don't know if the props being passed to `ClayCheckbox` will change at some point.

**Comment by epark18** [comment]
ci:test:relevant

**Comment by epark18** [comment]
Looks good to me!

**Comment by drewbrokke** [comment]
@boton any objects to forwarding this one?

**Comment by boton** [comment]
> @boton any objections to forwarding this one?

Absolutely not, please forward it :D

**Comment by drewbrokke** [comment]
@epark18 if there are no relevant failures, let's go ahead and send this one on.
Thanks everyone!

**Comment by epark18** [comment]
Forwarded to Brian https://github.com/brianchandotcom/liferay-portal/pull/121387.

**Comment by epark18** [comment]
ci:close

**Pull request closed without merging**
