### PR TITLE
LPS-164091 Cover searh by usigin integration test

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**
Hello Team,

Could you please review this pull request?

We need to provide a way to search by role name, title or description through the API,

I created a query parameter called "search" and I passed as keywords in `roleService.search`,

let me know if I'm missing something,

feel free to contact me if there are questions.

Thank you!

### CODE REVIEW

**Review by drewbrokke — APPROVED** [review]
LGTM 👍

**Comment by pei-jung** [comment]
@MarinhoFeliphe I believe you have a typo in your commit message in [dc6ae09](https://github.com/liferay-usm/liferay-portal/pull/762/commits/dc6ae09dffcd0840981850484b4d82a1e2039696); it should be `using` instead of `usigin`. Other than that, everything looks good. Thank you!

**Comment by MarinhoFeliphe** [comment]
@pei-jung 

fixed! Thank you!

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Pull request closed without merging**
