### PR TITLE
LPS-117666

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-117666](https://issues.liferay.com/browse/LPS-117666)
Dear Team,

This is the resurrection of an old case where the fix didn't get to master eventually. Previous pull request: https://github.com/drewbrokke/liferay-portal/pull/1181

Please review my changes and share your observations.

Thank you,
Istvan

### CODE REVIEW

**Comment by melodywu** [comment]
No related issue found in ci:test:relevant.

**Comment by drewbrokke** [comment]
@istvansajtos my apologies for the delay. I will review it this week.

**Comment by istvansajtos** [comment]
Thanks for the update @drewbrokke !

**Comment by istvansajtos** [comment]
Hi @drewbrokke , do you have any update on this? Thank you!

**Comment by drewbrokke** [comment]
Hey @istvansajtos, thanks for checking in. I'm exploring a possible alternative, and I'll be sure to have a review for you by EOD tomorrow. Thanks for patience!

**Comment by drewbrokke** [comment]
See https://github.com/liferay-usm/liferay-portal/pull/954.

**Comment by drewbrokke** [comment]
@istvansajtos I tried the approach of using the UserBagFactory logic to get all the user's inherited roles. Please take a look and let me know if you have any questions or concerns. Thanks!

**Pull request closed without merging**
