### PR TITLE
LPS-165341 Check cookie consent when using sessionStorage

### PR DESCRIPTION
**Pull request by victorg1991**
Hey @drewbrokke not sure if this the right place to send this PR, but let me know :) 

This is a simple change to use the Storage class from infra in order to retrieve values from the session storage in order to be compliant with cookie policies

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Review by drewbrokke — COMMENTED** [review]
@victorg1991 thanks for sending this change! This looks good to me, were you able to test the change at all?

**Comment by victorg1991** [comment]
Yes :)  I tested it, I ended up sending the pr to the app sec team, which are the new owners of this isn't it?

**Comment by drewbrokke** [comment]
@victorg1991 you are correct, though this github user is still active/monitored for now, so either works :)

**Pull request closed without merging**
