### PR TITLE
LPS-165421

### PR DESCRIPTION
**Pull request by jonathanmccann**
If the team feels that alphabetizing the _set*_ calls for _searchContext_ is better then the second commit can be dropped, otherwise this only checks for a non-null _params_ once.

### CODE REVIEW

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
This pull is identical to https://github.com/liferay-usm/liferay-portal/pull/780. We'll forward whichever passes CI first :)

**Comment by melodywu** [comment]
Relevant failures are not related

**Comment by drewbrokke** [comment]
ci:reevaluate:1287401_4716

**Comment by patriciajeanperez** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/124549

**Pull request closed without merging**
