### PR TITLE
LPS-135882

### PR DESCRIPTION
**Pull request by mbowerman**
https://issues.liferay.com/browse/LPS-135882

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@mbowerman thank you for this. Would you be willing to also include an integration test case with this?

**Review by drewbrokke — CHANGES_REQUESTED** [review]
@mbowerman thank you for this. Would you be willing to also include an integration test case with this?

**Comment by mbowerman** [comment]
Hi @drewbrokke,

Please see https://github.com/liferay-usm/liferay-portal/pull/161/commits/b4e616500804a8223d4367b4577978ce4694606b.

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@mbowerman this looks good. I will forward this as soon as we have a release build. If the customer needs a solution quickly, I think this is appropriate to deliver in a SDH.

**Comment by mbowerman** [comment]
Hi @drewbrokke, do you have an estimate for how long it will take to have the next release build? That may inform our decision about whether or not we decide to give an SDH to the customer. Thanks!

**Comment by drewbrokke** [comment]
@mbowerman I don't have an estimate, but from the looks of it there are not any known blockers to the release at this point, which is good news 👍

**Comment by drewbrokke** [comment]
What is your time threshold? Are you able to wait a few days, or do you need to deliver a fix sooner? If sooner, then I might suggest SDH.

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
Forwarding to Brian per his request. This seems like a relatively safe change.

**Pull request closed without merging**
