### PR TITLE
[TS] LPS-138867 configuration-admin-web: Use the updated path for the export resource URL

### PR DESCRIPTION
**Pull request by ericyanLr**
https://issues.liferay.com/browse/LPS-138867

Hi USM Team,

Can you help review this PR?

Please let me know if you have any questions.
Thanks!

### CODE REVIEW

**Comment by drewbrokke** [comment]
@ericyanLr any context for what caused this issue in the first place?

**Comment by ericyanLr** [comment]
Hi @drewbrokke ,

Yes, it was introduced by [LPS-115709](https://issues.liferay.com/browse/LPS-115709), looks like an SF ticket.

Here is the specific commit: https://github.com/liferay/liferay-portal/commit/8e6fd5c1003f31fd4177044a1234ea404f270b98

It looks like the URL for exporting all was properly changed, but not for the single export:
- Export all: [view_factory_instances.jsp#L93-L96](https://github.com/liferay/liferay-portal/blob/7.4.2-ga3/modules/apps/configuration-admin/configuration-admin-web/src/main/resources/META-INF/resources/view_factory_instances.jsp#L93-L96)
- Single Export: [view_factory_instances.jsp#L218-L221](https://github.com/liferay/liferay-portal/blob/7.4.2-ga3/modules/apps/configuration-admin/configuration-admin-web/src/main/resources/META-INF/resources/view_factory_instances.jsp#L218-L221)

**Comment by drewbrokke** [comment]
Thanks for the explanation @ericyanLr 👍

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
