### PR TITLE
LPS-168266 Users Table shouldn't have links without text in table cell

### PR DESCRIPTION
**Pull request by pat270**
- If a user doesn't have a Job Title, Organizations or User Group a link without text shouldn't be output

https://issues.liferay.com/browse/LPS-168266

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:relevant

**Review by drewbrokke — CHANGES_REQUESTED** [review]
@pat270 I think we could abstract some of this to earlier in the file to make it a bit easier to reason about. That way we can also reduce duplicate method calls.

**Review by drewbrokke — CHANGES_REQUESTED** [review]
@pat270 this one's odd to me. My immediate question is why we have to do this manually. Wouldn't it be better if the search container just didn't render a link that had no content? Could we investigate fixing this at the taglib level?

**Comment by pat270** [comment]
@drewbrokke I'm not sure, should the attributes `href` and `value` be dependent on each other? The reason it's printing an `a` tag with no text is because `rowURL` exists, but the value is blank.

**Comment by drewbrokke** [comment]
@pat270 that makes sense, but that's pretty custom, right? In that case it would make sense to just add an actual body to the taglib, which you would still be able to do.

**Comment by pat270** [comment]
@drewbrokke You have a point. The other thing that worries me is the age of this tag. You think it's safe to break?

**Comment by drewbrokke** [comment]
@pat270 it's a good question. It seems like the change itself is pretty safe, but of course we'd want to test it. If it seems like a reasonable amount of effort, let's give it a shot. In theory this problem would be present elsewhere, right?

**Comment by pat270** [comment]
New pr at https://github.com/liferay-frontend/liferay-portal/pull/3110

**Pull request closed without merging**
