### PR TITLE
LPS-170002 | master

### PR DESCRIPTION
**Pull request by sontruongces**
Hi team,

This is the fix for the [LPS-170002](https://issues.liferay.com/browse/LPS-170002), the original has passed my review at sontruongces#64. Please help me to review and give feedback.

Thanks!
cc: @quanhuynhces

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:account

**Comment by Sharryxue** [comment]
Test fix for following tests are required with the fix commit here. Will add the test fix commits after the PR get approved.
[LocalFile.Account#CannotInviteUserWithDifferentDomain](https://testray.liferay.com/home/-/testray/case_results/2091897208?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2091897020%26testrayRunId%3D2091897037%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)
[LocalFile.Account#CanInviteNewUserToAccount](https://testray.liferay.com/home/-/testray/case_results/2091897389?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2091897020%26testrayRunId%3D2091897037%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
@patriciajeanperez this one is good to go. We'll have to manually forward this one, right?

**Comment by Sharryxue** [comment]
ci:close

**Pull request closed without merging**
