### PR TITLE
LPS-130381 Eliminate "two star" wildcard usages for the emailAddress field

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:users

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:reevaluate:1087401_7300

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:users

**Comment by patriciajeanperez** [comment]
Hey @pei-jung, I checked the results and most failures are from searching a user. Searching a user does not display any results. Please see [Liferay log](https://testray.liferay.com/reports/production/logs/2021-05/test-1-8/test-portal-acceptance-pullrequest(master)/7300/functional-tomcat90-mysql57-jdk8/0/12/liferay-log.txt.gz). Thanks!

`2021-05-03 19:32:47.075 ERROR [http-nio-8080-exec-3][WorkflowMetricsPortalExecutor:53] java.lang.RuntimeException: org.elasticsearch.ElasticsearchStatusException: [liferay-54016-workflow-metrics-sla-task-results/boLm_M6zS-qukBwdD4qTTQ] ElasticsearchStatusException[Elasticsearch exception [type=resource_already_exists_exception, reason=index [liferay-54016-workflow-metrics-sla-task-results/boLm_M6zS-qukBwdD4qTTQ] already exists]]
     [exec] java.lang.RuntimeException: org.elasticsearch.ElasticsearchStatusException: [liferay-54016-workflow-metrics-sla-task-results/boLm_M6zS-qukBwdD4qTTQ] ElasticsearchStatusException[Elasticsearch exception [type=resource_already_exists_exception, reason=index [liferay-54016-workflow-metrics-sla-task-results/boLm_M6zS-qukBwdD4qTTQ] already exists]]`

**Pull request closed without merging**
