### PR TITLE
LPS-136288 users-admin should use it's own image uploader

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@IstvanD looks like a semver failure related to the new taglib attribute. Please update and resend.

**Comment by IstvanD** [comment]
@drewbrokke sorry, I corrected the error and sent a new pull: https://github.com/liferay-usm/liferay-portal/pull/202

**Comment by drewbrokke** [comment]
Thank you @IstvanD 👍

**Pull request closed without merging**
