### PR TITLE
LPS-141903 Only count the assignee with the active users

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-141903

/cc @thuycao-gs

Resend of https://github.com/liferay-usm/liferay-portal/pull/333

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by epark18** [comment]
ci:test:relevant

**Comment by holatuwol** [comment]
Added an integration test.

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
