### PR TITLE
LPS-166023 Instance mail settings value is not inherited

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-166023](https://issues.liferay.com/browse/LPS-166023).<br/><br/>/cc @pei-jung @ChrisKian @patriciajeanperez @david-truong @gislayne-vitorino

### CODE REVIEW

**Comment by drewbrokke** [comment]
FYI @hongvo2308

**Review by pei-jung — COMMENTED** [review]
Changes look good to me. Is it possible to add a test for this?

**Comment by drewbrokke** [comment]
@pei-jung it should be possible. I imagine some special setup is required in order to set up clustering for the test scenario, but I'll give it a shot.

**Comment by drewbrokke** [comment]
@pei-jung I have a thread open regarding testing DB Parition scenarios: https://liferay.slack.com/archives/C08SHT1M0/p1673306505714099. Looks like the tools we need will be made available later this week.

**Comment by pei-jung** [comment]
@drewbrokke thanks for the update! I'm fine with forwarding this pull to Brian now and then send a follow-up pull to add the test. Feel free to forward if you think it's ready!

**Comment by drewbrokke** [comment]
Thanks @pei-jung. I'm ok leaving it open - it's not high priority, and I'm more likely to actually write the tests if I have the PR open to bug me :)

**Comment by drewbrokke** [comment]
@pei-jung it sounds like the test utils are going to be delayed a bit. I'm fine forwarding this one and revisiting the test cases when the tools are available.

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
