### PR TITLE
LPS-157692 No limitation for External Reference Code in Account

### PR DESCRIPTION
**Pull request by RafaelCRC**
update for [LPS-157692](https://issues.liferay.com/browse/LPS-157692) and consistency changes between accountGroup and accountEntry

### CODE REVIEW

**Comment by Sharryxue** [comment]
ci:test:account

**Comment by Sharryxue** [comment]
ci:test:bundle

**Comment by Sharryxue** [comment]
Hello @RafaelCRC,
Please take a look into the SF failure. Thanks.
There is a related failure found in _ci:test:relevant_ result, the Type's locator seems changes, not sure if it is intended or not? I'd trigger the CI to build a bundle to confirm the issue on local as well.
after

**Comment by Sharryxue** [comment]
Related failure found in [ci:test:account](https://github.com/liferay-usm/liferay-portal/pull/713#issuecomment-1233716855) suite, failed for the same/similar reason as mentioned [above](https://github.com/liferay-usm/liferay-portal/pull/713#issuecomment-1233683259).
[LocalFile.Accounts#CanAddAPersonAccount](https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/206328//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Accounts_CanAddAPersonAccount_)
[LocalFile.Accounts#CanEditAccountCustomField](https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/183278//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Accounts_CanEditAccountCustomField_)
[LocalFile.Accounts#Smoke](https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/196219//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Accounts_Smoke_)

**Comment by RafaelCRC** [comment]
Hi @Sharryxue that issue is not intended, im working on it. Thanks!

**Comment by RafaelCRC** [comment]
ci:test:sf

**Comment by RafaelCRC** [comment]
ci:test:relevant

**Comment by RafaelCRC** [comment]
ci:stop

**Comment by RafaelCRC** [comment]
ci:test:sf

**Comment by RafaelCRC** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
ci:test:account

**Comment by RafaelCRC** [comment]
ci:test:relevant

**Comment by RafaelCRC** [comment]
ci:test:account

**Comment by Sharryxue** [comment]
No related failure found in both [relava ](ci:test:relevant) and ci:test:account, the unique failure is fixed in [COMMERCE-9930](https://issues.liferay.com/browse/COMMERCE-9930).

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
@patriciajeanperez

**Comment by patriciajeanperez** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/122789

**Comment by patriciajeanperez** [comment]
ci:close

**Pull request closed without merging**
