### PR TITLE
LPS-131197 Account-specific roles cannot define permissions or be deleted

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Review by drewbrokke — APPROVED** [review]
Looks great, @pei-jung. I left a single comment about moving the service tracker for PanelCategoryRoleTypeMapper to api and impl, but it doesn't have to block this fix.

See https://issues.liferay.com/browse/LPS-131459.

**Comment by drewbrokke** [comment]
ci:forward

LGTM 👍

**Pull request closed without merging**
