### PR TITLE
[TS] LPS-154862 Unable to manage a site without the user locale enabled

### PR DESCRIPTION
**Pull request by joseluisbango**
Relevant issues:
- https://issues.liferay.com/browse/LPS-154862
- https://issues.liferay.com/browse/PTR-3085

Previous pr: https://github.com/liferay-usm/liferay-portal/pull/622

---

Hi @liferay-usm,

As requested by BChan in https://github.com/brianchandotcom/liferay-portal/pull/120369#issuecomment-1184727891, I have removed the property so that it is always turned on.

Could you review it and forward it again?

Thanks!

### CODE REVIEW

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
@epark18 once CI finishes, if there are no related failures, we can forward this one.

**Comment by epark18** [comment]
ci:test:relevant

**Comment by epark18** [comment]
Pushed to Brian. https://github.com/brianchandotcom/liferay-portal/pull/120476

**Comment by epark18** [comment]
ci:close

**Pull request closed without merging**
