### PR TITLE
LPS-148152 Unable to select account for account use via user admin

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-148152](https://issues.liferay.com/browse/LPS-148152).<br/><br/>/cc @pei-jung @erickmonteiroo @ChrisKian @patriciajeanperez @epark18 @david-truong

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:usm

**Comment by Sharryxue** [comment]
Failures are not related to the commits.

**Comment by epark18** [comment]
Tested PR locally and can no longer reproduce issues from previous PR pertaining to the `3.0 opt-in` for Account Groups, Personal Data, or from the original ticket for Users Admin. This looks good from QA side.

**Comment by erickmonteiroo** [comment]
ci:forward

**Pull request closed without merging**
