### PR TITLE
LPS-149125 As an admin, I want to add regular Users to Accounts

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by Sharryxue** [comment]
ci:test:bundle

**Comment by Sharryxue** [comment]
Hello @pei-jung, Here are issues related to the commits. Would you please double check the issue, thanks in advance.
Run the accounts tests (ci:test:account) with TF in [Sharryxue/liferay-portal#366](https://github.com/Sharryxue/liferay-portal/pull/366), related failure found in [POSHI Test](https://testray.liferay.com/home/-/testray/case_results/1652115455). 
- Fail to assign user to account with domain.
Steps to reproduce it (In order to reproduce the issue, follow the specific steps):
1. Enable Email Domain Validation via Instance Settings
2. Add Account without domain
3. Add 2 account user via User tab in Account
4. Add an account with domain, assign user via User tab, 
5. On the assign user modal for account, change the filter to All Users, check the select all checkbox > Assign
6. Failed to assign the users, got error message on page "Error:Your request failed to complete"
- The [AccountEntryUserRelLocalServiceTest.testUpdateAccountEntryUserRels](https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1/42032//testReport/com.liferay.account.service.test/AccountEntryUserRelLocalServiceTest/testUpdateAccountEntryUserRels) failed consistently in this pr, would you please look into it? Thanks

**Comment by pei-jung** [comment]
@Sharryxue thanks for pointing out the issues. I was not able to reproduce the "fail to assign user to account with domain" issue with the steps provided. Are you able to reproduce the issue locally?

I updated the PR with the following changes:
- Fixed the the failed test AccountEntryUserRelLocalServiceTest.testUpdateAccountEntryUserRels
- Rename the filters in Account Users portlet. 
  - category`Filter by Accounts` -> `Filter by Account Memberships`
  - `All` -> `Any Account`
  - `Accounts` -> `Selected Accounts`

Screen Shot 2022-03-31 at 6 12 39 PM

Please let me know if you have any questions. Thank you!

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
ci:test:bundle

**Comment by Sharryxue** [comment]
Hello @pei-jung ,
I was able to reproduce the issue locally, in case to reproduce it, the test steps should be very like that in the POSHI test case, I will double checking the steps on the new build bundle.
Thanks for your heads up in the filter, I'd updated the related POSHI tests as well.

**Comment by epark18** [comment]
@Sharryxue for your 2nd point _Accounts#UsersWithValidAndInvalidDomainsAreFilteredWhenAssigningUsers_ is failing because the test filters by all users for both Accounts (Account With Domain, Account No Domain). It then selects all users and tries to add them to an account. Trying to add a user with a non-registered email domain to an account with a list of valid domains gives us an error and doesn't end up adding anyone even if we checked multiple users and some of them have the correct email domain. That's why the account is showing no account users in the poshi report screenshots. 

Not too sure why this worked in the past. Maybe the administrator user could bypass this, but no longer can with the updates.

I think this is an easy fix because I can change the filter to "Valid Domain Users" when assigning Account Users to the "Account With Domain" Account.

**Comment by pei-jung** [comment]
@epark18 

> Trying to add a user with a non-registered email domain to an account with a list of valid domains gives us an error

This should not happen. Admin user should be able to add users with non-registered email domain to account with a list of valid domains. Do you see any errors in the console with this failed test?

Screen Shot 2022-04-01 at 11 15 06 AM

**Comment by epark18** [comment]
@pei-jung Yeah after some more testing, I can't seem to reproduce exactly. I'm not getting any errors in the console. Just an error message on Portal saying my request failed to complete when selecting all and trying to assign. Will continue to test

**Comment by epark18** [comment]
@pei-jung From what I can see, if the Test Test user is already added to the account with valid domains, trying to add another account user with a non-valid domain to the same account gives us the error message and does not add the user.

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
@epark18 i've fixed the two issues that Sharry brought up and updated the PR. Please let me know if there's other related failures. Thank you!

**Comment by epark18** [comment]
ci:test:bundle

**Comment by epark18** [comment]
Hello, @pei-jung looks like there was a compile error: Would you be able to take a look? Thank you!
`     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/account/account-service/src/main/java/com/liferay/account/service/impl/AccountEntryUserRelLocalServiceImpl.java:467: error: unreachable statement
     [exec] 		User user = _userLocalService.getUser(userId);`

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
@epark18 i fixed the compile error.

**Comment by epark18** [comment]
ci:test:bundle

**Comment by epark18** [comment]
ci:test:relevant

**Comment by epark18** [comment]
ci:test:usm

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by epark18** [comment]
ci:test:account

**Comment by drewbrokke** [comment]
ci:reevaluate:1297401_2373

**Comment by epark18** [comment]
ci:test:account

**Comment by drewbrokke** [comment]
See https://github.com/liferay-usm/liferay-portal/pull/516

**Comment by drewbrokke** [comment]
@epark18 do we need to leave this one open, or can we close it in favor of your pull?

**Comment by epark18** [comment]
@drewbrokke https://github.com/liferay-usm/liferay-portal/pull/516 is the most up to date so we can close this one.

**Comment by epark18** [comment]
ci:close

**Pull request closed without merging**
