### PR TITLE
LPS-151906 As a developer using headless endpoints, I'd like to get a page of countries

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-151906](https://issues.liferay.com/browse/LPS-151906).<br/><br/>/cc @pei-jung @erickmonteiroo @ChrisKian @patriciajeanperez @epark18 @david-truong

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:reevaluate:1297401_2655

**Comment by epark18** [comment]
Failures are unrelated.

**Comment by drewbrokke** [comment]
ci:reevaluate:1297401_2655

**Comment by drewbrokke** [comment]
Just ran the OrganizationResource tests locally, all passed. Looks like there may be some leftover data from another test case, but we can investigate it separately.

**Comment by drewbrokke** [comment]
See: https://github.com/liferay-usm/liferay-portal/pull/539

**Pull request closed without merging**
