### PR TITLE
LPS-162532 Enable unique permission checking for editing account domains

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-162532](https://issues.liferay.com/browse/LPS-162532).

@patriciajeanperez we need to update functional tests because of this one. 

The ability to edit domains via the UI is now controlled by the MANAGE_DOMAINS permission on the AccountEntry.

It is _no longer_ dependent on whether we are in the admin portlet or the widget.

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
ci:test:account

**Comment by patriciajeanperez** [comment]
Hi @drewbrokke, can you please check the following backend test failures and an error with functionality?

1. com.liferay.account.service.test.AccountEntryLocalServiceTest > testAddAccountEntryWithDomains
```
[exec]     arrays first differed at element [0]; expected:<test[]1.com> but was:<test[-]1.com>
```
2. com.liferay.account.service.test.AccountEntryLocalServiceTest > testUpdateDomains
```
[exec]     arrays first differed at element [0]; expected:<[foo].com> but was:<[bar].com>
```

3. Cannot update account name and description

**Comment by drewbrokke** [comment]
@patriciajeanperez will do, thank you for the heads up!

**Comment by drewbrokke** [comment]
@patriciajeanperez I just force-pushed. When you are able, please verify that I have resolved the problems you mentioned.

**Comment by patriciajeanperez** [comment]
ci:test:bundle

**Comment by patriciajeanperez** [comment]
ci:test:account

**Comment by patriciajeanperez** [comment]
Looks good, thanks @drewbrokke!

**Comment by drewbrokke** [comment]
ci:test:relevant

**Review by pei-jung — APPROVED** [review]
LGTM! 👍

**Comment by pei-jung** [comment]
ci:forward

**Pull request closed without merging**
