### PR TITLE
LPS-138086

### PR DESCRIPTION
**Pull request by brunoquei2105**

### CODE REVIEW

**Comment by brunoquei2105** [comment]
ci:test:relevant

**Comment by brunoquei2105** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
Hey @brunoquei2105, please take a look at the following errors upon startup:

` [parallel] 2021-10-04 22:50:52.805 ERROR [main][PortalInstances:276] com.liferay.portal.kernel.exception.ContactBirthdayException
 [parallel] com.liferay.portal.kernel.exception.ContactBirthdayException: null`

` [parallel] 2021-10-04 17:32:10.567 ERROR [Portal Dependency Manager Component Executor--1][VerifyProcessTrackerOSGiCommands:296] com.liferay.portal.verify.VerifyException: com.liferay.portal.verify.VerifyException: com.liferay.portal.kernel.exception.NoSuchRoleException: No Role exists with the key {companyId=20099, name=Owner}
 [parallel] com.liferay.portal.verify.VerifyException: com.liferay.portal.verify.VerifyException: com.liferay.portal.kernel.exception.NoSuchRoleException: No Role exists with the key {companyId=20099, name=Owner}`

See full console [here](https://testray.liferay.com/reports/production/logs/2021-10/test-1-30/test-portal-acceptance-pullrequest(master)/729/functional-tomcat90-mysql57-jdk8/0/15/jenkins-console.txt.gz)

Thank you!

**Pull request closed without merging**
