### PR TITLE
LPS-166303 Escape Apostrophe/Quote in localization lookups through ResourceBundleUtil

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-166303](https://issues.liferay.com/browse/LPS-166303).<br/><br/>/cc @olafk @pei-jung

### CODE REVIEW

**Comment by melodywu** [comment]
Relevant failures are not related

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
Failure not related.

**Comment by drewbrokke** [comment]
@pei-jung if this looks good to you then I think we're ready to forward.

**Review by pei-jung — APPROVED** [review]
LGTM!

**Comment by drewbrokke** [comment]
ci:reevaluate:1297401_5232

**Comment by drewbrokke** [comment]
@patriciajeanperez any issues with forwarding this one?

**Comment by patriciajeanperez** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/125409

**Pull request closed without merging**
