### PR TITLE
LPS-129713 Default to "All" filter instead of "Company Users" for Users portlet

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-129713](https://issues.liferay.com/browse/LPS-129713).<br/><br/>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Review by pei-jung — APPROVED** [review]
LGTM 👍

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
