### PR TITLE
LPS-167706 Incorporate account role assignment in the invite user workflow

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Review by drewbrokke — APPROVED** [review]
LGTM, thanks @pei-jung!

**Comment by drewbrokke** [comment]
ci:forward

**Comment by melodywu** [comment]
No related issue found in ci:test:relevant.

**Comment by pei-jung** [comment]
@melodywu @sharryxue can we manually forward this to Brian?

**Comment by Sharryxue** [comment]
Manually forwarded, refer https://github.com/brianchandotcom/liferay-portal/pull/126710.

**Comment by Sharryxue** [comment]
ci:close

**Pull request closed without merging**
