### PR TITLE
LPS-130383 Eliminate "two star" wildcard usages for the userName field

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:users

**Comment by Sharryxue** [comment]
No specific failure found in ci:test:users test suite, the failed tests are due to test fix issues.

**Comment by pei-jung** [comment]
thanks @Sharryxue

**Comment by pei-jung** [comment]
ci:forward

**Pull request closed without merging**
