### PR TITLE
LPS-156105 Mail settings of the new instances not inherited the updated server level settings

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-156105](https://issues.liferay.com/browse/LPS-156105).<br/><br/>/cc @pei-jung @ChrisKian @patriciajeanperez @epark18 @david-truong @gislayne-vitorino @RafaelCRC @victorcdp

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:reevaluate:1377401_2804

**Comment by Sharryxue** [comment]
No related failure found.

**Comment by drewbrokke** [comment]
ci:reevaluate:1377401_2804

**Comment by epark18** [comment]
@drewbrokke Relevant results looks good to me, but I think I should check  _MailEngineTest_ locally since it looks like that test did not run and it caused issues last time.

**Comment by epark18** [comment]
ci:test:bundle

**Review by pei-jung — APPROVED** [review]

**Comment by drewbrokke** [comment]
Thanks @epark18! If that's the case, we can forward this one manually.

**Comment by epark18** [comment]
Pushed to Brian. https://github.com/brianchandotcom/liferay-portal/pull/119026

**Comment by epark18** [comment]
ci:close

**Pull request closed without merging**
