### PR TITLE
LPS-156720 Privilege escalation: Role-Assign Member to Administrator

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-156720](https://issues.liferay.com/browse/LPS-156720).

@pei-jung @ChrisKian @patriciajeanperez @david-truong @gislayne-vitorino

### CODE REVIEW

**Comment by drewbrokke** [comment]
@pei-jung FYI we're choosing option number 1 on the ticket.

**Comment by drewbrokke** [comment]
Roles tab will not show in the Administrator role:
Screen Shot 2022-10-26 at 5 47 21 PM

**Comment by drewbrokke** [comment]
Direct URL access will show `error.jsp` with a "do not have permissions" message.

Screen Shot 2022-10-26 at 5 47 59 PM

**Comment by drewbrokke** [comment]
ci:test:roles

**Comment by drewbrokke** [comment]
ci:test:usm

**Comment by patriciajeanperez** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/125385

**Pull request closed without merging**
