### PR TITLE
LPS-143455 buildLang

### PR DESCRIPTION
**Pull request by ealonso**
Hey @liferay-usm,

As part of https://issues.liferay.com/browse/LPS-140253, we need to change the organization site to reflect if the private pages are enabled or not.

The changes are in d42b662 and 3df586f, the other ones are some improvements in the code that you can discard if you want.

Please let me know if you have any question.

Regards,
Eudaldo.

### CODE REVIEW

**Review by drewbrokke — APPROVED** [review]
Thanks for the pull @ealonso. The changes look good. Are there any steps for manual testing I should be aware of?

**Comment by ealonso** [comment]
Hey @drewbrokke,

You need to copy https://issues.liferay.com/secure/attachment/432837/com.liferay.layout.internal.configuration.FFDisablePrivateLayoutsConfiguration.config, in osgi > configs folder

**Comment by ealonso** [comment]
Hey @drewbrokke,

The steps to test it:

1. Copy https://issues.liferay.com/secure/attachment/432837/com.liferay.layout.internal.configuration.FFDisablePrivateLayoutsConfiguration.config, in osgi > configs folder, to enable FFDisablePrivateLayoutsConfiguration
2. Create a new Organization
3. Edit organization site

With the Feature Flag enabled you should see:

Edit_LFR_ORG_-_Liferay

The idea with this story is hide the public and private pages, so we are only going to have pages.

Let me know if you have any other question.

Regards,
Eudaldo

**Comment by drewbrokke** [comment]
Sounds good, thanks @ealonso!

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
