### PR TITLE
LPS-175187 Add endpoints to update user profile pic

### PR DESCRIPTION
**Pull request by gislayne-vitorino**
This is an update for [LPS-175187](https://issues.liferay.com/browse/LPS-175187).

### CODE REVIEW

**Comment by gislayne-vitorino** [comment]
ci:stop

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
ci:test:relevant

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
