### PR TITLE
LPS-141830 Introduce permissions to AccountGroup

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Review by drewbrokke — APPROVED** [review]
This looks good @pei-jung. Nice work!

**Comment by pei-jung** [comment]
ci:forward

**Comment by pei-jung** [comment]
ci:reevaluate:1257401_839

**Comment by epark18** [comment]
ci:test:account

**Comment by epark18** [comment]
ci:test:account

**Comment by epark18** [comment]
Hi @pei-jung, there are failures across several AccountGroups tests when trying to add an Account Group because the feature is unavailable.
[Poshi Report](https://testray.liferay.com/reports/production/logs/2021-11/test-1-13/test-portal-acceptance-pullrequest(master)/6388/functional-tomcat90-mysql57-jdk8/0/6/LocalFile.AccountGroups_CanRemoveAccountFromGroup/index.html.gz)
[Log](https://testray.liferay.com/reports/production/logs/2021-11/test-1-13/test-portal-acceptance-pullrequest(master)/6388/functional-tomcat90-mysql57-jdk8/0/6/jenkins-console.txt.gz)
image

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:account

**Comment by epark18** [comment]
Good morning @pei-jung! The related failures from Accounts test suite are gone.
There is a unique failure in **relevant**. [Error Logs](https://testray.liferay.com/reports/production/logs/2021-11/test-1-10/test-portal-acceptance-pullrequest(master)/5049/functional-upgrade-tomcat90-mysql57-jdk8/0/2/jenkins-console.txt.gz)

`    [java] 2021-11-12 17:28:51.570 INFO  [main][UpgradeProcess:126] Failed upgrade process com.liferay.account.internal.upgrade.v2_4_0.AccountGroupResourceUpgradeProcess in 7 ms
     [java] 2021-11-12 17:28:51.574 ERROR [main][UpgradeStepRegistratorTracker:143] Failed upgrade process for module com.liferay.account.service
     [java] com.liferay.portal.kernel.upgrade.UpgradeException: com.liferay.portal.kernel.exception.NoSuchResourceActionException: There are no actions associated with the resource com.liferay.account.model.AccountGroup
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:120) ~[portal-kernel.jar:?]
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:138) ~[portal-kernel.jar:?]
     [java] 	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor$UpgradeInfosRunnable.run(UpgradeExecutor.java:199) ~[?:?]`

`     [java] Caused by: com.liferay.portal.kernel.exception.NoSuchResourceActionException: There are no actions associated with the resource com.liferay.account.model.AccountGroup
     [java] 	at com.liferay.portal.service.impl.ResourcePermissionLocalServiceImpl.validate(ResourcePermissionLocalServiceImpl.java:1957) ~[portal-impl.jar:?]`

**Comment by pei-jung** [comment]
thanks @epark18! I'll take a look

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:forward

**Pull request closed without merging**
