### PR TITLE
LPS-169813 Added margin to the bottom of Add Entry button.

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
FWD: https://github.com/fortunatomaldonado/liferay-portal/pull/62

Let me know if there are any questions or comments about this.
Thank you!

> [LPS-169813](https://issues.liferay.com/browse/LPS-169813) Added margin to the bottom of Add Entry button.

### CODE REVIEW

**Review by drewbrokke — COMMENTED** [review]
@fortunatomaldonado thank you for sending this. I think I'd like to fix this at the component level. This issue is happening because we're creating the footer inside the `iframe`, but instead we should use the native modal footer if possible.

This issue is similar to another found here: https://github.com/liferay-frontend/liferay-portal/pull/2892, and in fact I think we can more or less apply the same solution. It requires a particular change in `Modal.js` to work properly: https://github.com/liferay-frontend/liferay-portal/pull/2892/files#diff-15984289d46b19a7d68a56b2d41c72a99fa2307cb9628c43f2d0f32f2b47129fR80. I'd say once that one is merged, we'll apply a similar fix here.

Thanks! I'm going to close this one for now. Let me know if you have any questions.

**Comment by fortunatomaldonado** [comment]
@SelenaAungst

**Comment by drewbrokke** [comment]
Here's an example of what the change would look like: https://github.com/pei-jung/liferay-portal/pull/843

**Comment by SelenaAungst** [comment]
Hi @drewbrokke it looks like the solution you mentioned was just merged to master (https://github.com/brianchandotcom/liferay-portal/compare/4378e841e6...184b76f2df). Do you still want me to add these same changes here, or is this being taken care of elsewhere?

**Comment by drewbrokke** [comment]
Hi @SelenaAungst, if you are willing to apply the fix, go for it! Thank you!

**Comment by SelenaAungst** [comment]
Hi @drewbrokke, 
I just wanted to ask for clarification, how/where were you suggesting this solution should be applied to solve the issue for this component?

**Comment by drewbrokke** [comment]
@SelenaAungst buttons can be added through the `openModal` config objcect, like this: https://github.com/brianchandotcom/liferay-portal/compare/4378e841e6...184b76f2df#diff-086c32e4b1a693192c566758079c2547e899c82275dd529cd5fca66a5edc5955R24-R35

The same can be applied here: https://github.com/drewbrokke/liferay-portal/blob/master/modules/apps/account/account-admin-web/src/main/resources/META-INF/resources/account_entries_admin/js/AccountUsersManagementToolbarPropsTransformer.js?plain=1#L117-L129.

Then all buttons can be removed from the jsp rendered in the modal.

Please let me know if anything is unclear. Thanks!

**Comment by SelenaAungst** [comment]
Thanks for the help so far @drewbrokke, it is much appreciated! 

I tried adding the buttons to `AccountUsersManagementToolbarPropsTransformer.js`, then I found the old footer buttons in `InviteUsersForm.tsx` (the footer buttons ended up being in this file, I could not find them in a `.jsp` file) and removed those. 

It looks like the "Invite" button no longer works now, I think because the applicable `submitForm` method is in `InviteUsersForm.tsx`. Is there some way around this?

**Comment by drewbrokke** [comment]
The modal footer submit button should still look for the first form it finds in the modal and request a submit on it. It could be a quirk of React, but it's just a guess.

Feel free to send me a pull directly (@drewbrokke) and I'll play around with it on Monday if you haven't figured it out by then. Thanks!

**Comment by SelenaAungst** [comment]
Hi @drewbrokke,
I tried a few more things that ended up not working out, so I sent you a PR (https://github.com/drewbrokke/liferay-portal/pull/1398) with just the changes you explained in your previous comment. Thank you again for your help with this and for walking me through it!

**Pull request closed without merging**
