### PR TITLE
LPS-151918 As a developer using headless endpoints, I'd like to create a region and know which fields are required

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by Sharryxue** [comment]
The [semantic-versioning-jdk8/0/0](https://testray.liferay.com/zh/home/-/testray/case_results/1796601048?redirect=https%3A%2F%2Ftestray.liferay.com%2Fzh%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1796595261%26testrayRunId%3D1796600553%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) issue probably related to commit [LPS-151918 Baseline](https://github.com/liferay-usm/liferay-portal/pull/561/commits/ca0d4daeeab91a20d201b78c8f256a7fc8bf22ab). Would you @pei-jung please help to confirm? Thanks

**Review by drewbrokke — APPROVED** [review]
The changes look good, @pei-jung. Once we fix the rebase error and pass CI this is good to go!

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
