### PR TITLE
LPS-141830 Add tests for AccountGroup remote services

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by epark18** [comment]
ci:test:relevant

**Comment by epark18** [comment]
ci:test:account

**Comment by epark18** [comment]
Accounts failure is unrelated to the pull :]

**Review by drewbrokke — APPROVED** [review]
Changes look good @pei-jung. Looks like there's a merge conflict so once you re-send or force-push we're good to go on this one

**Comment by pei-jung** [comment]
ci:forward

**Comment by epark18** [comment]
There is only one unique failure `Execute failed: java.io.IOException: Cannot run program "mysql57" (in directory "/opt/dev/projects/github/liferay-portal"): error=2, No such file or directory` here, but I don't think it is related to the pull. I can rerun relevant to make sure. [Error Logs](https://testray.liferay.com/reports/production/logs/2021-11/test-1-19/test-portal-acceptance-pullrequest(master)/8741/functional-upgrade-tomcat90-mysql57-jdk8/0/2/jenkins-console.txt.gz)

**Comment by epark18** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
Hi @epark18, can you forward this pull to Brian? Thank you!

**Comment by patriciajeanperez** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/110113

**Comment by patriciajeanperez** [comment]
ci:close

**Pull request closed without merging**
