### PR TITLE
LPS-171688 Add annotation to the methods searchCountries and searchRegions

### PR DESCRIPTION
**Pull request by gislayne-vitorino**
This is an update for: [subtask: LPS-171688](https://issues.liferay.com/browse/LPS-171688), [LPS-164438](https://issues.liferay.com/browse/LPS-164438)

### CODE REVIEW

**Review by pei-jung — APPROVED** [review]
LGTM!

**Comment by melodywu** [comment]
No related issue found in ci:test:relevant.

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
ci:test:relevant

**Comment by melodywu** [comment]
No related issue found in ci:test:relevant.

**Comment by drewbrokke** [comment]
@patriciajeanperez if this looks good to you, I think we can go ahead and forward.

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
ci:forward

**Comment by patriciajeanperez** [comment]
Sorry @drewbrokke, I just saw your comment. I will manually forward if this one fails. Thanks!

**Comment by drewbrokke** [comment]
No worries @patriciajeanperez, thank you!

**Comment by patriciajeanperez** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/128425

**Pull request closed without merging**
