### PR TITLE
LPS-132250 Provide on-demand admin access to virtual instances

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Review by drewbrokke — CHANGES_REQUESTED** [review]
Looks great @pei-jung. The only comment I have is that I think we can just put one `.lfrbuild-releng-ignore` file in the module group directory instead of each individual module. Otherwise I think it's good to go.

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:forward

**Pull request closed without merging**
