### PR TITLE
LPS-139430 As an Administrator, I want to assign a User to Accounts

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-139430](https://issues.liferay.com/browse/LPS-139430).<br/><br/>/cc @pei-jung @alee8888 @ChrisKian @patriciajeanperez @lr-leo @erickmonteiroo

### CODE REVIEW

**Comment by epark18** [comment]
ci:test:account

**Comment by epark18** [comment]
Most of the account failures should be fixed with this ticket merged https://issues.liferay.com/browse/LRQA-72894. One of our common macros has been failing and needed updating. 

There is a unique failure in _AccountUsers#CannotSelectPersonAccountWithUserAssigned_ where the test has the option to still select an assigned Person Account. [Case Results](https://testray.liferay.com/home/-/testray/case_results/1605551702) | [Poshi Report](https://testray.liferay.com/reports/production/logs/2022-01/test-1-31/test-portal-acceptance-pullrequest(master)/1946/functional-tomcat90-mysql57-jdk8/0/8/LocalFile.AccountUsers_CannotSelectPersonAccountWithUserAssigned/index.html.gz) | [Error Logs](https://testray.liferay.com/reports/production/logs/2022-01/test-1-31/test-portal-acceptance-pullrequest(master)/1946/functional-tomcat90-mysql57-jdk8/0/8/jenkins-console.txt.gz). 

image

**Comment by epark18** [comment]
Although when I run the test locally on my master, there is an option for two Person accounts instead of just the one.
LPS-139430-localtest

**Comment by drewbrokke** [comment]
See https://github.com/liferay-usm/liferay-portal/pull/435

**Pull request closed without merging**
