### PR TITLE
LPS-163638

### PR DESCRIPTION
**Pull request by natocesarrego**
Hi,

Basically, this pull introduces a new entry in Instance Settings to allow the user configure the locale in friendly URLs. This is a demand from a customer in pure LXC. Perhaps, @liferay-core-infra, would like to take a look on this pull since it manipulates the usage of the portal property `locale.prepend.friendly.url.style`.

Thanks in advance for your review! :smile: 

Jira ticket: https://issues.liferay.com/browse/LPS-163638

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:friendly-url

**Comment by vicnate5** [comment]
ci:stop

**Comment by vicnate5** [comment]
I noticed an issue with our friendly url test suite, I am running it here with this code and the test suite fix:
https://github.com/vicnate5/liferay-portal/pull/2188

**Comment by melodywu** [comment]
No related issue found in ci:test:relevant and ci:test:friendly-url of [vicnate#2188](https://github.com/vicnate5/liferay-portal/pull/2188)

**Review by drewbrokke — CHANGES_REQUESTED** [review]
@natocesarrego this seems fine to me. 

One thing I'd like to check though, is whether it's necessary to even pass in the default value `PropsValues.LOCALE_PREPEND_FRIENDLY_URL_STYLE` in all the usages. I think that the default value will already be `PropsUtil.get(key)` by default. Would you be willing to double-check that? If so we can probably simplify all these calls.

**Comment by natocesarrego** [comment]
Thank you very much for your review, @drewbrokke! :slightly_smiling_face: 

I just double checked the implementation of `PropsUtil.get(key)` and, from what I could see, it doesn't return the default value of the property associated to the key.

**Comment by drewbrokke** [comment]
@natocesarrego I'm looking at this spot here: https://github.com/liferay/liferay-portal/blob/7e52e9fb4195eb8526180b5036c5211cd6e5e46c/portal-impl/src/com/liferay/portal/util/PrefsPropsUtil.java#L274-L280. I believe I ran into an issue with this at some point where because of this line, the default value I was passing in was actually ignored completely.

Am I missing something?

**Comment by natocesarrego** [comment]
Hey @drewbrokke,

Sorry about that! I did a quick double checking and I didn't go deeper into the method [_getConfiguration](https://github.com/liferay/liferay-portal/blob/197f259f54e8b6d86666d184966e1601c5b03cc2/portal-impl/src/com/liferay/portal/util/PropsUtil.java#L254-L256) before, but now I realized that this method indeed does what you said. Thank you very much! :smile: 

I just updated the pull according to your suggestion. :slightly_smiling_face:

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:forward

**Comment by natocesarrego** [comment]
ci:forward

**Comment by Sharryxue** [comment]
No related issue found in [ci:test:relevant](https://github.com/liferay-usm/liferay-portal/pull/864#issuecomment-1322458898), will manually forward the commits.

**Comment by Sharryxue** [comment]
Manually forwarded. Refer https://github.com/brianchandotcom/liferay-portal/pull/126645.

**Comment by Sharryxue** [comment]
ci:close

**Comment by natocesarrego** [comment]
Thanks, @Sharryxue, for forwarding this pull :smile:

**Pull request closed without merging**
