### PR TITLE
LPS-137453 Support get via headless-user-admin for Role's actions

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:relevant

**Review by drewbrokke — CHANGES_REQUESTED** [review]

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
Hey @drewbrokke, is this pull ready to be forwarded?

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
