### PR TITLE
LPS-151552 Removing and re-adding account role permission makes Group Scope permission disappear

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-151552](https://issues.liferay.com/browse/LPS-151552).<br/><br/>/cc @pei-jung @erickmonteiroo @ChrisKian @patriciajeanperez @epark18 @david-truong

### CODE REVIEW

**Review by pei-jung — APPROVED** [review]
LGTM!

**Comment by epark18** [comment]
CI failure is unrelated.

**Comment by drewbrokke** [comment]
@epark18 if this looks good to you, then feel free to manually forward.

**Comment by drewbrokke** [comment]
ci:reevaluate:1297401_2538

**Comment by epark18** [comment]
Pushed to BChan: [brianchandotcom#116184](https://github.com/brianchandotcom/liferay-portal/pull/116184).

**Comment by epark18** [comment]
ci:close

**Pull request closed without merging**
