### PR TITLE
LPS-168540 Screen reader should announce the role title when Choose b…

### PR DESCRIPTION
**Pull request by pat270**
…utton is focused

https://issues.liferay.com/browse/LPS-168540

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
ci:test:roles

**Comment by drewbrokke** [comment]
ci:reevaluate:1257401_6152

**Comment by drewbrokke** [comment]
@patriciajeanperez are the roles failures related?

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
