### PR TITLE
LPS-127473 Bridge Commerce's Address with Portal's Address

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-127473](https://issues.liferay.com/browse/LPS-127473).<br/><br/>/cc @patriciajeanperez @Sharryxue

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:forward

**Comment by Sharryxue** [comment]
- The [lpkg-base-jdk8/0/0](https://testray.liferay.com/zh/home/-/testray/case_results/1546187600) failure not related, it more like failed for a broswer related issue.
- The [SampleSQLBuilderTest](https://testray.liferay.com/zh/home/-/testray/case_results/1546187614) seems failed for a related issue, refer [console](https://testray.liferay.com/reports/production/logs/2021-07/test-1-15/test-portal-acceptance-pullrequest(master)/4603/modules-unit-jdk8/0/0/jenkins-console.txt.gz), hello @drewbrokke, would you please take a look into it? Thanks
```
     [exec]     01:02:30,492 ERROR [runtime:59] Error executing FreeMarker template
     [exec]     freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
     [exec]     ==> commerceAccountEntryModels  [in template "com/liferay/portal/tools/sample/sql/builder/dependencies/commerce_groups.ftl" at line 3, column 60]
```

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
@patriciajeanperez is this a related failure?

**Comment by Sharryxue** [comment]
The failed test not related to the changes, will manully forward the pr.

**Comment by drewbrokke** [comment]
Merged in https://github.com/brianchandotcom/liferay-portal/pull/104261

**Pull request closed without merging**
