### PR TITLE
LPS-149319 Create view page for configuring email server at company level

### PR DESCRIPTION
**Pull request by erickmonteiroo**
@drewbrokke @pei-jung

### CODE REVIEW

**Review by drewbrokke — CHANGES_REQUESTED** [review]

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by erickmonteiroo** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
