### PR TITLE
LPS-162692 Remove redundant usages of the method getSearchActionURL

### PR DESCRIPTION
**Pull request by gislayne-vitorino**
This is an update for: [sub-task: LPS-162692](https://issues.liferay.com/browse/LPS-162692), [LPS-161233](https://issues.liferay.com/browse/LPS-161233)

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:forwrad

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
ci:reevaluate:1297401_4680

**Comment by drewbrokke** [comment]
@patriciajeanperez we can forward this one.

**Comment by Sharryxue** [comment]
Will manually forward the pr.

**Comment by Sharryxue** [comment]
ci:close

**Pull request closed without merging**
