### PR TITLE
LPS-152407 Account Address as system object

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-152407](https://issues.liferay.com/browse/LPS-152407).<br/><br/>/cc @pei-jung @ChrisKian @patriciajeanperez @epark18 @david-truong @gislayne-vitorino @RafaelCRC @victorcdp

### CODE REVIEW

**Review by pei-jung — APPROVED** [review]
LGTM! 👍

**Comment by pei-jung** [comment]
@epark18 @sharryxue are the failures related?

**Comment by samuelromeiro** [comment]
New related Jira ticket: [LPS-155961](https://issues.liferay.com/browse/LPS-155961)

**Comment by drewbrokke** [comment]
New PR with the appropriate ticket number: https://github.com/liferay-usm/liferay-portal/pull/604

**Pull request closed without merging**
