### PR TITLE
LPS-150976 Get UserAccount in a specfic account (by externalReferenceCode) that has a specfic role

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-150976](https://issues.liferay.com/browse/LPS-150976).<br/><br/>/cc @pei-jung @erickmonteiroo @ChrisKian @patriciajeanperez @epark18 @david-truong

### CODE REVIEW

**Comment by drewbrokke** [comment]
This pull request does not address the limitation described [here](https://github.com/liferay-usm/liferay-portal/pull/524#issuecomment-1097455238). I have started looking at the issue and think it will take quite a bit of planning to solve, so for now I am submitting this change as-is, but will continue investigating a solution going forward.

**Comment by pei-jung** [comment]
`userGroupRoleNames` needs to be added to `UserIndexerIndexedFieldsTest.java` too. Everything else looks good!

**Comment by drewbrokke** [comment]
@pei-jung I went back and forth about whether or not to add them. I think that `roleNames` needed to be added to the test case because the user will by default have regular roles associated with them, but for example `userGroupRoleIds` is not there because the user does not have any site/org/account roles assigned to them by default, so there will be no `userGroupRoleIds` or `userGroupRoleNames` in the document. Same goes for `lastLoginDate`. So in this case, if we want to add them to the test, we'll also probably have to adjust the setup. Thoughts?

**Comment by pei-jung** [comment]
@drewbrokke I see. I thought it will affect the search test. This is good to go then.

**Comment by pei-jung** [comment]
ci:forward

**Pull request closed without merging**
