### PR TITLE
LPS-150975 Filter by lastLoginDate in getAccountUserAccountsByExternalReferenceCode

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-150975](https://issues.liferay.com/browse/LPS-150975).<br/><br/>/cc @pei-jung @erickmonteiroo @ChrisKian @patriciajeanperez @epark18 @david-truong

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@epark18 are these failures related?

**Comment by epark18** [comment]
@drewbrokke looks good to me, would you like me to manually forward?

**Comment by drewbrokke** [comment]
@epark18 if it looks good to you, go ahead! Thanks!

**Comment by epark18** [comment]
Pushed to BChan: [brianchandotcom#115989](https://github.com/brianchandotcom/liferay-portal/pull/115989)

**Pull request closed without merging**
