### PR TITLE
LPS-166931 Fix remaining usages for Contact_ table

### PR DESCRIPTION
**Pull request by gislayne-vitorino**
This is an update for: [subtask: LPS-166931](https://issues.liferay.com/browse/LPS-166931), [task: LPS-155969](https://issues.liferay.com/browse/LPS-155969)

### CODE REVIEW

**Review by drewbrokke — APPROVED** [review]

**Comment by melodywu** [comment]
No related issue found in ci:test:relevant.

**Comment by ling-alan-huang** [comment]
see https://liferay.slack.com/archives/C1SJ64S9X/p1667504745194109

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
ci:forward

**Comment by patriciajeanperez** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/125830

**Pull request closed without merging**
