### PR TITLE
LPS-151909 As a developer using headless endpoints, I'd like to update a country by countryId via partial update and full replace

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-151909](https://issues.liferay.com/browse/LPS-151909).<br/><br/>/cc @pei-jung @erickmonteiroo @ChrisKian @patriciajeanperez @epark18 @david-truong

### CODE REVIEW

**Review by pei-jung — APPROVED** [review]
LGTM!

**Comment by erickmonteiroo** [comment]
LGTM!

**Review by erickmonteiroo — APPROVED** [review]

**Comment by drewbrokke** [comment]
ci:reevaluate:1307401_3289

**Comment by epark18** [comment]
Test failures are unrelated here.

**Comment by drewbrokke** [comment]
@epark18 thanks! If it looks good to you, go ahead and forward.

**Comment by epark18** [comment]
Pushed to BChan. https://github.com/brianchandotcom/liferay-portal/pull/117304

**Comment by epark18** [comment]
ci:close

**Pull request closed without merging**
