### PR TITLE
LPS-178134 Create a new language in the portal: Cambodian (Khmer) as Beta

### PR DESCRIPTION
**Pull request by hhtank**

### CODE REVIEW

**Comment by hhtank** [comment]
ci:test:relevant
ci:test:sf

**Review by drewbrokke — APPROVED** [review]
Looks great, thank you @hhtank!

**Comment by drewbrokke** [comment]
@hhtank please double-check the SF failures. It may just require a rebase.

**Comment by hhtank** [comment]
> @hhtank please double-check the SF failures. It may just require a rebase.

Hi @drewbrokke, 
I have rebased and pushed to my branch again. Would you mind to forward again?

Thanks,

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
@hhtank looks like there's another merge conflict. Please rebase and resend. Overall this looks good though.

**Comment by hhtank** [comment]
@drewbrokke I pushed the rebase again. Please help forward again. Thanks!

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
@patriciajeanperez do these failures look related to you?

**Comment by patriciajeanperez** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/132498

**Pull request closed without merging**
