### PR TITLE
LPS-168452 Bundle blacklist integration test is aborted when running testAddToAndRemoveFromBlacklist

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-168452](https://issues.liferay.com/browse/LPS-168452).

FYI @tinatian

/cc x@pei-jung @ChrisKian @patriciajeanperez @david-truong @gislayne-vitorino

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:reevaluate:1377401_8886

**Comment by drewbrokke** [comment]
@patriciajeanperez if this one looks ok to you then we can forward.

**Comment by patriciajeanperez** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/130408

**Pull request closed without merging**
