### PR TITLE
[TS] LPS-134096

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-134096

Please let me know if you have any questions, or if I should forward this fix to the core-infra team.  Thanks!

### CODE REVIEW

**Comment by Sharryxue** [comment]
The [semantic-versioning-jdk8/0](https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/478528/) failure seems related, would you please double check? @ChrisKian , thanks. No other related failure found.
```
[beanshell]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
[beanshell] = ================================================== ========== ========== ========== ========== ==========
[beanshell]   com.liferay.portal.kernel.service                  MINOR      5.6.0      5.4.0      5.5.0      EXCESSIVE VERSION INCREASE
```

**Comment by ChrisKian** [comment]
Hi @Sharryxue,
I incremented the version from `5.5.0` to `5.6.0`, however the failure is claiming the base version is `5.4.0`.  I believe this error is happening due to the base version of the liferay-usm repo vs the base version of the PR (about 76 commits).  You can also see [this commit](https://github.com/liferay-usm/liferay-portal/pull/102/commits/69c6a40bd3be3aa4a2f58761c77744c2bf2e6d03) which is included in this PR but not the base branch increments from `5.4.0` to `5.5.0`.

Please let me know if you have any questions, and how we should proceed.  Thanks!

**Comment by Sharryxue** [comment]
Got it, thanks for your explaination and sorry for any confusion @ChrisKian, not sure if a rebase would resolve the issue, will try a retrigger of ci:test:relevant.

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Resent here: https://github.com/liferay-usm/liferay-portal/pull/107

**Pull request closed without merging**
