### PR TITLE
LPS-161223 Use Apache Commons Validator version 1.7

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-161223](https://issues.liferay.com/browse/LPS-161223).

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@patriciajeanperez if the failures are unrelated, we can manually forward.

**Comment by patriciajeanperez** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/122138

**Comment by patriciajeanperez** [comment]
ci:close

**Pull request closed without merging**
