### PR TITLE
LPS-165903 | master

### PR DESCRIPTION
**Pull request by sontruongces**
Hi team,

This is the fix for the [LPS-165903](https://issues.liferay.com/browse/LPS-165903), the original has passed my review at sontruongces#52. Please help me to review and give feedback.

Thanks,
cc: @ces-huynguyen

### CODE REVIEW

**Comment by Sharryxue** [comment]
No related issue found in ci:test:relevant. Test fix is required with the commits for following tests, or we can fix the affected tests later since we probably need trigger ci:test:usm and ci:test:account to confirm if there are hidden tests that need update. /cc @patriciajeanperez 
[LocalFile.AccountGroups#CanRemoveAccountFromGroup](https://testray.liferay.com/home/-/testray/case_results/2021755027)
[LocalFile.Accounts#CanDeactivateAccount](https://testray.liferay.com/home/-/testray/case_results/2021755126)
[LocalFile.Accounts#CanDeleteAccount](https://testray.liferay.com/home/-/testray/case_results/2021755099)

**Comment by patriciajeanperez** [comment]
ci:test:usm

**Comment by melodywu** [comment]
Hi @ces-huynguyen, Is it an expect result that when it is empty the search bar is gray out? If it is an expect result we will update our testcases. Thanks a lot. /cc @drewbrokke @patriciajeanperez @pei-jung 
Screenshot from 2022-10-31 15-31-06

**Comment by ces-huynguyen** [comment]
> Hi @ces-huynguyen, Is it an expect result that when it is empty the search bar is gray out? If it is an expect result we will update our testcases. Thanks a lot. /cc @drewbrokke @patriciajeanperez @pei-jung
> 
> Screenshot from 2022-10-31 15-31-06

Hi @melodywu,

**Comment by ces-huynguyen** [comment]
> Hi @ces-huynguyen, Is it an expect result that when it is empty the search bar is gray out? If it is an expect result we will update our testcases. Thanks a lot. /cc @drewbrokke @patriciajeanperez @pei-jung
> 
> Screenshot from 2022-10-31 15-31-06

Hi @melodywu, 
  According to this ticket https://issues.liferay.com/browse/LPS-165903, expected result when it is empty the search bar is gray out. Same as the way did in Accounts > Account Groups. 
 Thanks,

**Comment by melodywu** [comment]
No related issue found in ci:test:usm. Test fix is required with the commits.
For checkbox and filter affect 10 testcases:
```
LocalFile.Accounts#CanEditInactiveAccount
LocalFile.Accounts#CanDeleteAnInactiveAccount
LocalFile.Accounts#CanDeleteAccount
LocalFile.Accounts#CanActivateAnInactiveAccount
LocalFile.AccountUsers#CanDeactivateUser
LocalFile.AccountGroups#CanRemoveAccountFromGroup
LocalFile.Accounts#CanDeactivateAccount
LocalFile.AccountPermissions#AccountAdminCanDeactivateAccount
LocalFile.Accounts#CanDeactivateAndActivateAccountsInBulk
LocalFile.GDPR#PaginationWorksInExportPersonalData
```
For search bar affect 3 testcases:
```
LocalFile.Accounts#ClickingCancelOrBackWillNotSaveAccount
LocalFile.Accounts#CannotAddShippingAddressAsDefaultBilling
LocalFile.Accounts#CannotAddBillingAddressAsDefaultShipping
```

**Review by drewbrokke — COMMENTED** [review]
@sontruongces @ces-huynguyen thank you for sending this change. After looking at this a bit more, I think a more fundamental change is needed in the defaults provided to all the classes that extend the `SearchContainerManagementToolbarDisplayContext`. In the end, `isDisabled` is not usually what we want, but instead we should be asking about `isSelectable`. I've sent a PR here to update the defaults: https://github.com/liferay-frontend/liferay-portal/pull/2831. 

As for the unique changes in roles and organizations, we should apply the changes for `isSelectable` rather than `isDisabled` here as well. I am going to close this pull in favor of the one mentioned above, but feel free to re-send the other pieces not affected by that pull.

Please let me know if you have any questions or concerns. Thank you!

**Comment by drewbrokke** [comment]
Closing for now in favor of https://github.com/liferay-frontend/liferay-portal/pull/2831.

**Pull request closed without merging**
