### PR TITLE
LPS-156573 As a user I'd like to have Commerce's MANAGE_AVAILABLE_ACCOUNTS permission available in portal

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-156573](https://issues.liferay.com/browse/LPS-156573).

@pei-jung a notable addition with this pull request: The `MANAGE_SUBORGANIZATIONS_ACCOUNTS` action now grants `VIEW` privileges for accounts associated with the suborganizations by default. For all other actions acting on sub-org accounts, the relevant permissions are still required.

/cc @pei-jung @ChrisKian @patriciajeanperez @epark18 @david-truong @gislayne-vitorino @RafaelCRC

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by melodywu** [comment]
These failures are not related to this PR.

**Comment by melodywu** [comment]
ci:test:usm

**Comment by melodywu** [comment]
ci:test:account

**Comment by melodywu** [comment]
ci:test:roles

**Comment by drewbrokke** [comment]
ci:reevaluate:1377401_3872

**Comment by drewbrokke** [comment]
ci:reevaluate:1397401_424

**Comment by drewbrokke** [comment]
ci:reevaluate:1377401_3871

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@patriciajeanperez @epark18 are these failures related?

**Comment by epark18** [comment]
@drewbrokke looks good to me! No unique failures.

**Review by pei-jung — APPROVED** [review]
LGTM! 👍

**Comment by drewbrokke** [comment]
@epark18 if this looks ok to you, I think we can manually forward.

**Comment by epark18** [comment]
Forwarded to Brian. https://github.com/brianchandotcom/liferay-portal/pull/121249

**Comment by epark18** [comment]
ci:close

**Pull request closed without merging**
