### PR TITLE
LPS-131641 Remove ThemeDisplay from method signatures in account-admin-web AccountEntryDisplay.java

### PR DESCRIPTION
**Pull request by erickmonteiroo**
@drewbrokke

### CODE REVIEW

**Comment by erickmonteiroo** [comment]
ci:test:sf

**Comment by epark18** [comment]
ci:test:account

**Comment by epark18** [comment]
@erickmonteiroo It looks like the changes caused some of the Accounts tests to fail. Tests that run the command to "Enable Email Domain Validation" are failing during the account creation step because the "Valid Domains" section is missing. 
image (This image is from my master)

Looking at the [Poshi Test Report](https://testray.liferay.com/reports/production/logs/2021-11/test-1-28/test-portal-acceptance-pullrequest(master)/1046/functional-tomcat90-mysql57-jdk8/0/10/LocalFile.Accounts_WarningDisplaysWhenAddingUserWithBlockedEmailDomain/index.html.gz) for this PR and the attached image: 
image it's showing no section for "Valid Domains" and no way to add any. [Logs](https://testray.liferay.com/reports/production/logs/2021-11/test-1-28/test-portal-acceptance-pullrequest(master)/1046/functional-tomcat90-mysql57-jdk8/0/10/jenkins-console.txt.gz)

**Comment by erickmonteiroo** [comment]
ci:test:account

**Comment by epark18** [comment]
@erickmonteiroo Looks good now, no more email domain errors and other accounts failures are unrelated.

**Comment by erickmonteiroo** [comment]
ci:forward

**Comment by erickmonteiroo** [comment]
ci:reevaluate:1277401_862

**Comment by erickmonteiroo** [comment]
ci:reevaluate:1277401_862

**Comment by erickmonteiroo** [comment]
ci:test:relevant

**Comment by erickmonteiroo** [comment]
ci:forward

**Pull request closed without merging**
