### PR TITLE
LPS-129587 Migrate selection modals in users-admin

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:reevaluate:1187401_5776

**Comment by pei-jung** [comment]
@patriciajeanperez are these failures related?

**Comment by patriciajeanperez** [comment]
Hi @pei-jung! no related failures but looks like it needs rebasing.

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:forward

**Pull request closed without merging**
