### PR TITLE
LPS-130793 Unify the AccountUser object with the UserAccount object in the account-rest module schema.

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-130793](https://issues.liferay.com/browse/LPS-130793).<br/><br/>/cc @pei-jung @alee8888 @ChrisKian @patriciajeanperez @lr-leo

/cc @luca-pellizzon @marco-leo I did not see any current usages of the changed endpoints in portal that needed updating. Will you please check any in-progress work that may be affected by this change? 

The main difference is this: 
• account-user -> user-account (endpoint path)
• accountUser -> userAccount (GraphQL resource name)
• AccountUser -> AccountUserAccount (GraphQL resource name)

-------------

Edit: additional changes pushed:
• UserAssociation -> UserAccountAssociation (GraphQL resource name)
• AccountRole -> AccountAccountRole (GraphQL resource name)

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
Hello @drewbrokke,
yes, our in-progress work will be affectd, but we will take care of that.
Just keep us updated on the status of this PR so that we know when it will be merged in master.
Thank you.

**Comment by drewbrokke** [comment]
Thanks @luca-pellizzon, will do.

**Comment by drewbrokke** [comment]
ci:reevaluate:1287401_416

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
